### ISSUE TITLE
Can't install autoortho 

### ISSUE THREAD

**Issue by PVPVA** [kubilus1/autoortho#100]
hello everyone I've installed autoortho as suggested however despite of my several attempts I always have the same error,
Any help or sugestion will be appreciated thank you.

![autoortho](https://user-images.githubusercontent.com/94744360/231010514-4165f367-4975-4c96-866a-b13a57305078.jpg)
![autoortho_1](https://user-images.githubusercontent.com/94744360/231010515-726e6e0c-b588-470a-9de7-fb2285031379.jpg)

**Comment by jwisey** [comment]
Hey @PVPVA - I am having the same issue. Did you get to the bottom of this?

**Comment by mb-simulations** [comment]
It does seem like there are problems when it tries to link the different parts to the texture folder. I had the same issue when trying this somewhere else, than on my C drive but could not dig deeper into it yet but maybe it helps to find the issue or even the solution.

**Comment by jwisey** [comment]
Thanks @mb-simulations - I guess I should move my sim the C drive and then try again or wait for an update.

**Comment by mckleashey123** [comment]
ensure the directory paths for the source and target directories are accurate and have no typos. If the paths are correct, try running the command prompt as an administrator and retry the mklink command (In the command prompt you left a character in there that shoundt have been there [ ' ]):

mklink /J "H:\XPLANE12\CUSTOM SCENERY\z_aus_pac_00\textures" "H:\XPLANE12\CUSTOM SCENERY\z_autoortho\textures"

This is what you need to run
