### ISSUE TITLE
Divide cache folder by tile

### ISSUE THREAD

**Issue by evilstiefel** [kubilus1/autoortho#101]
The cache folder gets quite unwieldy after some time, with millions of files. Windows doesn't cope well with folders that contain that many files in the explorer. It would maybe be a good idea to divide them by tile boundary or ortho provider. This would also make it easier to delete certain areas from the cache.

Maybe it could be a setting in the config to not make existing user's cache folder invalid, or migrate the files on boot.

For clarification: looking through the code, the rows and cols in the filenames don't easily convert to latitude and longitude, but that's what I mean by "tile boundary", so much like ortho4xp groups/generates DSF files. Folders could be named in a format like

* "5040N" for 50deg N, 40deg E
* "50N40" for 50deg N, 140deg E
 
* "5040E" for 50deg S, 40deg E
* "50E40" for 50deg S, 140deg E

* "5040S" for 50deg S, 40deg W
* "50S40" for 50deg S, 140deg W

* "5040W" for 50deg N, 40deg W
* "50W40" for 50deg N, 140deg W

So much like the shorthand for latitude and longitude on a lot of FMCs, making folder names always have the same length and easy format to recognize.

**Comment by jonaseberle** [comment]
I like the idea of having a directory structure in the file cache to make it easier to prune areas. 

But your (ARINC) format for coordinates is pretty tedious ;)

I would try to stay close to the X-Plane .dsf format:
```
cache/
├── -60+160
│   ├── -51+165
│   │   ├── {col}_{row}_{zoom}_{maptype}.jpg
│   │   ...
│   ...
...
```

That could probably be done at the cache implementation level (in `Chunk::cache_path`/`Chunk::get_cache()` /`::save_cache()` and would need to calculate that path from row/col. 

@kubilus1 I can work on that.
