### ISSUE TITLE
Changing Config file

### ISSUE THREAD

**Issue by KennardTV** [kubilus1/autoortho#102]
Is there anyway of changing the ortho cfg file from my C: drive? I have it set to my F: Drive but it still goes to my C: drive with about 20gb left if I try to install NA its 24gb. So can I config the files to download somewhere else?

**Comment by DraggeBagge** [comment]
I have the same issue! This should be prioritized during next builds as most of us have little space on C drive

**Comment by hakanr339b** [comment]
you should delete .autoortho file in the c:/users/(name)
if this doesnt work, delete .autoortho-data folder too

**Comment by Made1Kraken** [comment]
> you should delete .autoortho file in the c:/users/(name) if this doesnt work, delete .autoortho-data folder next to it too

tried that multiple times but when the .exe runs, it automatically just creates a new folder in the same location (C Drive under users/name)

**Comment by mckleashey123** [comment]
> > you should delete .autoortho file in the c:/users/(name) if this doesnt work, delete .autoortho-data folder next to it too
> 
> tried that multiple times but when the .exe runs, it automatically just creates a new folder in the same location (C Drive under users/name)

Same here, I tried to create a symlink but that didn't do anything.
