### ISSUE TITLE
About FAQ: Windows Defender marking the addon as virus

### ISSUE THREAD

**Issue by hakanr339b** [kubilus1/autoortho#109]
Isn't there a way that defender to stop marking it as virus? The thing it keeps deleting my file over and over each time. I want to keep defender active while preventing it to mark this as virus since it's not.

**Comment by wiggleforlife** [comment]
Open Windows Security > Virus and threat protection > Manage settings > Add or remove exclusions > Add a process "autoortho_win.exe" should work. This removed a lot of CPU overhead from `MsMpEng.exe` as well for me.
