### ISSUE TITLE
Not working in Hawaii

### ISSUE THREAD

**Issue by BlaineElMono** [kubilus1/autoortho#110]
Excellent program.
I installed all regions, flew to different parts of the world and it works perfectly.
So far the only place I don't see Ortho is in Hawaii. Only the default X-Plane scenery appears.

Attached is my scenario file
[scenery_packs.ini.txt](https://github.com/kubilus1/autoortho/files/11304707/scenery_packs.ini.txt)

and my log file
[Log.txt](https://github.com/kubilus1/autoortho/files/11304709/Log.txt)

**Comment by kubilus1** [comment]
Yeah I think Hawaii was part of the demo scenery that didn't make it into the prior builds of scenery for this project.   Should be resolved with the next scenery update.

**Comment by BlaineElMono** [comment]
> Yeah I think Hawaii was part of the demo scenery that didn't make it into the prior builds of scenery for this project.   Should be resolved with the next scenery update.

Thanks!!!

**Comment by BlaineElMono** [comment]
I confirm that with the new scenario update it works correctly.
Thanks
