### ISSUE TITLE
Cannot download current set for North America

### ISSUE THREAD

**Issue by evilstiefel** [kubilus1/autoortho#114]
Might be the wrong repo for this, but currently, downloading the NA-set gives an error for the Zip-file for *.00 when trying to extract:

Retrying doesn't help, so it's definitely the hosted file and not the download.

![image](https://user-images.githubusercontent.com/8029370/234559124-53899d5e-583d-4d57-b8a8-77143a7379f8.png)

**Comment by evilstiefel** [comment]
Same issue for _asi_02

![image](https://user-images.githubusercontent.com/8029370/234585617-5fe8f804-9b59-406b-bcbc-93045cb1db27.png)

**Comment by kubilus1** [comment]
Thanks!  Should be fixed now.  You may need to clear our your .autoorth-data/downloads folder, then retry.
