### ISSUE TITLE
Asterisk sign for folder name

### ISSUE THREAD

**Issue by hawajka76** [kubilus1/autoortho#115]
Hello, 
I'm keep the Custom Scenery folder on a ntfs formatted drive . As some of the scenery  folders contain the asterisk sign in the naming convention, it is quite challenging to use autoortho, as need to implement some pretty sketchy workarounds. Is it possible to change the naming convention of the folders which contain the asterisk sign in their name to something ntfs friendly?

**Comment by kubilus1** [comment]
I don't know what you are referring to.  Do you have an example?

**Comment by hawajka76** [comment]
Hi, for example the folder yAutoOrtho_Overlays contains a folder named "*".

**Comment by hawajka76** [comment]
> I don't know what you are referring to. Do you have an example?

Hi just to touch base, is the example I provided ok?

**Comment by hawajka76** [comment]
Bumping to unstale. Also just to check is the problem I described clearer now?

**Comment by dpdurst** [comment]
Did you name a folder with a * as AO does not when installing. If so folder names with * in them will not work. Please provide a screenshot and your autoortho.log file.

**Comment by hawajka76** [comment]
I did not make one like that. It is located in Documents/XP11 Autoortho/AutoOrthCustomScenery/yAutoOrtho_Overlays/Earth nav data. I'm attaching a screenshot and part of the log file which mentions that the * folder can not be accessed when I copied all remaining files to a ntfs drive. 
![Asterisk folder](https://github.com/kubilus1/autoortho/assets/35002520/695e18f9-6f5d-4851-8d00-fb69a90e772e)
[autoortho asterisk log](https://github.com/kubilus1/autoortho/files/11992551/autoortho.asterisk.log)

**Comment by dpdurst** [comment]
You installed first time to this location and it was working, not sure what got changed after but to me the config files look to have been changed for locations. I'd remove everything and set back up and see if that error comes back.

Was working here at 2100 hours

INFO:aoconfig:Creating dir /home/piotr/.steam/steam/steamapps/common/X-Plane 11/Custom Scenery/z_autoortho

INFO:autoortho_fuse:First matched DDS file /37360_56848_BI16.dds detected.  Start flight tracker.
WARNING:getortho:GET_IMG: Empty chunk data.  Skip.
INFO:aostats:STATS: ID: {'count': 558, 'chunk_miss': 558, 'bytes_dl': 9784106, 'partial_mm_averages': {0: 0.001}, 'partial_mm_counts': {0: 25}, 'backup_chunk_count': 16, 'mm_counts': {0: -1, 1: -1, 2: -1, 3: -1, 4: 18}, 'mm_averages': {0: -1, 1: -1, 2: -1, 3: -1, 4: 0.001}, 'chunk_missing_count': 1}
WARNING:getortho:GET_IMG: Empty chunk data.  Skip.
WARNING:getortho:GET_IMG: Empty chunk data.  Skip.
INFO:aostats:STATS: ID: {'count': 1393, 'chunk_miss': 1393, 'bytes_dl': 28182114, 'partial_mm_averages': {0: 0.001}, 'partial_mm_counts': {0: 65}, 'backup_chunk_count': 65, 'mm_counts': {0: -1, 1: -1, 2: -1, 3: -1, 4: 63}, 'mm_averages': {0: -1, 1: -1, 2: -1, 3: -1, 4: 0.001}, 'chunk_missing_count':



Then a second install to this location about an hour later at 2200 hours but paths don't match

INFO:downloader:Installed scenery location of '/home/piotr/.steam/steam/steamapps/common/X-Plane 11/Custom Scenery' and configured scenery dir of '/media/piotr/NVMe M.2/X-plane scenery/Custom Scenery' do not match!
INFO:downloader: ... Issues detected with scenery.  Recommend retrying

Then there is a python error and os error

ERROR:aoconfig:Traceback (most recent call last):
  File "/tmp/onefile_14175_1681854557_573867/aoconfig.py", line 261, in scenery_setup
  File "/tmp/onefile_14175_1681854557_573867/downloader.py", line 311, in extract
  File "/tmp/onefile_14175_1681854557_573867/zipfile.py", line 1645, in extractall
  File "/tmp/onefile_14175_1681854557_573867/zipfile.py", line 1695, in _extract_member
OSError: [Errno 22] Invalid argument: '/media/piotr/NVMe M.2/X-plane scenery/Custom Scenery/y_aus_pac/yOrtho4XP_Overlays/Earth nav data/*

**Comment by hawajka76** [comment]
Hi, thank you for looking into this. To be clear the program works, the issue which I have is that I can't move all of the data to the NTFS formatted drive and simlink to that location because of the folder named "*".  Is there a way to change the "*" name to something compatible with NTFS drives in future releases so that I could move the "Earth Nav Data" folder to the NTFS drive entirely?

**Comment by dpdurst** [comment]
Delete the folder with the * and carry on from there

**Comment by hawajka76** [comment]
Seems to have worked! Not sure why I convinced myself that that folder was required :). Thank you for the help. Will do some more extensive testing soon to make sure it is ok and will close this topic.
