### ISSUE TITLE
X-Plane 12 Water

### ISSUE THREAD

**Issue by wiggleforlife** [kubilus1/autoortho#116]
![image](https://user-images.githubusercontent.com/46230102/235278791-6fc1fead-e334-46ec-801b-462a3c016272.png)
Is it possible for water compatible with X-Plane 12 to be added? Currently it is replaced by 2D water that occurs when you use XP11 orthos. I know Ortho4XP doesn't have this yet, but I know there are payware products that do (see Hawai'i on the org store)

**Comment by kubilus1** [comment]
This uses Ortho4XP to generate tiles, so it supports whatever can be generated with that tool.

**Comment by wiggleforlife** [comment]
I'll close this then as we wait for Ortho4XP to support XP12 water. Thanks!
