### ISSUE TITLE
[FEATURE REQUEST] Don't use autoortho for certain user-defined areas 

### ISSUE THREAD

**Issue by wiggleforlife** [kubilus1/autoortho#121]
It would be nice if we could remove certain areas from the autoortho (AO from here on out) list. For example, I have Orbx True Earth for SoCal and I don't want the program using up CPU when I am flying in SoCal - as mentioned in another issue, AO uses enough of my CPU for long enough to tank my FPS from >30 to ~15, disconnecting me from VATSIM. I'd be fine with this just being a simple config file to get the feature in quicker, but later down the line a wizard would be nice, similar to Ortho4XP's tile selection window.

**Comment by kubilus1** [comment]
You can simply do this by putting your Orbx scenery higher up in the order of your scenery_packs.ini.

**Comment by wiggleforlife** [comment]
I did notice that the program wasn't taking up any resources when flying through SoCal on a test flight, as you described. However, I think the ignore list would still be very beneficial. If I'm in an area with normal ortho, there is no reason to have AO open. For example, a transpacific flight from SoCal that leaves the AO area behind while still in normal ortho territory. Unfortunately, I need to leave AO open as it still tries to load (at the very least) oceanic terrain - see this screenshot while loading at L52 (Big Bear) 
![image](https://user-images.githubusercontent.com/46230102/236657172-aac067bc-5139-49c3-afa9-2c663e784c7e.png)

**Comment by kubilus1** [comment]
I'm not sure how that would work, though, since XPlane itself determines what it loads in.

**Comment by wiggleforlife** [comment]
I'd say the simplest way is just having a map inside the program of what's already installed and being able to delete it. It's a bit of a hassle having to go into the Custom Scenery folder and delete the specific tiles by number alone. 
I don't think there's anything stopping you from having an implementation as simple as adding a static image as the world with clickzones representing each tile. There isn't really a need to go as far as Ortho4XP's moving map.
