### ISSUE TITLE
Same region fails to load consistently

### ISSUE THREAD

**Issue by ffortin** [kubilus1/autoortho#142]
![20230519095138_1](https://github.com/kubilus1/autoortho/assets/1824628/a01e262a-3211-43e1-a03c-40c1c590e4a8)
![20230519095955_1](https://github.com/kubilus1/autoortho/assets/1824628/78a71f32-ef49-4123-a97e-0013fa43f64a)
![image](https://github.com/kubilus1/autoortho/assets/1824628/d4ece94f-dfab-4862-89b4-a15820fe7f9b)

It seems that right around Montreal, there's an area that fails to pull scenery consistently. I've deleted the cache folder twice, and had the same thing happen. I also tried BI and Firefly on different occasions, to the same result.

This might also be happening elsewhere, but it seems to be pretty consistent around that specific spot.

I see the "timeout" messages in the console, although it's a little strange to me that it's always the exact specific spot that times out.

Exact position is an area that seems to be around 20nm squared, around the HABBS waypoint on the HABBS6 arrival into CYUL.
![image](https://github.com/kubilus1/autoortho/assets/1824628/bec7d293-eb78-4f84-8e88-99410443e28c)

**Comment by NNowakowski** [comment]
I just did a flight from CYOW to CYYG yesterday and encountered the exact same thing right around Montreal as you stated. I was also using the default BI provider.

**Comment by vagueov** [comment]
Same here!! its annoying haha hopefully there is a fix. 
![FJS_732_TwinJet - 2023-06-25 5 57 08 PM](https://github.com/kubilus1/autoortho/assets/103288471/8df81f2c-9bc6-47bf-9fe4-afb46193e185)
![FJS_732_TwinJet - 2023-06-25 17 23 34](https://github.com/kubilus1/autoortho/assets/103288471/1a4c8b94-06a6-41fc-947a-323f8af30974)
![FJS_732_TwinJet - 2023-06-25 20 49 29](https://github.com/kubilus1/autoortho/assets/103288471/003807f3-9366-4fbe-abc6-2a3485619aea)

**Comment by ffortin** [comment]
Updating to NA version 0.54 has resolved this issue for me (at least the part around Montreal).
