### ISSUE TITLE
NameError: name 'sys' is not defined

### ISSUE THREAD

**Issue by germannorwegian** [kubilus1/autoortho#146]
I have installed Python and Winfsp, as Dokan did not work for me. When attempting to start, WinFSP seems to work but when Python gets booted up i get this error;NameError: name 'sys' is not defined. I am running X-Plane 12.

![image](https://github.com/kubilus1/autoortho/assets/85123392/43702b83-8c56-44a0-9308-0112256391d8)

**Comment by germannorwegian** [comment]
I am aware that this error normally means that the sys module is loaded in the wrong order, or something akin to that. However since this is not a script I have created, that isn't really relevant since I cannot change the code, and I wonder how i can get the error to go away.

**Comment by germannorwegian** [comment]
Figured it out, had to switch out something in the configs. Sorry for cluttering up the forum!

**Comment by kubilus1** [comment]
No problem, what did you have to change?

**Comment by germannorwegian** [comment]
It was on the bottom, where you had to input "TRUE" for using WinFSP, although it said it was not recommended. In the meantime I have encountered more issues, and I turned it to FALSE again, aswell as uninstalling WinFSP because of CTDs

**Comment by germannorwegian** [comment]
I am having issues with Dokan, making it impossible to use me, however, if I use WinFSP the game crashes, so sort of stuck right now.

**Comment by germannorwegian** [comment]
The issue being, when I first installed AutoOrtho, I downloaded Dokan as normal, but then I uninstalled it wrong when I wanted to try WinFSE, for some reason. This resulted in some registry traces being left on my pc, so Dokan was not uninstalled completely afterall. When I tried to use the Dokan uninstaller, I got an error and I still do to this hour, so I cannot uninstall it that way. (I need to uninstall it to reinstall it again because AutoOrtho does not recognize that Dokan is installed on my pc because it is partially deleted, but I cannot delete the remaining files because of the error, paradox really.

I tried to delete the remaining registry traces, and then it actually worked, I was able to uninstall and reinstall Dokan completely using the installer, however AutoOrtho does not recognize that Dokan is installed on my pc, and therefore it does not start. It seems that even the installer has not installed Dokan properly either, and that is maybe why AutoOrtho does not recognize it as being installed. So I am very much stuck right now, been browsing the Dokan github but I have limited knowledge of anything related to coding so I am not able to do anything about the problem.

**Comment by germannorwegian** [comment]
So to sum it up, I cannot use AutoOrtho because it does not recognize Dokan as being installed, and Dokan does not seem to be properly installed either. I have tried to uninstall Dokan and reinstall, however when I do i get an error. When I  try to delete the registry stuff manually, the installer works without error again, however when I reinstall Dokan (the same version) it does not install properly for some reason and is not recognized by AutoOrtho as being installed. So I am unable to install Dokan, and if i use WinFSP the game crashes.

**Comment by germannorwegian** [comment]
And I cannot download older versions of Dokan either, like 2.0.5, that one does not install properly either and is not recognized by AutoOrtho, therefore meaning that the program does not run..

**Comment by NoamBar123** [comment]
Same problem to me

**Comment by NoamBar123** [comment]
Did you fix that?
