### ISSUE TITLE
Cannot See Full Setup Window

### ISSUE THREAD

**Issue by Godzilaer** [kubilus1/autoortho#153]
Whenever I open the setup window, I can never see the bottom of the window, where the start, run, and other buttons are. I cannot resize the window, and even if I move it to the top not everything is visible. If I try moving it off screen, it just teleports back to the middle of the screen.
![image](https://github.com/kubilus1/autoortho/assets/114835170/922e7e9c-7830-40e5-80f4-c528b19ec9f1)

**Comment by SGFlightSimmerYT** [comment]
same issue for me, i had to change my windows res to 125% to see the image cache directory and the scenery tab

**Comment by SGFlightSimmerYT** [comment]
![image](https://github.com/kubilus1/autoortho/assets/95022255/4c95898a-13c3-41ad-949d-463d45e7e023)

**Comment by Ulazygit** [comment]
+1. Please make window resizeable
