### ISSUE TITLE
Loading times

### ISSUE THREAD

**Issue by srykho22** [kubilus1/autoortho#161]
### Discussed in https://github.com/kubilus1/autoortho/discussions/160

<div type='discussions-op-text'>

<sup>Originally posted by **srykho22** May 23, 2023</sup>
I'm having issues with AO taking over an hour and a half to start up, with my flights also hanging for over thirty minutes at a time every time it gets new textures. I've gone as far down as minimum ZL 14 and things haven't really changed. Max wait time at 0.25 shows the majority of tiles as just pure green (didn't download), whereas a wait time of 1.50 doesn't load in, even overnight. 

I don't clear the cache, and I have experimented with having the cache on both an external SSD and external HDD. Speedtest says my internet is around 180Mbps download, with task manager saying my ethernet is using 17Mbps with Auto Ortho running. I've also seen the usage go up with other apps when I tested if my ISP was throttling, and I've also tried the new version and reverting to older versions, with barely any difference.

Auto Ortho gives a lot of "empty chunk data, skip" errors, but VPN doesn't really help there.</div>

**Comment by srykho22** [comment]
Using the default ZL of 12 does reduce the initial startup to 30 minutes, but the majority of the tiles are pixelated and I see multiple tiles being pure green (default). The sim also still hangs instead of stuttering when gathering new tiles. Tried this with both the default wait time of 0.5 and a wait time of 1.5

![Screenshot 2023-05-23 182015](https://github.com/kubilus1/autoortho/assets/31467287/bba26372-9401-433f-b4b3-edab99f67f93)
![Screenshot 2023-05-23 182340](https://github.com/kubilus1/autoortho/assets/31467287/75e71300-d6a0-4387-91a8-d2f015361f37)
![Screenshot 2023-05-23 183459](https://github.com/kubilus1/autoortho/assets/31467287/a0874e74-ee61-4579-bcbb-86ff545ee7ed)

**Comment by kubilus1** [comment]
Interesting.  Definitely something is throttling your connection.  Maybe it's a DNS issue?  Do you just use your ISPs default?  Maybe try a standard DNS server.

**Comment by srykho22** [comment]
I should be on Google's DNS servers; I'll try others

**Comment by rt23456p** [comment]
Is "Map type override" blank? Blank sometimes helps.

**Comment by srykho22** [comment]
Map override is currently blank, though I also tried it with ARC and BI. No difference

**Comment by pla031** [comment]
Hi.
I have the same issue. Textures don't load or load very late. Tested on BING and ARC with ZL12 and 1.5 time
https://cdn.discordapp.com/attachments/758215560105689099/1120003296321613844/X-Plane_Screenshot_2023.06.18_-_16.52.48.44.png
https://cdn.discordapp.com/attachments/758215560105689099/1119998299211059302/image.png
