### ISSUE TITLE
Some freeze issues with Python version - Can be solved if you use the EXE-Release

### ISSUE THREAD

**Issue by Cockpitlyrics** [kubilus1/autoortho#179]
I'm a bit surprised that there is hardly any talk about the recurring freezes here. I use AO with XP12 and a 250 MBit/s line and a Ryzen 7 5800X3D. After about 10 minutes, X-Plane freezes for a few minutes. I have actually tried everything: Changed CPU allocation via ProcessLasso, changed image provider, excluded cache and AutoOrtho folder from Windows Defender, reduced texture quality in XP, it all did nothing. XP continues to stop for a few minutes. The problem exists for some users, but for the majority it seems to work without problems. I am at a loss as to what to do. And that's especially a shame since AO is a real must have. I don't even want to fly without it anymore.

**Comment by evilstiefel** [comment]
Weirdly enough, I have the same problem when using the python version. X-Plane will hang after a while and only continue working after 20-30 seconds.

Running autoortho through the `.exe` of 0.4.3, I don't experience such issues. The only difference I could tell so far is maybe the Python version I use vs. what's used inside of the bundled .exe and the lack of Websockets support in the .exe (which appears to be a new feature for the flight tracker and I don't suspect should be related)

**Comment by Cockpitlyrics** [comment]
A small addition: Freezes only occur with the ZIP release, i.e. the Python version. I recently did a two-hour flight and XP12 ran smoothly without freezes or long interruptions. By the way, the Python version I used was 0.4.3.

So: Anyone who is affected by freezes during XP12 flights should try the EXE from Autoortho.
