### ISSUE TITLE
Question: My cache folder is getting very large is there anyway to delete it? 

### ISSUE THREAD

**Issue by vagueov** [kubilus1/autoortho#181]
If there is how do i delete it without messing it all up. Ive tried deleting the cache but i get an error i love it besides that it takes up a lot of storage.
![X-Plane 2023-05-31 01-15-55](https://github.com/kubilus1/autoortho/assets/103288471/69225034-39c1-416e-b84a-835fb667670e)

**Comment by vagueov** [comment]
I believe i found how to do it i just completely delete the cache folder then remake it clean the chnage the directory to there

**Comment by nic0l45** [comment]
I have the same error, where's the cache folder?
