### ISSUE TITLE
`--headless` does not unmount and stop on SIGTERM (any more)

### ISSUE THREAD

**Issue by jonaseberle** [kubilus1/autoortho#185]
While it catches SIGINT (CTRL+C), it does not react to SIGTERM.

I start the sim and start/stop autoortho in a script and it stopped catching SIGTERM with https://github.com/kubilus1/autoortho/commit/35f8c2c5d7badff852873d28720597f2841860a1 (introduction of `KeyboardInterrupt`). I have to SIGKILL and unmount manually.

I'll provide a pull request.

**Comment by kubilus1** [comment]
Yeah I was afraid of this.  Likely a 'finally' block is in order.
