### ISSUE TITLE
Run on another device on the same network

### ISSUE THREAD

**Issue by baragoon** [kubilus1/autoortho#190]
Hi,
At first, thank you a lot for the such great X-plane add-on!

Just wondering, is it possible to run a binary on the linux host (like NAS, Pi, etc) and use the orthos on the Windows machine?
It can reduce CPU load for people like me, with a not so powerful CPU.
If you are connected via 1G Ethernet, theoretically it can be a solution.

Any thoughts?

Thank you.

**Comment by jonaseberle** [comment]
Yes, possible. You can try it. But keep in mind that it is literally 10.000s of small files.
