### ISSUE TITLE
[FEATURE REQUEST] Multiple Scenery Dirs for XP11 and XP12 

### ISSUE THREAD

**Issue by jamieernest** [kubilus1/autoortho#193]
Have 2 boxes for 2 paths for the scenery dir so I can use the same app for both XP11 and XP12 :)

**Comment by wiggleforlife** [comment]
What I do to have scenery shared between the two is a folder on my drive where I put all my scenery, then add it to each scenery_pack.ini. Ex `SCENERY_PACK G:\Custom Scenery\KBZN Bozeman Yellowstone Intl/`

**Comment by jamieernest** [comment]
@wiggleforlife I mean if the app could automatically do it for me it would be great
