### ISSUE TITLE
Cant1see some buttons

### ISSUE THREAD

**Issue by Henqw** [kubilus1/autoortho#196]
I can't see the buttons RUN QUIT and SAVE for any reason, i dont know what to do, all the think work but i dont find these buttons

**Comment by GOZARCK** [comment]
you can run on bat file cmd "autoortho_win.exe -H".

**Comment by Henqw** [comment]
i cant write on the bat file

**Comment by chezhj** [comment]
in windows: open shell 
windows-r, type CMD press enter
Now navigate to directory where autoartho_win.exe is by using cd
then type "autoortho_win.exe -H"
Hope this helps
