### ISSUE TITLE
ERROR File is not a zip file with Zipfile

### ISSUE THREAD

**Issue by av1art** [kubilus1/autoortho#197]
![Screenshot_1](https://github.com/kubilus1/autoortho/assets/53268523/03bc731e-8d25-47b4-b00b-a2fbbd9b5d05)
****************************************************************************************************
Config file found C:\Users\Ilya\.autoortho reading...
Saving config ...
Wrote config file: C:\Users\Ilya\.autoortho
INFO:downloader:Looking for regions ...
INFO:downloader:Last release refresh time: 2023-06-05 14:09:00.767733
INFO:downloader:Using cache ...
INFO:downloader:Using scenery dir C:/Program Files (x86)/Steam/steamapps/common/X-Plane 12/Custom Scenery
INFO:downloader:Found region eur version 0.0.51
INFO:downloader: ... eur update is available
INFO:downloader:Found region na version 0.0.49
INFO:downloader: ... na up to date and validated.
INFO:downloader:Found region sa version 0.0.46-1
INFO:downloader: ... sa up to date and validated.
INFO:downloader:Found region afr version 0.0.45-1
INFO:downloader: ... afr up to date and validated.
INFO:downloader:Found region asi version 0.0.44-1
INFO:downloader: ... asi up to date and validated.
INFO:downloader:Found region aus_pac version 0.0.42-1
INFO:downloader: ... aus_pac up to date and validated.
Saving config ...
INFO:aoconfig:Wrote config file: C:\Users\Ilya\.autoortho
Wrote config file: C:\Users\Ilya\.autoortho
Config file found C:\Users\Ilya\.autoortho reading...
INFO:aoconfig:Config file found C:\Users\Ilya\.autoortho reading...
INFO:downloader:Download eur
INFO:downloader:Will download https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.51/z_eur_00.zip
100.00%   10.82 MBpsINFO:downloader:  DONE!
INFO:downloader:Will download https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.51/z_eur_01.zip
100.00%   10.15 MBpsINFO:downloader:  DONE!
INFO:downloader:Will download https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.51/z_eur_02.zip
100.00%   10.25 MBpsINFO:downloader:  DONE!
INFO:downloader:We already have https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.51/z_eur_03.zip
INFO:downloader:We already have https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.51/z_eur_04.zip
INFO:downloader:We already have https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.51/z_eur_05.zip
INFO:downloader:We already have https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.51/z_eur_06.zip
INFO:downloader:We already have https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.51/z_eur_07.zip
INFO:downloader:We already have https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.51/z_eur_08.zip
INFO:downloader:We already have https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.51/z_eur_09.zip
INFO:downloader:We already have https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.51/z_eur_10.zip
INFO:downloader:We already have https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.51/z_eur_11.zip
INFO:downloader:We already have https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.51/z_eur_12.zip
INFO:downloader:We already have https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.51/z_eur_13.zip
INFO:downloader:We already have https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.51/z_eur_14.zip
INFO:downloader:We already have https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.51/z_eur_15.zip
INFO:downloader:ORTHOS DOWNLOADED
INFO:downloader:Will download https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.51/y_eur_overlays.zip.00
100.00%   10.93 MBpsINFO:downloader:  DONE!
INFO:downloader:Will download https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.51/y_eur_overlays.zip.01
100.00%   10.82 MBpsINFO:downloader:  DONE!
INFO:downloader:Will download https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.51/y_eur_overlays.zip.02
100.00%   10.47 MBpsINFO:downloader:  DONE!
INFO:downloader:OVERLAYS DOWNLOADED
Setting extract dir to C:/Program Files (x86)/Steam/steamapps/common/X-Plane 12/Custom Scenery
INFO:downloader: ... eur update is available
INFO:downloader:Detected existing scenery dirs for eur.  Cleanup first
INFO:downloader:Ready to extract archives for eur v0.0.51!
INFO:downloader:Split zip detected for ('C:\\Users\\Ilya\\.autoortho-data\\downloads\\y_eur_overlays.zip',)
INFO:downloader:ZIPNAME C:\Users\Ilya\.autoortho-data\downloads\y_eur_overlays.zip
INFO:downloader:Split zip detected for ('C:\\Users\\Ilya\\.autoortho-data\\downloads\\y_eur_overlays.zip',)
INFO:downloader:ZIPNAME C:\Users\Ilya\.autoortho-data\downloads\y_eur_overlays.zip
INFO:downloader:Split zip detected for ('C:\\Users\\Ilya\\.autoortho-data\\downloads\\y_eur_overlays.zip',)
INFO:downloader:ZIPNAME C:\Users\Ilya\.autoortho-data\downloads\y_eur_overlays.zip
INFO:downloader:Cleaning up parts for C:\Users\Ilya\.autoortho-data\downloads\y_eur_overlays.zip
INFO:downloader:Cleaning up parts for C:\Users\Ilya\.autoortho-data\downloads\z_eur_00.zip
INFO:downloader:Cleaning up parts for C:\Users\Ilya\.autoortho-data\downloads\z_eur_01.zip
INFO:downloader:Cleaning up parts for C:\Users\Ilya\.autoortho-data\downloads\z_eur_02.zip
INFO:downloader:ERROR: File is not a zip file with Zipfile C:\Users\Ilya\.autoortho-data\downloads\z_eur_03.zip.  Recommend retrying
INFO:downloader:Cleaning up parts for C:\Users\Ilya\.autoortho-data\downloads\z_eur_03.zip
Errors detected!
****************************************************************************************************
Please, fix the issue.

**Comment by silvanuskrisna** [comment]
i got the same problem, retryin so many times, still get this error on SA
any help how to fix this?

**Comment by TombBoy** [comment]
Same issue here with the latest scenery updates

**Comment by dpdurst** [comment]
Go here - https://github.com/kubilus1/autoortho-scenery/releases
There is a new release .52 for the EUR scenery or you can try and re-download the .51 part that says its bad, click on the assets area under the version. Make sure you are running the 4.4 AO program

**Comment by TombBoy** [comment]
Solved this by installing the latest version of the exe from github and clearing up the previously downloaded zip files in the download directory. Now it’s working fine

**Comment by kubilus1** [comment]
Great!  Thanks for the update!

**Comment by silvanuskrisna** [comment]
finally it works... thankssss
