### ISSUE TITLE
PLEASE make already a good version

### ISSUE THREAD

**Issue by BlueSkyStarCompany** [kubilus1/autoortho#203]
INFO:getortho:GET_IMG: Tile Tile(71760, 113808, BI, 18, 12, E:/X-Plane 12/AutoOrtho/Cache) Try to find backup chunk.
WARNING:getortho:GET_IMG: Empty chunk data.  Skip
None of this works, yesterday flew all fine, everything loaded perfectly, today in the middle of flight it hanged and crashed. After that I couldn't get it to work no matter what I tried, reinstalled, tried options, everything. It seems like it is not letting me through at all

**Comment by kubilus1** [comment]
lol

**Comment by pntrafewl** [comment]
Wow, some people...
