### ISSUE TITLE
Random terrain in the Pacific, but on the NA pack

### ISSUE THREAD

**Issue by wiggleforlife** [kubilus1/autoortho#209]
Hi, me again.

I was flying from PHNL-PKMJ and crashed around a quarter of the way through. Unfortunately, I've deleted the Volanta log of the flight I had (d'oh!). The log says it loaded the overlays for +16-170, then tried to find images for the terrain and failed. I've since deleted +10-170 in the na_02 folder, but why was this outlier included in the first place? Should this not be part of the Australia Pacific pack instead of North America?

**Comment by kubilus1** [comment]
The scenery tiles are based off of XPlane's global scenery.  Same exact
sets.  I did notice that there are some odd choices for what they consider
part of different areas.

**Comment by wiggleforlife** [comment]
Fair enough. Is it possible these areas could be included in the README or docs for quick reference?
