### ISSUE TITLE
CTD when trying to open .exe (Error 10054)

### ISSUE THREAD

**Issue by Vinirc777** [kubilus1/autoortho#221]
![Captura de tela 2023-06-18 213400](https://github.com/kubilus1/autoortho/assets/137015551/5bcb9d8f-2eb6-40f6-8afa-825d4fd5ce1e)
Getting this error everytime I try to open autoortho_win. Any one know how to solve this?

**Comment by hazzar123** [comment]
have the same issue - a reinstall doesn’t fix it
