### ISSUE TITLE
It´s not a issue is a open door

### ISSUE THREAD

**Issue by m0nstergr33n** [kubilus1/autoortho#233]
This is not a mistake is twisting the wonderful work trying to open a door for those of us who have limited space and the two versions of x-plane. 
The issue is that with v0.43 I performed the installation in a separate folder (F:/photoreals) and called the folders generated by symbolic links to custom scenery, so with a single download and program made use of it in both simulators. 
Now with v0.502, the data download is the same (1 not custom scenery, F:/photoreals) and I generate the symbolic links to both simulators (the same as v0.43), but the program generates its fuses at startup and therefore I have to redirect the program to the custom scenery of the simulator I am running. In theory it should work, but I get error, although autoortho does see the data sources with the symbolic link then it does not generate in the fuses the calls. If it would be solved, it would be interesting to add to the program a location for the installation of the data and the entry to the simulator that at that moment is running. I hope to open with this a door to ideas to enjoy this project with the minimum cost of space and in both simulators. Thanks for the effort and for the software. Something that should be gratified by Laminar because it has put xpl in force together with simheaven in front of msfs.

**Comment by kubilus1** [comment]
You should be able to have a scenery in a single location but make it available in both simulators.  Instead of a symbolic link, have you tried just using a shortcut?  I was able to get shortcuts to work just fine.

**Comment by m0nstergr33n** [comment]
Thanks for your answer, no, I have not tested with shortcuts. I'll try it and let you know.

**Comment by m0nstergr33n** [comment]
I have the same problem as with the symbolic links, it generates the folders but does not generate the files, the folders are empty, it is as if dokan does not inject them.
Folder  z_ao_aus_pac - Shortcut has files only in subfolder Earth nav data, but terrain and textures are empty.

**Comment by kubilus1** [comment]
>  Folder z_ao_aus_pac - Shortcut has files only in subfolder Earth nav data, but terrain and textures are empty.

Yes, that is how it looks when it is working

**Comment by m0nstergr33n** [comment]
Yes, the issue was that the contents of the terrain and textures folders were not generated when the program was executed. Finally I found the problem, it was dokan, I uninstalled it and installed it again and everything is working with symbolic links and shortcuts. Thanks for your answers.

**Comment by kubilus1** [comment]
Interesting.  Did you update the dokan version when you reinstalled?

**Comment by m0nstergr33n** [comment]
Yes I had the last version, but I had in other time the same problem and I solved it reinstalling it

**Comment by m0nstergr33n** [comment]
Sorry to bother again. As I told you everything ok in xpl11 but xpl12 does not inject the files in the folders and xpl reports me scenery error. Any idea?
