### ISSUE TITLE
Water covering a land area west and north of Montreal

### ISSUE THREAD

**Issue by FlynAlex** [kubilus1/autoortho#236]
**Describe the bug**
An oblong area of water at a level approximately 100' above sea level, from roughly W75, N46; to W74, N45. The edges are straight and when surrounding land is at a higher elevation there is a vertical wall from the water to the land elevation.  In this water area there are some objects that are above the water. I am not very computer savvy, this is a new install, It works and looks great except for this large area. I am running X-Plane 12.51 in Windows 10, 3070Ti 8gb, 32gb ram, intel 12700. getting 40 fps on  2560X1440 4k tv.
**To Reproduce**
1. goto autoortho_win.exe
2. Click on 'run'
3. Start X-Plane at CYUL and fly west
4. Land appears again west of CYCC Corwall ON

**Expected behavior**
To see the same quality as the rest of my flights from Brockville to Brantford and Calgary to Banff

**
![RV-7 - 2023-06-30 13 22 55](https://github.com/kubilus1/autoortho/assets/138323596/0b662874-90f0-4413-a165-bfe89715ae13)
![RV-7 - 2023-06-30 14 10 07](https://github.com/kubilus1/autoortho/assets/138323596/40751394-dc3d-442c-8d20-fdd1e32e4e47)
![Water World](https://github.com/kubilus1/autoortho/assets/138323596/867aa7bc-ab3b-45b2-8509-ff0de59b05a1)
**

**(please complete the following information):**
 - OS: [e.g. Windows 10]
 - XPlane 12.0.5.4
 - AutoOrtho Version North America 0.0.49; Europe 0.0.51
 - Filesystem type (NTFS)

**Additional context**

**Comment by dpdurst** [comment]
Yep there's a whole bunch of water where the land should be!

**Comment by d41k4n** [comment]
Most likely this is an issue with OSM coastlines in Ortho4XP which happens during preparation of the mesh that is distributed as part of the Autoortho installation. In that case it would require debugging in Ortho4XP and JOSM. If you can reproduce this using a tile created with Ortho4XP I suggest to post a topic in the [Ortho4XP forum](https://forums.x-plane.org/index.php?/forums/forum/322-ortho4xp/) mentioning the affected tile coordinates.

**Comment by d41k4n** [comment]
I found and fixed the root cause, which I could confirm to be Ortho4XP/OSM. However, this will require an update of the DSF file for tile +45-075 as distributed by AutoOrtho to have an effect.

More details see [here](https://forums.x-plane.org/index.php?/forums/topic/290663-auto-ortho-has-a-tile-that-is-water-world-west-of-cyul-montreal/&do=findComment&comment=2574515).

**Comment by kubilus1** [comment]
Excellent, thanks for that.  I'll start the scenery rebuild process shortly.

Do you suppose that there is a similar OSM issue going on here: https://github.com/kubilus1/autoortho/issues/239 ?

**Comment by d41k4n** [comment]
> Do you suppose that there is a similar OSM issue going on here: #239 ?

Indeed - I just fixed it in OSM as well.

**Comment by kubilus1** [comment]
Nice, thanks!

**Comment by kubilus1** [comment]
Latest release of scenery should resolve this.

**Comment by FlynAlex** [comment]
Hi Kubilus1,
I love what you have created, it is fantastic when it works :). At 75 and not being computer savvy I don't know what or how to get you the info for this new bug. I saw you and d31k4n fixed the issue I posted so I tried to reload the na data and I get this error message at the end of the down load when it tries to unzip:
INFO:downloader:ERROR: File is not a zip file with Zipfile C:\Users\2mtsg\.autoortho-data\downloads\z_na_00.zip.  Recommend retrying
INFO:downloader:Cleaning up parts for C:\Users\2mtsg\.autoortho-data\downloads\z_na_00.zip
Errors detected!
Saving config ...
INFO:aoconfig:Wrote config file: C:\Users\2mtsg\.autoortho
Wrote config file: C:\Users\2mtsg\.autoortho
Config file found C:\Users\2mtsg\.autoortho reading...
INFO:aoconfig:Config file found C:\Users\2mtsg\.autoortho reading...

**Comment by kubilus1** [comment]
> Hi Kubilus1, I love what you have created, it is fantastic when it works :). At 75 and not being computer savvy I don't know what or how to get you the info for this new bug. I saw you and d31k4n fixed the issue I posted so I tried to reload the na data and I get this error message at the end of the down load when it tries to unzip: INFO:downloader:ERROR: File is not a zip file with Zipfile C:\Users\2mtsg.autoortho-data\downloads\z_na_00.zip. Recommend retrying INFO:downloader:Cleaning up parts for C:\Users\2mtsg.autoortho-data\downloads\z_na_00.zip Errors detected! Saving config ... INFO:aoconfig:Wrote config file: C:\Users\2mtsg.autoortho Wrote config file: C:\Users\2mtsg.autoortho Config file found C:\Users\2mtsg.autoortho reading... INFO:aoconfig:Config file found C:\Users\2mtsg.autoortho reading...

Are you using the latest release, that is required for updating the packages?

**Comment by FlynAlex** [comment]
how do I know if it is the latest does it auto update?

**Comment by kubilus1** [comment]
> how do I know if it is the latest does it auto update?

Nothing fancy like auto update for this, but the latest release will be at this link: https://github.com/kubilus1/autoortho/releases/latest

**Comment by FlynAlex** [comment]
I deleted everything downloaded a new auto ortho zip installed europe and it works now trying to install na that you said should have the water tile fixed but this is what I am dealing with. I have retried this 7 times and each time it takes me one step further. So when I retry 7, I expect I'll have to retry 8, and there are 35 files in total ( talk to you next year lol) and it has yet to unpack the zips. I wish I understood what is going on and why it is not installing like Europe did. 
INFO:downloader:We already have https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.54/z_na_34.zip.sha256
INFO:downloader:We already have https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.54/z_na_35.zip
INFO:downloader:We already have https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.54/z_na_35.zip.sha256
INFO:downloader:ORTHOS DOWNLOADED
INFO:downloader:Will download https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.54/y_na_overlays.zip.00
100.00%   65.40 MBpsINFO:downloader:  DONE!
INFO:downloader:Will download https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.54/y_na_overlays.zip.01
100.00%   87.13 MBpsINFO:downloader:  DONE!
INFO:downloader:Will download https://github.com/kubilus1/autoortho-scenery/releases/download/0.0.54/y_na_overlays.zip.02
100.00%   62.37 MBpsINFO:downloader:  DONE!
INFO:downloader:OVERLAYS DOWNLOADED
Setting extract dir to C:/X-Plane 12 with working pop outs/Custom Scenery
INFO:downloader: ... na not setup yet
INFO:downloader:Ready to extract archives for na v0.0.54!
INFO:downloader:Split zip detected for ('C:\\Users\\2mtsg\\.autoortho-data\\downloads\\y_na_overlays.zip',)
INFO:downloader:ZIPNAME C:\Users\2mtsg\.autoortho-data\downloads\y_na_overlays.zip
INFO:downloader:Split zip detected for ('C:\\Users\\2mtsg\\.autoortho-data\\downloads\\y_na_overlays.zip',)
INFO:downloader:ZIPNAME C:\Users\2mtsg\.autoortho-data\downloads\y_na_overlays.zip
INFO:downloader:Split zip detected for ('C:\\Users\\2mtsg\\.autoortho-data\\downloads\\y_na_overlays.zip',)
INFO:downloader:ZIPNAME C:\Users\2mtsg\.autoortho-data\downloads\y_na_overlays.zip
INFO:downloader:Cleaning up parts for C:\Users\2mtsg\.autoortho-data\downloads\y_na_overlays.zip
INFO:downloader:Dir already exists.  Clean first
INFO:downloader:Cleaning up parts for C:\Users\2mtsg\.autoortho-data\downloads\z_na_00.zip
INFO:downloader:Dir already exists.  Clean first
INFO:downloader:Cleaning up parts for C:\Users\2mtsg\.autoortho-data\downloads\z_na_01.zip
INFO:downloader:Dir already exists.  Clean first
INFO:downloader:Cleaning up parts for C:\Users\2mtsg\.autoortho-data\downloads\z_na_02.zip
INFO:downloader:Dir already exists.  Clean first
INFO:downloader:Cleaning up parts for C:\Users\2mtsg\.autoortho-data\downloads\z_na_03.zip
INFO:downloader:Dir already exists.  Clean first
INFO:downloader:Cleaning up parts for C:\Users\2mtsg\.autoortho-data\downloads\z_na_04.zip
INFO:downloader:Dir already exists.  Clean first
INFO:downloader:Cleaning up parts for C:\Users\2mtsg\.autoortho-data\downloads\z_na_05.zip
INFO:downloader:Dir already exists.  Clean first
INFO:downloader:Cleaning up parts for C:\Users\2mtsg\.autoortho-data\downloads\z_na_06.zip
INFO:downloader:Cleaning up parts for C:\Users\2mtsg\.autoortho-data\downloads\z_na_07.zip
INFO:downloader:ERROR: File is not a zip file with Zipfile C:\Users\2mtsg\.autoortho-data\downloads\z_na_08.zip.  Recommend retrying
INFO:downloader:Cleaning up parts for C:\Users\2mtsg\.autoortho-data\downloads\z_na_08.zip
Errors detected!

**Comment by kubilus1** [comment]
Try deleting the files under your download dir manually.
