### ISSUE TITLE
AutoOrtho v5 detected as a virus

### ISSUE THREAD

**Issue by Orbitally** [kubilus1/autoortho#237]
Just downloaded v5 of AutoOrtho to test it out and Windows deleted the file as a virus and deleted it as soon as it finished downloading. I know Windows can be a bit of a pain with false positives so I ran the file through VirusTotal where it was [detected as a virus by 23 different checks](https://www.virustotal.com/gui/file/eafe765a71cf01af8bbfa3826a6de616266b4b955543a96e2b3e52758a43aa91). I don't think AutoOrtho's a virus or anything like that but just thought I'd mention it since [v4.3 came back from VirusTotal with 0 detections](https://www.virustotal.com/gui/file/171be58f465863e1596c6b0a94c6070fcccba1b95c4f3489029b6b22709e99ab)

**Comment by AntonKuf** [comment]
the same with me

**Comment by kit-v-kapushone** [comment]
affirm

**Comment by kubilus1** [comment]
https://kubilus1.github.io/autoortho/faq/

**Comment by Orbitally** [comment]
I saw that section in the docs but I was just pointing this out since VirusTotal was getting hits on the app. I know Windows tends to be a bit wonky with detection but VirusTotal generally does a much better job. As I mentioned it also only showed up with the prerelease version whereas the last full release came back clean so I’d imagine that helps to narrow down a change that’s causing this.
