### ISSUE TITLE
Auto ortho keeps crashing xp12

### ISSUE THREAD

**Issue by c777alpha** [kubilus1/autoortho#243]
I updated to 0.4.4 but xp12 still crashing....I attached a copy of auto ortho repeating pattern
![autoortho](https://github.com/kubilus1/autoortho/assets/138440465/9ae19e53-e225-48db-89a4-c813af42cc10)

**Comment by dpdurst** [comment]
The AO log is fine its streaming data. You will need to provide the Xplane log.txt file after a crash

**Comment by koch44** [comment]
Hi, for me it was the plane which caused the error in the end. I also had this situation but it turned out that it happend only when using the JAR A330. The ToLiss A321 for example in exact the same scenario worked just fine. So this seems not to be caused by AO.....

**Comment by c777alpha** [comment]
What version of  AO is current for XP12  .0.4.4  or .05.2
Thanks




It's more profitable to listen than talk!
Never squander the treasures of your words! 

    On Saturday, July 8, 2023 at 12:48:15 AM MST, koch44 ***@***.***> wrote:  
 
 


Hi, for me it was the plane which caused the error in the end. I also had this situation but it turned out that it happend only when using the JAR A330. The ToLiss A321 for example in exact the same scenario worked just fine. So this seems not to be caused by AO.....
