### ISSUE TITLE
SL: CERTIFICATE_VERIFY_FAILED (Fedora Linux)

### ISSUE THREAD

**Issue by simakovpa** [kubilus1/autoortho#246]
**Describe the bug**
I'm downloaded autoortho_lin.bin file, installed python requirements.txt (I have Python 3.11), bun after run application's log shows me the error:
"WARNING:downloader:Couldn't update release info <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>."

**To Reproduce**
0. I have a Steam version of X-Plane 11 with installed Europe ans Asia default regions.
1. Create a folder AutOrtho in a root folder of XP11 application ("~/.steam/steam/steamapps/common/X-Plane 11/AutoOrtho")
2. Copy file "autoortho_lin.bin" into the dir, made chroot +x to the file.
3. In terminal I cd to the directory and run the .bin file. Application launcher is starting.
4. Set a scenery folder "Custom Scenery" (full path), set a cache folder "AutoOrtho/Cache" (full path too)
5. Click a "Scenery" tab and see an empty window (no one csenery for download) and three dots in down field ("...")
6. Okay. Just maybe I must to starn the app for creating files etc.
7. See error.

**Screenshots**
![image](https://github.com/kubilus1/autoortho/assets/18704269/f5a688f0-7c0f-4925-898a-f6c34bac7f57)

![image](https://github.com/kubilus1/autoortho/assets/18704269/61e5b848-a644-4c02-a4a8-4160cfbad574)

![image](https://github.com/kubilus1/autoortho/assets/18704269/7f325e53-a3f3-4f91-885b-03f0ed760496)

**(please complete the following information):**
 - OS: Fedora Linux 38 (Workstation Edition) x86_64 
 - Kernel: 6.3.8-200.fc38.x86_64 
 - Gnome 44.2
 - NVidia
 - X11
 - Linux 6.3.8-200.fc38.x86_64
 - XPlane Version: XP11.55 (x64, Vulcan)
 - AutoOrtho Version 0.4.4
 - Filesystem type Ext4

**Additional context**
Nothing special

**Comment by simakovpa** [comment]
Yes! Thank you. It's working. 

![image](https://github.com/kubilus1/autoortho/assets/18704269/ecaea87d-3d14-4e6c-9325-ddd9784097df)

**Comment by simakovpa** [comment]
I've reinstall Linux and have the same problem again, but your command it's not working now (ROSA Linux). 
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>
Here's Python 3.8, I've installed python certifi, create openssl certificate, but it's not working from user privileges (the same error, and Application isn't starting), but from root it starts and have the error and empty Scenery tab again. 

Log after start from user:
[autoortho.log](https://github.com/kubilus1/autoortho/files/11995767/autoortho.log)

**Comment by JT8D-17** [comment]
This issue is also present on Arch Linux.

Would be nice if Autoortho could check "/etc/ssl/certs" by default.

**Comment by fshubthunfischbaum** [comment]
please include this in your officeial documentation :)
