### ISSUE TITLE
Iceland is flat

### ISSUE THREAD

**Issue by nnabber** [kubilus1/autoortho#247]
1. When loading ICELAND terrain/airports with AutoOrtho, everything is 100% flat. It is downloading the Jpegs but no height information.
2. When I put Ortho4XP generated tiles in the z_autoortho/scenery directory(without textures), nothing is getting mounted by AutoOrtho.
3. When I just use the Ortho4XP tiles it works fine like expected, showing mountains and vulcanos.

**Comment by jonaseberle** [comment]
It is being worked on: https://github.com/kubilus1/autoortho-scenery/issues/11

A general hint:
You are posting 2 issues as one which is hard to deal with. 
Essential information like version of program and scenery is missing.

**Comment by dpdurst** [comment]
"When I put Ortho4XP generated tiles in the z_autoortho/scenery directory(without textures), nothing is getting mounted by AutoOrtho"

Ortho4XP does not get loaded in anything for AutoOrtho. These are two separate programs. You would need to install Ortho4Xp the normal way you do and then adjust the scenery.ini to disable the yautoortho_overlays I believe to have them work together

**Comment by nnabber** [comment]
> r

But I want to insert it whithout the textures as a "self created scenery" in the custom scenenry/z_autoortho/scenery  directory, as advised in the manual

" You can take advantage of this setup for your own scenery that you have packaged: * Place your scenery directory in Custom Scenery/z_autoortho/scenery"

**Comment by jonaseberle** [comment]
That works for me, but PLEASE open a new issue for that completely different topic.

Your problem is important information for others and might help someone in the future, but you are burrying it under a completely different name.
