### ISSUE TITLE
Unable to change directory

### ISSUE THREAD

**Issue by gokings1** [kubilus1/autoortho#249]
hello enthusiasts, I am trying to install auto orhto. I want the downloads, the cache and the log file to go to a specific drive that is not the default C drive. I change it using notepad++ and save but it keeps telling me that change is not supported. When I try to download the scenery, I still downloads to the C drive and runs out of space, thus cancelling the download. Anybody know how to change the directory? I have updated notepad and python but didn't help

**Comment by dpdurst** [comment]
The only thing you can change, 5.0 and higher software (sounds like your on 4.3 or 4.4 software)  is the Cache Folder, Temp Download folder and the XP Custom Scenery folder. That's it.

**Comment by gokings1** [comment]
I heard a rumor of that. No, my screen only has the scenery and cache option. How do I get the new  version? I have looked but only get 1 option.
![Screenshot 2023-07-07 082753](https://github.com/kubilus1/autoortho/assets/138895333/6a98cea2-d894-4cac-ae8a-20b6f35d65fb)
![Screenshot 2023-07-07 080656](https://github.com/kubilus1/autoortho/assets/138895333/424583ff-1509-403e-8b51-b65efee14ca6)

**Comment by dpdurst** [comment]
Second section where it says 5.0, click on Assets and download the autoortho_win.exe, put in a directory anywhere you want and double click to run it, setup and you should be good to configure the new locations

https://github.com/kubilus1/autoortho/releases

**Comment by gokings1** [comment]
Thank you, worked great
