### ISSUE TITLE
The app does not open

### ISSUE THREAD

**Issue by tomer1290** [kubilus1/autoortho#250]
When I try to open the .exe file it only opens the Windows command and not the application that I can install the autoortho, I tried to reinstall but it didn't help.

**Comment by SierraRomeoTW** [comment]
Hi, I seem to have the same problem.

I've been using autoortho with XP11 and just purchased XP12 last week. I have previously checked the option to not to show the configuration window (where you set the paths and download the tiles etc.) and now I can't find a way to reopen that window to configure for XP12.
