### ISSUE TITLE
Atrocious performance

### ISSUE THREAD

**Issue by airbusseventhreeseven** [kubilus1/autoortho#253]
Hello, I am aware that stuttering in XP12 is a problem and that Austin has work to do on that front. However, ever since I installed autoortho, the problem has multiplied itself SIGNIFICANTLY. I have had horrible stutters on EVERY flight as often as every two minutes, and ones that can last as much as 10 minutes, even in performance friendly airplanes like the Toliss A321. These stutters can bring the sim to a whopping 0.1 fps, which is not something I can say about regular ortho. This is purely unacceptable. What can be done about this? I do not want to have to run the sim on bare minimum settings just so it won't nearly crash. Thank you. 
[Log.txt](https://github.com/kubilus1/autoortho/files/11994173/Log.txt)

**Comment by dpdurst** [comment]
I think your expectations are a little lofty here. You already said xplane has a stuttering problem and I'm going to disagree with you. You've got your xplane loaded down already pretty good with plugins and scenery im quite sure you already have slowdowns and stuttering to some extent at times.

AO is only as good as your internet connection and everything between you and the server connection. Flying jets you most likely will be able to go faster than AO can keep up with. 

If your configuration right now without AO as you say has no issues, then AO may not be a good choice and sticking with local orthographics may be your solution.
