### ISSUE TITLE
Autoortho.exe instant crashes on launch.

### ISSUE THREAD

**Issue by LightsYRL** [kubilus1/autoortho#254]
AutoOrtho.exe instantly crashes on launch; it shows an empty CMD window for a brief second and then immediately closes.

**To Reproduce**
It started happening out of nowhere 5 or 6 days ago. I did not install new plugins or applications, nor did i update Windows in any way during this time.

**Expected behavior**
A CMD Window appears for half a second and then immediately closes when trying to start AutoOrtho.exe. I also do not get any kind of written or audio error message on my PC when this occurs.

**Screenshots**
I can't provide a screenshot since the event is extremely brief, and I think it is pointless due to the nature of the problem.

**System Specs**
- OS: Windows 10
- XPlane Version: XP 12.05 
- AutoOrtho Version 0.4.3 
- Filesystem type: NTFS

**Additional context**
It really started happening out of nowhere (at least on my end) 5 days ago; I did not update Windows, XPlane, or Autoortho at that time.

**Comment by dpdurst** [comment]
Do you have the AutoOrtho log in C:\Users\Your Name\.autoortho-data? Lets see if that shows anything

**Comment by LightsYRL** [comment]
Very Sorry, I needed space on my drive and deleted the autoortho-data folder. The timing could not be any worse.

**Comment by LightsYRL** [comment]
Update: I did a complete reinstall of my PC and Windows (Formatted my C: drive), and it's working like usual. Unfortunately, I did not find the culprit.
