### ISSUE TITLE
Autoortho keep freezing while entering new area

### ISSUE THREAD

**Issue by flyboi00** [kubilus1/autoortho#258]
I have been tried using this Autoortho In different versions. Both Exe and Zip file. Many times I have also downloaded the "eu" file package again and tried a different map service provider. This game still keeps freezing when I enter a new area. It can't be about the internet speed because I use Optical fiber network and i get around 600-700. I have been installing Dokan and winfps But I don't notice any difference myself. Autoortho still continues to freeze when entering a new area.

---------- System ----------

Windows 11
X Plane 12  
AutoOrtho 0.4.4

GPU Nvidia RTX 2070 Q Max (laptop)
CPU	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
WD Blue SN570 1 Tt M.2 NVMe SSD
RAM	16,0 Gt

[Log.txt](https://github.com/kubilus1/autoortho/files/12004381/Log.txt)

**Comment by dpdurst** [comment]
Without a matching AutoOrtho log and log.txt from XP hard to say. Here is where you exited out to the main menu, about 4 seconds after AO was pulling in scenery. I can already tell you Jets (you were flying the Zibo) and AO streaming whether you have a 10GB or 1000GB connection at your house does not matter. You have a few things limiting this 

1. Jets will be able to outfly the stream more than likely
2. You may be getting throttled further upstream from you house
3. You are running this on a laptop.

0:40:54.348 D/SCN: Generating detailed DEM for 'Custom Scenery/z_eur_05/Earth nav data/+50+020/+56+022.dsf'
0:40:58.177 I/WIN: Showing subscreen Freeflight
0:40:58.177 I/OVR: User is entering the holodeck.
0:40:58.177 I/WIN: Opened window Primary V11 UI
0:40:59.866 I/SIM: Exiting the sim without confirmation
0:40:59.887 D/STM: Transitioning from state state_Normal to state_ShuttingDown
FlyWithLua Info: Load exit file.
FlyWithLua Info: Exit file loaded.

Fly something slower SEL or MEL and see if you get the same pauses happening. I suspect you won't or it will be so slight its barely noticed at all.

**Comment by flyboi00** [comment]
I downloaded X Plane 11 to my laptop and tested how Autoortho behaves now.  Instead of Xplane 11 continuing to freeze I noticed that i was missing a big chunk of tiles.  so I don't think it's a hardware problem.  I don't think that the problem could be that I play on a laptop.  I've seen much worse desktop computers that still run autoortho.  In any case, the end result was reasonably interesting.
[autoortho.log](https://github.com/kubilus1/autoortho/files/12015941/autoortho.log)
  A log file is i
![20230711164046_1](https://github.com/kubilus1/autoortho/assets/81065518/2ce8e240-6813-44ca-9fc7-844dd8119abe)
ncluded if it would help to develop the software further.
[Lo
![20230711171104_1](https://github.com/kubilus1/autoortho/assets/81065518/1cca98fd-cdd0-49a8-a210-eb3d0eec4857)
g.txt]
![20230711171701_1](https://github.com/kubilus1/autoortho/assets/81065518/2c59e655-538d-4c99-b191-bc5b9cc74f1b)
(https://github.com/kubilus1/autoortho/files/12015945/Log.txt)

**Comment by flyboi00** [comment]
I downloaded X Plane 11 to my machine and tested how Autoortho behaves.  Instead of xplane continuing to freeze I noticed that i was missing a big chunk of tiles.  so I don't think it's a hardware problem.  I don't think that the problem could be that I play on a laptop.  I've seen much worse desktop computers that still run autoortho.  in any case, the end result was reasonably interesting.  A log file is included if it would help to develop the software further.
![20230711171701_1](https://github.com/kubilus1/autoortho/assets/81065518/86a33bcb-6dd9-4400-87f4-910fbf7c4467)
![20230711171104_1](https://github.com/kubilus1/autoortho/assets/81065518/bf9b7a2d-b61a-4672-8738-d48416902274)
![20230711164046_1](https://github.com/kubilus1/autoortho/assets/81065518/b64b9acb-0cd8-4c11-8dc7-4ecfee4bc914)
[Log.txt](https://github.com/kubilus1/autoortho/files/12015975/Log.txt)
[autoortho.log](https://github.com/kubilus1/autoortho/files/12015981/autoortho.log)
