### ISSUE TITLE
X-Plane 12 cannot find resource and stuck at "Reading new scenery files"

### ISSUE THREAD

**Issue by cptalpdeniz** [kubilus1/autoortho#262]
**Describe the bug**
X-Plane 12 hangs on loading screen "Reading new scenery files" and auto-ortho has many errors and other log entries.

**To Reproduce**
1. Open auto-ortho
2. Click Run
3. Open XP-12
4. Start a flight 

**Expected behavior**
Sim should load the scenery files and open

**(please complete the following information):**
 - OS: Windows 11 64-bit
 - XPlane Version: XP12 latest version
 - AutoOrtho Version 0.4.4
 - Filesystem type NTFS
 
**Additional context**
The logs can be found below.  FYI the `Error, could not locate image file for terrain` error at the bottom of the X-Plane log file is because I closed Auto-ortho exe. 
@kubilus1 

[autoortho.log](https://github.com/kubilus1/autoortho/files/12032614/autoortho.log)
[Log.txt](https://github.com/kubilus1/autoortho/files/12024452/Log.txt)

**Comment by marloscaida** [comment]
cptalpdeniz:

I would think that you are from the group of unfortunate ones that version 0.5.0-2 does not work for us (like me...!) that we have Windows 11 with an Intel processor.

Install -with confidence- version 0.4.4 which works great with XP12, Windows 11 and Intel processor.

Regards

carlos

**Comment by cptalpdeniz** [comment]
> Install -with confidence- version 0.4.4 which works great with XP12, Windows 11 and Intel processor.

Hello Carlos, as you can see from my initial post that I tried the latest version, 0.5.0-2, 0.5.0-1 and 0.4.4. 

**UPDATE:** The issue was fixed when I enabled VPN. Any idea why? @kubilus1

**Comment by kubilus1** [comment]
You could be blocked or throttled by ip address or if outside the US, geo
location.

**Comment by cptalpdeniz** [comment]
Blocked by ISP or the map provider service? Can you elaborate more?

**Comment by kubilus1** [comment]
Basically the system relays requests to map providers such as servers for
Bing maps.  Bing may decide to limit the requests, or block requests
completely for whatever reason they choose.  I know some folks have had
luck using a VPN to get around that, but I can't speak personally on how
well that works.

**Comment by Meistari** [comment]
I have the same trouble with version 0.6.1. Windows 11, Intel CPU. Any solution?

**Comment by Meistari** [comment]
UPD: Tried to switch to other map provider (Firefly), but still stuck
