### ISSUE TITLE
Unable to see other categories in application

### ISSUE THREAD

**Issue by Kaj2006** [kubilus1/autoortho#266]
### Discussed in https://github.com/kubilus1/autoortho/discussions/265

<div type='discussions-op-text'>

<sup>Originally posted by **Kaj2006** July 13, 2023</sup>
### Please check existing docs and issues first.

- [X] I have checked for existing answers
- [X] This is not a bug or other "Issue"
- [X] I have read the FAQ and documentation

### System Details

- OS: [e.g. Windows 10]
- XPlane Version: [e.g. XP12 beta 4]
- AutoOrtho Version [e.g. 0.4.3]
- Filesystem type (NTFS, exFAT, etc)

### question

Dont quite know how to describe it. I followed the installation instructions to a T, but im unable to see "Scenery" or "Setup" as well as the section below "image cache dir"
![Screenshot 2023-07-13 213234](https://github.com/kubilus1/autoortho/assets/69185779/04fb90fc-fea3-4ebf-869a-e078a1b93f7c)

</div>

**Comment by dpdurst** [comment]
Go into your Windows display settings looks like you have your fonts or screen size larger than 100%
