### ISSUE TITLE
The app will not open

### ISSUE THREAD

**Issue by Iixidy** [kubilus1/autoortho#277]
Whenever I try and open the autoortho.exe I only see the command prompt, not the app where I install the scenery. Tried reinstalling, didn't work.

**Comment by maxl-daxl** [comment]
i have the same problem

**Comment by chezhj** [comment]
in .autoortho (in your user directory) make sure the following is set

```
# use gui config at startup
gui = True
# show config setup at startup everytime
showconfig = True

```

Then you will see the config screen 
Or start with -c param:  
`autoortho_win.exe -c`
