### ISSUE TITLE
ERROR: File is not a zip file with Zipfile

### ISSUE THREAD

**Issue by LucasWin99** [kubilus1/autoortho#279]
**Describe the bug**
After everything is installed, the script starts to "clean up" each of the zip files but it gives me this error every time

**To Reproduce**
Install North America
wait for everything to download
once the overlays have been installed it gives me an error

**Expected behavior**
I expected it to complete installation so I can use auto ortho

**Screenshots**
![Screenshot (1)](https://github.com/kubilus1/autoortho/assets/140021582/b8fe3149-1821-498f-ba54-3d07ce090eb8)

**(please complete the following information):**
 - OS: Windows [11]
 - XPlane Version: [e.g. XP11.55
 - AutoOrtho Version 0.4.1
 - Filesystem type (NTFS, exFAT, etc)

**Additional context**
I have installed both WinFSP and Doken and Python

**Comment by dpdurst** [comment]
Your AutoOrtho version if 4.1 needs to be updated to 4.4 or 5.x
