### ISSUE TITLE
AutoOrtho Causes Freezing of X-Plane 12 when Flying Over Certain Locations

### ISSUE THREAD

**Issue by SammyBeen** [kubilus1/autoortho#281]
Whenever I fly over Village Bay on Mayne Island in British Columbia, Canada (48° 51' 7.07" N 123° 20' 48.82" W) using AutoOrtho, X-Plane 12 freezes.  It happens repeatedly and consistently.  Occasionally X-Plane 12 will "unfreeze" for a minute, but then it "re-freezes" shortly thereafter.

I'm really loving this Add-On and hope that this issue can be solved.  Thank You! for you hard work and efforts to support the X-Plane flight sim community.

**(please complete the following information):**
 - OS: Windows 11
 - XPlane Version: X-Plane 12.05r1 (build 120504 Intel 64-bit, Vulkan f7b628ec95e0ea64bb6d708dfc264044be6263f1)
 - AutoOrtho Version - 0.4.4 (Current version posted at https://kubilus1.github.io/autoortho/)
 - Filesystem type NTFS

**Additional context**
Here are some of the pertinent .log/.txt files:

[.autoortho.txt](https://github.com/kubilus1/autoortho/files/12135293/default.autoortho.txt)
[.release_info.txt](https://github.com/kubilus1/autoortho/files/12135294/default.release_info.txt)
[autoortho.log](https://github.com/kubilus1/autoortho/files/12135295/autoortho.log)
[debug.log](https://github.com/kubilus1/autoortho/files/12135296/debug.log)
[Log.txt](https://github.com/kubilus1/autoortho/files/12135297/Log.txt)

**Comment by dpdurst** [comment]
This is not an AutoOrtho issue see from your log below, this is just a side affect from streaming from the servers in different area's or using an external drive possibly. Some days may be better than others, some days worse. You could try a VPN connection or changing the max_wait time in the autoortho configration file found at c:\users\<your username> directory.

// This below is not finding the information it needs on your drive. What is your r:\drive is it an external SSD or HD? If so you may want to move this to an internal SSD or M.2 drive (worse case HD) as it may help out in searching for the data.

WARNING:getortho:GET_IMG: FAILED! Chunk(42835,91920,BI,18,12):  LEN: 13011  HEADER: b'\xff\xd8\xff\xe0\x00\x10JF'
INFO:getortho:GET_IMG: Tile Tile(10736, 22928, BI, 16, 12, R:/Cache) Try to find backup chunk.
WARNING:getortho:GET_IMG: FAILED! Chunk(10739,22928,BI,16,12):  LEN: 18819  HEADER: b'\xff\xd8\xff\xe0\x00\x10JF'
INFO:getortho:GET_IMG: Tile Tile(42816, 91936, BI, 18, 12, R:/Cache) Try to find backup chunk.
WARNING:getortho:GET_IMG: Empty chunk data.  Skip.
INFO:getortho:GET_IMG: Tile Tile(42272, 91264, BI, 18, 12, R:/Cache) Try to find backup chunk.
INFO:getortho:GET_IMG: Tile Tile(10736, 22800, BI, 16, 12, R:/Cache) Try to find backup chunk.
INFO:getortho:GET_IMG: Tile Tile(10736, 23040, BI, 16, 12, R:/Cache) Try to find backup chunk.
INFO:getortho:GET_IMG: Tile Tile(42832, 91936, BI, 18, 12, R:/Cache) Try to find backup chunk.
WARNING:getortho:GET_IMG: Empty chunk data.  Skip.
WARNING:getortho:GET_IMG: Empty chunk data.  Skip.
WARNING:getortho:GET_IMG: Empty chunk data.  Skip.

// This below is good data being found and streamed, this is what you want to see all the time happening

INFO:aostats:STATS: ID: {'count': 99523, 'chunk_hit': 84115, 'partial_mm_averages': {0: 0.012}, 'partial_mm_counts': {0: 9747}, 'mm_counts': {0: 39, 1: 87, 2: 79, 3: 164, 4: 20738}, 'mm_averages': {0: 0.085, 1: 0.075, 2: 0.02, 3: 0.01, 4: 0.009}, 'chunk_miss': 51421, 'bytes_dl': 156775258, 'backup_chunk_count': 1138, 'chunk_missing_count': 9688, 'minutes_to_start': 5.77}

**Comment by SammyBeen** [comment]
Thank you so much for your response.  I'm sorry, but I should have supplied you with more information about my desktop computer.  Here are the details:

Hardware
CPU: 13th Gen Intel(R) Core(TM) i7-13700F
MB: ASUS Pro B760M-CT (Raptor Lake-S PCH)
GPU: ASUS TUF RTX 3080 GAMING w 10240 MBytes of GDDR6X SDRAM [Micron]
RAM: 96GB DDR5 SDRAM running at 2x2400 MHz = 4800 MHz; Current Timing (tCAS-tRCD-tRP-tRAS): 40-39-39-76 (default)
Network: Intel(R) Ethernet Connection (22) I219-V - Maximum Link Speed: 1000 Mbps
Drives:	Drive C: (OS) NTFS - PNY CS1030 1TB SSD M.2 - NVMe (PCIe 4x 8.0 GT/s)
	Drive F: (X-Plane 12; autoortho_win) NTFS - KINGSTON SKC3000D2048 2TB M.2 - NVMe (PCIe 4x 16.0 GT/s)
	Drive D: (DATA) ST4000DM004-2U9104 4TB NTFS - Serial ATA 6Gb/s @ 6Gb/s
	Drive R: (R:/Cache - AutoOrtho) NTFS - RamDrive using 16GB created with ImDisk Virtual Disk Driver (2.1.1)

Software
OS: Microsoft Windows 11 Professional (x64) Build 22621.1992 (22H2)
XPlane Version: X-Plane 12.05r1 (build 120504 Intel 64-bit, Vulkan f7b628ec95e0ea64bb6d708dfc264044be6263f1)
AutoOrtho Version - 0.4.4

Update:

1.) I made a small change to my scenery_packs config file after re-reading your setup suggestions for this file. I had previously arranged the beginning of my Ortho files as follows:

SCENERY_PACK Custom Scenery/-------------------- Ortho --------------------/
SCENERY_PACK Custom Scenery/yAutoOrtho_Overlays/
SCENERY_PACK Custom Scenery/z_autoortho/
SCENERY_PACK Custom Scenery/z_na_00/
etc.

But I noticed that you had suggested that the "SCENERY_PACK Custom Scenery/z_autoortho/" be the last entry, so now my scenery_packs config file looks like this:

SCENERY_PACK Custom Scenery/-------------------- Ortho --------------------/
SCENERY_PACK Custom Scenery/yAutoOrtho_Overlays/
SCENERY_PACK Custom Scenery/z_na_00/
etc.
SCENERY_PACK Custom Scenery/z_sa_15/
SCENERY_PACK Custom Scenery/z_autoortho/

2.) I persisted in flying to the same location and eventually got through that area that was causing a "freeze" and "crash" to x-Plane 12 without crashing (though it did freeze for a couple of minutes).

So I am encouraged.  I would really like this setup to work consistently, as I think that what you have done to create AutoOrtho is nothing sort of amazing and X-Plane users should be extremely grateful for you contributions to this flight sim community.

As you can see from my hardware description, I am NOT using an external drive for my AutoOrtho Cache files but rather a very fast 16GD RAMDrive using my DDR5 RAM memory.  I can do this because I recently upgraded by RAM memory from 32GB to 96GB and have lots to spare.  Before I did this memory upgrade and created the RAMDrive, I was using my faster M.2 SSD which is Drive F: for the AutoOrtho Cache and the location of my X-Plane 12 installation.  Before making the change to the RAMDrive I was also experiencing some "freezes" and "crashes" of XP12 in certain locations.

If you have any further suggestions on how I can may this work more consistently, I am open to trying anything, and I will try running my internet connect through a VPN.  I will also try changing the max_wait time in the autoortho configration file.  It is currently set at 1.5. Perhaps I should try 2 or higher?

Thanks again.
