### ISSUE TITLE
FPS drop to very low above south UK when I start decent do Bristol

### ISSUE THREAD

**Issue by Aculeus1** [kubilus1/autoortho#290]
Hello.
Near a west of Kingsbridge, when start descent via Trojaq1B to Bristol EGGD. All flight time I have fps above 60, no matter the region, but when I cross this one location FPS drop radically to 3-5. Texture on ground are very blurry. I try many times and always this happens there.

**Comment by marloscaida** [comment]
If before starting the flight, you put your C172 at different airports, along the route, could help

**Comment by Aculeus1** [comment]
Thank you! It's working. First, I have couple freezes above Trojaq1B, but after sim back to normal and I can continue. Texture are blurry at level 250-240, but when I passed 210 they load in high quality and everything back to normal.
