### ISSUE TITLE
Firewall blocking autoortho_win.exe

### ISSUE THREAD

**Issue by RogerK888** [kubilus1/autoortho#297]
autoortho_win.exe is being blocked because the exe respawns itself into temporary folder and launches.

For example: C:\users\<username>\appdata\local\temp\onefile_3696_133350554859507474\autoortho_win.exe

The firewall is simplewall. It denies the process, and autoautho exits before I can allow it. 

The question is, why is is the exe respawning itself into a temp and hidden directory? Can this behaviour be changed?

**Comment by dpdurst** [comment]
Each Virus protection software handles .exe in different ways. The default Windows Defender does not have this issue at all. Have you tried to create exclusions so that  your virus software does not try and block the executable from running? You should have not be running the software in order to allow exclusions.

**Comment by RogerK888** [comment]
I got around the problem by downloading the complete zip package and
installing into its own folder. Previously I just had the exe in my x-plane
folder, and it appears the exe was respawning itself into a temporary
directory, and a different one every time, making it impossible for my
firewall to deal with it.
As I originally mentioned, the exe would exit way too quickly on no network
access, so my firewall would ask for permission, but by the time I could
say yes, the application had already exited. Then on the next attempt, the
exe was in a different temp folder and the problem repeated.

Anyhow, downloading the latest complete zip file and installing into it's
own folder seemed to solve the problem. Maybe you could document that
somewhere.

**Comment by chezhj** [comment]
I'm guessing the re-spawning is because the exe is actually unpacking it self then running python
