### ISSUE TITLE
Auto Ortho will not work - cannot load into flight

### ISSUE THREAD

**Issue by chairpilot** [kubilus1/autoortho#304]
System

- OS:  Windows 11
- XPlane Version: 12.05r1
- AutoOrtho Version 0.4.4
- Filesystem type NTFS
- i9 13900K
- NVIDIA RTX 4090
- 64 GB DDR5
- 4TB and 8TB NVME

Order of Events

1. Run Auto Ortho exe file
2. Load into an X-Plane flight
3. This program has stopped responding
4. End task from task manager

I cannot get Auto Ortho to run. When I try to load in to X-Plane it just sits there until it gives up. Terminal window shows that there are some issues but I have no idea what any of this means. I don't have a masters degree in computer science, so I am kinda up the creek there. I have installed this exactly as described. My .ini file is configured properly from what I understand. Dokan is installed. The .exe is run concurrently with the software. I do not understand why it will not run. Can someone please provide me some insight into how I can fix this? I have attached several screenshots of the terminal window  as it is trying to load the ortho scenery as well as my .ini file. Thank you for your help. Please help........
![AutoOrthoBS](https://github.com/kubilus1/autoortho/assets/141291745/f6708469-6adf-430d-b13a-5ad08db8157a)
[sceneryorderXP12.txt](https://github.com/kubilus1/autoortho/files/12246332/sceneryorderXP12.txt)

**Comment by chezhj** [comment]
SCENERY_PACK Custom Scenery/z_autoortho/ 
Should not be on top in you ini, put it direct behind yAutoOrtho_Overlays/
First load can take a while, if windows is says: stopped responding, just wait.. sometimes it comes back again
Perhaps this video can help to https://www.youtube.com/watch?v=owbdWzdKwm4
