### ISSUE TITLE
In TileCacher "tiles" is a class variable

### ISSUE THREAD

**Issue by hotbso** [kubilus1/autoortho#307]
```
class TileCacher(object):
    tiles = {}
....    
    def __init__(self, cache_dir='.cache'):
....
        self.tc_lock = threading.RLock()

```
... but the locks are per instance (= per mount thread). Doesn't that mean unlocked access?

**Comment by kubilus1** [comment]
Hmm, yeah, this is probably not quite right.  It's probably *not* and issue since there is one TileCacher instance per mount thread and each mount covers different areas so effectively only one is active at a time, but still ugly.

**Comment by hotbso** [comment]
I'm more concerned because each mount thread has a cleaning thread and they can all clean the same tiles dict in parallel without locking.

**Comment by kubilus1** [comment]
Good point.  Fixing...
