### ISSUE TITLE
Autoortho

### ISSUE THREAD

**Issue by chuk07** [kubilus1/autoortho#313]
when I run the auto ortho .exe file  version 4,4 to download the scenery files for europe. some of the .zip files do not download to 100%. So when the program comes to  extract the zip files that are not downloaded 100% the "error message"  this is not a Zip file appears.

**To Reproduce**

**Expected behavior**

**Screenshots**

**(please complete the following information):**
 - OS: [e.g. Windows 11]
 - XPlane Version: [e.g. XP12 beta 4]
 - AutoOrtho Version [e.g. 0.4.3]
 - Filesystem type (NTFS, exFAT, etc)

**Additional context**

**Comment by kubilus1** [comment]
Latest releases should handle retries better.

**Comment by chuk07** [comment]
Thank you, I will test it.Sent from Android deviceOn 19 Aug 2023 19:33, kubilus1 ***@***.***> wrote:
Closed #313 as completed.
