### ISSUE TITLE
RuntimeError: main threat is not in main loop

### ISSUE THREAD

**Issue by confile** [kubilus1/autoortho#317]
Hi, 
I run the 0.5 pre release and get the following error when downloading EU map. RuntimeError: main threat is not in main loop

![image](https://github.com/kubilus1/autoortho/assets/64265/ab1c80e5-4803-4384-96e8-d0204373b67a)

**Comment by kubilus1** [comment]
I think this is just some kind of GUI refresh issue on Windows.  I suspect the process still works, but the GUI stops updating.
