### ISSUE TITLE
Problems with autoortho-0.5.1-2

### ISSUE THREAD

**Issue by marloscaida** [kubilus1/autoortho#320]
Kubiluis1:

This is what happens when I run run.bat in version autoortho-0.5.1-2. There is no log (it is not generated). So I ran the commands one by one in a CMD and this is what happens:

E:\autoortho-0.5.1-2>py -m pip install -r requirements-win.txt
Collecting pillow-simd@ https://download.lfd.uci.edu/pythonlibs/archived/Pillow_SIMD-9.0.0.post0-cp310-cp310-win_amd64.whl (from -r requirements-win.txt (line 31))
  Using cached https://download.lfd.uci.edu/pythonlibs/archived/Pillow_SIMD-9.0.0.post0-cp310-cp310-win_amd64.whl (2.6 MB)
Requirement already satisfied: bidict==0.22.1 in c:\python310\lib\site-packages (from -r requirements-win.txt (line 7)) (0.22.1)
Requirement already satisfied: click==8.1.3 in c:\python310\lib\site-packages (from -r requirements-win.txt (line 9)) (8.1.3)
Requirement already satisfied: dnspython==2.3.0 in c:\python310\lib\site-packages (from -r requirements-win.txt (line 11)) (2.3.0)
Requirement already satisfied: eventlet==0.33.3 in c:\python310\lib\site-packages (from -r requirements-win.txt (line 13)) (0.33.3)
Requirement already satisfied: flask==2.2.2 in c:\python310\lib\site-packages (from -r requirements-win.txt (line 15)) (2.2.2)
Requirement already satisfied: flask-socketio==5.3.4 in c:\python310\lib\site-packages (from -r requirements-win.txt (line 19)) (5.3.4)
Requirement already satisfied: greenlet==2.0.2 in c:\python310\lib\site-packages (from -r requirements-win.txt (line 21)) (2.0.2)
Requirement already satisfied: itsdangerous==2.1.2 in c:\python310\lib\site-packages (from -r requirements-win.txt (line 23)) (2.1.2)
Requirement already satisfied: jinja2==3.1.2 in c:\python310\lib\site-packages (from -r requirements-win.txt (line 25)) (3.1.2)
Requirement already satisfied: markupsafe==2.1.2 in c:\python310\lib\site-packages (from -r requirements-win.txt (line 27)) (2.1.2)
Requirement already satisfied: psutil==5.9.4 in c:\python310\lib\site-packages (from -r requirements-win.txt (line 33)) (5.9.4)
Requirement already satisfied: pysimplegui==4.60.4 in c:\python310\lib\site-packages (from -r requirements-win.txt (line 35)) (4.60.4)
Requirement already satisfied: python-engineio==4.4.1 in c:\python310\lib\site-packages (from -r requirements-win.txt (line 37)) (4.4.1)
Requirement already satisfied: python-socketio==5.8.0 in c:\python310\lib\site-packages (from -r requirements-win.txt (line 39)) (5.8.0)
Requirement already satisfied: refuse==0.0.4 in c:\python310\lib\site-packages (from -r requirements-win.txt (line 41)) (0.0.4)
Requirement already satisfied: six==1.16.0 in c:\python310\lib\site-packages (from -r requirements-win.txt (line 43)) (1.16.0)
Requirement already satisfied: werkzeug==2.2.2 in c:\python310\lib\site-packages (from -r requirements-win.txt (line 45)) (2.2.2)
Requirement already satisfied: winfspy==0.8.3 in c:\python310\lib\site-packages (from -r requirements-win.txt (line 47)) (0.8.3)
Requirement already satisfied: colorama in c:\python310\lib\site-packages (from click==8.1.3->-r requirements-win.txt (line 9)) (0.4.6)
Requirement already satisfied: cffi>=1.0.0 in c:\python310\lib\site-packages (from winfspy==0.8.3->-r requirements-win.txt (line 47)) (1.15.1)
Requirement already satisfied: pycparser in c:\python310\lib\site-packages (from cffi>=1.0.0->winfspy==0.8.3->-r requirements-win.txt (line 47)) (2.21)
E:\autoortho-0.5.1-2>py autoortho
Config file found C:\Users\carluchinx\.autoortho reading...
Found sceneries: ['z_ao_sa']
[{'root': 'C:/Program Files (x86)/Steam/steamapps/common/X-Plane 12/Custom Scenery\\z_autoortho\\scenery\\z_ao_sa', 'mount': 'C:/Program Files (x86)/Steam/steamapps/common/X-Plane 12/Custom Scenery\\z_ao_sa'}]
Saving config ...
Wrote config file: C:\Users\carluchinx\.autoortho
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\autoortho-0.5.1-2\autoortho\__main__.py", line 28, in <module>
    import autoortho
  File "E:\autoortho-0.5.1-2\autoortho\autoortho.py", line 14, in <module>
    import config_ui
  File "E:\autoortho-0.5.1-2\autoortho\config_ui.py", line 16, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'

**Comment by mikecbr** [comment]
same

**Comment by kubilus1** [comment]
I've updated requirements-win.txt to include the missing 'packaging' req for those running from source on Windows.
