### ISSUE TITLE
FPS downgrade with AutoOrtho at some Parts of the World

### ISSUE THREAD

**Issue by fresH229a** [kubilus1/autoortho#324]
**Describe the bug**
First of all, the tool you are created is absoluty amazing.
Unfort. at some parts of the World, the FPS gets really downgraded, I have no idea why.
Example: At the area of EHAM, my FPS went (without AutoOrtho) from 50+ to nearly 3-10.
Is this probably of the big files and canals they are shown there? Can this be fixed in any way?

Another Example is the area in Norway (Bergen).

**(please complete the following information):**
 - OS: Win 11
 - XPlane Version: XP12 latest Beta
 - AutoOrtho: latest version
 - Filesystem type: NTFS

**Comment by chezhj** [comment]
EHAM is a "famous" for the FPS drops, regardless of autoortho. I've been told it could be because it's below sea-level
