### ISSUE TITLE
Maybe failure to create the symbolic link is causing error to load X-Plane and scenery 

### ISSUE THREAD

**Issue by tadeuprimo** [kubilus1/autoortho#330]
Failure to load the sim and scenery

 When try to load the sim, the first image appears 

![image](https://github.com/kubilus1/autoortho/assets/20975928/62f69c9f-c436-497b-9e63-4472c2b542fd)

If I try to create the symbolic link my self to the folder "z_ao_na", now it comes with the following error.

![image](https://github.com/kubilus1/autoortho/assets/20975928/f9bf35fa-3bb4-4b28-89d9-bb0fe746ac59)

 - OS: [e.g. Windows 10]
 - XPlane Version: 12.06  b6
 - AutoOrtho Version [e.g. 0.5.1-3]
 - Filesystem type (NTFS)

**Comment by chezhj** [comment]
Any errors in the "terminal" window of autoOrtho?

**Comment by MsgLedeni** [comment]
Same problem, and no, terminal doesn't give any errors

**Comment by AntonKuf** [comment]
Same problem 
![X-Plane Screenshot 2023 08 19 - 13 54 28 04](https://github.com/kubilus1/autoortho/assets/70604383/dd4a2011-e6c7-460f-86ea-52ebd7d603c8)

**Comment by MsgLedeni** [comment]
Hi,
As You can see symbolic link exist and when I start AO it changes under
properties from Owner: Unknown to DOKAN

**Comment by tadeuprimo** [comment]
Solved ✅

I posted the solution that worked for me in the x-Plane forum

In the documentation, you can use Dokan or WinFSP as backup.

I followed the instruction, uninstalling the Dokan, reboot, install WinFSP, reboot and start autoortho again.

The SCENERY_PACK.ini is running a in this order , the end of the file. (I tested "z_autoortho" above the "z_ao_na" and "z_ao_sa" and it make no difference. 

I'm also using the *.zip version of AutoOrtho because if something is wrong in the settings, you can easily remove the AutoOrtho folder and create a new one again with default settings. 

Now its again working fine, SA and NA with no issues.

https://forums.x-plane.org/index.php?/forums/topic/290048-autoortho/&do=findComment&comment=2596353
