### ISSUE TITLE
Release 0.5.1 error while loading flight

### ISSUE THREAD

**Issue by confile** [kubilus1/autoortho#331]
I just tried to load Release 0.5.1 of autoortho. It loads a flight but there are two errors. 

1. X-Plane 12 reportes it cannot read eu00 file and crashs or it loads a flight and there are no objects around the please.

**Comment by confile** [comment]
I did check that. I use XOrganizer which works great to find the correct order. Autoortho scenery are always at the bottom.

**Comment by Skymatix** [comment]
It is not just that file. It happens on others as well. It tells us that XP cannot run with this package installed, Once you click on understood, XP closes.

Matt, I have spent hours on this issue with Johan Reynolds. It does not matter which continent you do it gives the same error. 
I have uninstalled and reinstalled and checked every aspect to match my installation and it still tells us we need to remove the file as XP cannot run with it. It works perfectly on my system and the only big difference is that I use an AMD graphics card!

We even tried a new XP12 installation without the latest Beta and still it complains, I cannot see a difference between his system and my system except for the Python error I asked him to email you, from Event Viewer.
The only thing we have not done is to uninstall and reinstall Python yet.

Matt, also for your information, Facebook is full of users reporting this issue. The users are getting restless and dumping the program big time now. Please try and find a solution fast.

Let me know if you need more information.

**Comment by moragonm1** [comment]
[autoortho1113220823.log](https://github.com/kubilus1/autoortho/files/12407742/autoortho1113220823.log)

my log after investigating if python might be an issue. deleted python 3.10.9, ran xp12 same issue, reinstalled python no change same issue.

**Comment by jtrim1** [comment]
Experiencing this same issue.  Install latest AutoOrtho 0.5.1-3.  Installed Dokan.  launched AutoOrtho and installed North America scenery fully.  Run AutoOrtho (output window seems fine, z_ao_na folder is created in the Custom Scenery directory, looks like a linked folder, but I can open it and see typical folders inside, Earth nav data, terrain, textures).   Load x-plane (latest beta as of this morning) select default 172 and airport (tried near Dayton, OH, also Chicago, IL)   when sim starts to load, given error: "Error loading the scenery package: Custom Scenery/z_ao_na/"   click "Understood" and sim quits.   I tried uninstalling Dokan, rebooting, then installing WinFSP.   Relaunched AutoOrtho as above, saw message from WinFSP that the z_ao_na folder already existed and it needed to re-create it, I allowed it to do that.  Launched x-plane and had same results.   back to Dokan, but still having same results.  Running windows 10

**Comment by Skymatix** [comment]
![Screenshot_6](https://github.com/kubilus1/autoortho/assets/63475005/066db090-2c0a-473a-9804-85b5a82f1a45)
This is what lead me to question Python

**Comment by coptered** [comment]
I am having the same issues.  I can get Xplane12 to load with WinFSP, but it keeps moving the z_ao_na to the top of the scenery_packs.ini file and I lose all overlays..  It will not stay at the bottom.

**Comment by moragonm1** [comment]
Stupid question. You ARE saving the ini file when you have moved z_ao_na to the correct position. Because once saved it CANNOT  moved.Sent using the mail.com mail appOn 22/08/2023 at 16:38, coptered wrote:
                
            
            
                
                    From: "coptered" ***@***.***>Date: 22 August 2023To: "kubilus1/autoortho" ***@***.***>Cc: "John Reynolds" ***@***.***>,"Comment" ***@***.***>Subject: Re: [kubilus1/autoortho] Release 0.5.1 error while loading flight (Issue #331)
                
                
I am having the same issues.  I can get Xplane12 to load with WinFSP, but it keeps moving the z_ao_na to the top of the scenery_packs.ini file and I lose all overlays..  It will not stay at the bottom.

**Comment by coptered** [comment]
Yes, I save it.  I have edited it manually and used XOrganizer.  I have even noticed that the entry is deleted when I close Xplane.  I never had these issues with the 0.4 version.

**Comment by Skymatix** [comment]
Right so the issue for John seems to be Dokan... Uninstalled it and installed WinSFP and it works now. How is that possible or is that just how it is?

**Comment by tadeuprimo** [comment]
Solved for me ✅

I posted the solution that worked for me in the x-Plane forum

In the documentation, you can use Dokan or WinFSP as backup.

I followed the instruction, uninstalling the Dokan, reboot, install WinFSP, reboot and start autoortho again.

The SCENERY_PACK.ini is running a in this order , the end of the file. (I tested "z_autoortho" above the "z_ao_na" and "z_ao_sa" and it make no difference. 

I'm also using the *.zip version of AutoOrtho because if something is wrong in the settings, you can easily remove the AutoOrtho folder and create a new one again with default settings. 

Now its again working fine, SA and NA with no issues.

https://forums.x-plane.org/index.php?/forums/topic/290048-autoortho/&do=findComment&comment=2596353

**Comment by jtrim1** [comment]
> Solved for me ✅
> 
> I posted the solution that worked for me in the x-Plane forum
> 
> In the documentation, you can use Dokan or WinFSP as backup.
> 
> I followed the instruction, uninstalling the Dokan, reboot, install WinFSP, reboot and start autoortho again.
> 
> The SCENERY_PACK.ini is running a in this order , the end of the file. (I tested "z_autoortho" above the "z_ao_na" and "z_ao_sa" and it make no difference.
> 
> I'm also using the *.zip version of AutoOrtho because if something is wrong in the settings, you can easily remove the AutoOrtho folder and create a new one again with default settings.
> 
> Now its again working fine, SA and NA with no issues.
> 
> https://forums.x-plane.org/index.php?/forums/topic/290048-autoortho/&do=findComment&comment=2596353

This initially worked for me.  I think the trick was one of two things...   uninstall Dokan, reboot, install WinFSP, reboot.    OR downloading the zip version of the AutoOrtho and using that.     After I did both of those things in full (My SCENERY_PACK.ini was never and issue, I always made sure those lines were in the correct position)  it worked.  It was great!   I spent a good hour flying around enjoying the autoortho scenery.   I closed the sim and went to bed.   This morning, I thought I'd give it another go so I launched autoortho from the folder where I extraced the zip, once it was up and running, I launched x-plane, selected my airport (same airport as last night) and clicked to fly, and after a little bit, x-plane complained that it couldn't load scenery from "z_ao_na" folder and closed to desktop, just like before.   I literally changed nothing.     Just wanted to post here to add that info.

**Comment by jtrim1** [comment]
just launched AutoOrtho again, and started x-plane and this time it worked.  I dunno.  I guess all the stars need to align for this to work.  Sorry for the double post!  I still think the key for mine working (at least some of the time) is what Tadeuprimo posted above.  thanks for the help!

**Comment by coptered** [comment]
I finally gave up and went back to 0.4.  I uninstalled WinFSP and installed Dokan and it errors.  I uninstalled Dokan and Installed WinFSP and X-plane12 keeps moving the z_ao_na to the top of scenery_packs.ini.  I am on Windows 11 and have an RTX 4080.  0.4.4 is works fine on Dokan.

**Comment by Mtarcis** [comment]
Hello friends, any solution for this problem? I already tried everything that was posted, I changed from Dokan to winFSP, I removed everything and installed it again and nothing, the Autoortho scenarios always go up to the beginning of the .ini file, if anyone can help me I will be grateful.

**Comment by moragonm1** [comment]
Your NOT going to like my recommendation. After spending almost three days on this issue along side of Nico Du Bryn and yes speaking with the developer sending all progress reports, we don’t at this time have a resolution or workaround. I would highly recommend you shelf for the time being any thoughts of installing AUTOORTHO Until such time as the current bugs have been resolved. That’s what I’ve decided to do myself. Sent using the mail.com mail appOn 24/08/2023 at 15:04, Mtarcis wrote:
                
            
            
                
                    From: "Mtarcis" ***@***.***>Date: 24 August 2023To: "kubilus1/autoortho" ***@***.***>Cc: "Comment" ***@***.***>,"John Reynolds" ***@***.***>Subject: Re: [kubilus1/autoortho] Release 0.5.1 error while loading flight (Issue #331)
                
                
Hello friends, any solution for this problem? I already tried everything that was posted, I changed from Dokan to winFSP, I removed everything and installed it again and nothing, the Autoortho scenarios always go up to the beginning of the .ini file, if anyone can help me I will be grateful.

**Comment by flyman-dc8** [comment]
After it crashes keep AO running and load XP again at the same location. It looks like the files it needs are not loaded the first time.

**Comment by jtrim1** [comment]
The issue is extremely intermittent for me.  I'm running about a 10% success rate in getting AutoOrtho running vs it not working and crashing when loading the scene.   So, while I thought some of the above suggestions were the fix, I can't say for sure they fixed, or if it's just always a hit or miss if the sim can access the symlink folder and access the scenery files it needs.   So, hopefully this will just get ironed out and a new release will get everyone back up and running.

**Comment by Mtarcis** [comment]
> 

I tested it and it gave an error when opening xplane 12, stating that the file cannot be read-only.

**Comment by HenriqueChenWyden** [comment]
This is normal, I just clicked on "ok" and X-Plane loaded normally.

**Comment by SimOld73** [comment]
I was having the same problem error loading scenery package: Custom Scenery/z_ao_aus_pac.  I went into the C:\Users\XXXX\.autoortho file and changed the debug mode from False to True.  Then I ran autoortho and XP and the scenery files loaded.  I then went back and changed the debug mode back to false and the scenery files still load.  Runnung the debug once has seemed to fix the problem

**Comment by SimOld73** [comment]
I was incorrect to say the debug mode fixed the problem somehow after I changed the debug mode back to False the z_ao_aus_pac got Disableed in the scenery_packs config file.  I don't know if the ortho scenery pack is loading in the debug mode or just being bypassed I just don't get the error when running in debug mode.  Attached is the the log file when running in debug mode
[autoortho Debug.txt](https://github.com/kubilus1/autoortho/files/12447108/autoortho.Debug.txt)

**Comment by chezhj** [comment]
Running into the same problem .. installed winFSP yesterday, that seemed to work. Today again xPlane can't start because of problems described above. 
I also noticed the links with winFSP are recreated so xplane identifies them as new scenery, putting them on top of the ini file every run of AutoOrtho. 
Trying a complete fresh install of autoortho now.. with Dokan first, then i'll try winFSP again.

**Comment by SimOld73** [comment]
I have tried Dokan and winFSP and neither have work.  The only way I have been able to get it to work is to change the debug mode from false to true in the .autoortho config file.  X-Plane then runs and from what I can tell it is loading the ortho scenery.  I have ran flights from the same airport with and without autoortho running and the scenery appears to be different when I run autoortho

**Comment by bloggo** [comment]
I initially installed the program and downloaded the scenery but could not get X Plane 12 to load. When I tried to download more scenery it had a blank page and on the CMD prompt page it had the following error: [WARNING: downloader: Couldn't update release info <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>].
Is anyone able to offer a solution to this problem and who would the remote host be?
