### ISSUE TITLE
New install: X-Plane cannot run with this package installed.

### ISSUE THREAD

**Issue by TMV-NL** [kubilus1/autoortho#335]
Hi,
I'm new to AO and hoping to be able to shed all my vast amounts of ortho files with AO. Unfortunately sofar it doesn't start for me.

1) I use XP12 with latest beta on a Win10 machine (i7/RTX3080).
2) I downloaded and installed AO (exe) and Dokan as instructed. Using the AO app.
3) I downloaded all areas with AO and they seem to be installed correctly.
4) With AO running (the DOS window is active), I started xOrganizer and put all AO files in the instructed order. I also disabled almost all other files, except SimHeaven, the default XP scenery and planes and the mesh. Just to have a faster and cleaner start.
The scenery_packs.ini has the AO order as instructed.
5) I run XP12 and select the airport.

When loading the scenery, I get the message:
**Error loading the scenery package: Custom Scenery/z_ao_eur/
X-Plane cannot run with this package installed. You may need to remove the custom scenery package.**

And XP shuts down. Sofar I have not been able to run XP with AO. Any suggestions?

[Log.txt](https://github.com/kubilus1/autoortho/files/12441310/Log.txt)

**Comment by marloscaida** [comment]
Something similar happened to me. I solved it by uninstalling DOKAN and installing WinFSP.
Try to uninstall Dokan, reboot the computer, then install WinFSP and try AutoOrtho again.

Download and install the latest version of WinFSP here:
https://github.com/winfsp/winfsp/tree/v2.0
(We recommend downloading the MSI file for installation)

Regars
carlos

**Comment by TMV-NL** [comment]
Hi Carlos,

I tried your suggestion. Unfortunately this seems not to be te solution in my case as I get the same error. I didn't compare the logs though to be honest.

Maybe you have some additional suggestions?

Kind regards,
Taco
________________________________
Van: marloscaida ***@***.***>
Verzonden: vrijdag 25 augustus 2023 20:14
Aan: kubilus1/autoortho ***@***.***>
CC: TMV-NL ***@***.***>; Author ***@***.***>
Onderwerp: Re: [kubilus1/autoortho] New install: X-Plane cannot run with this package installed. (Issue #335)


Something similar happened to me. I solved it by uninstalling DOKAN and installing WinFSP.
Try to uninstall Dokan, reboot the computer, then install WinFSP and try AutoOrtho again.

Download and install the latest version of WinFSP here:
https://github.com/winfsp/winfsp/tree/v2.0
(We recommend downloading the MSI file for installation)

Regars
carlos

**Comment by marloscaida** [comment]
Taco:

If you have Python version 3.10 installed on your computer, I would suggest that you install AO version 0.5.1-3, which you can download from here:
https://github.com/kubilus1/autoortho/releases/download/0.5.1-3/autoortho_win_0.5.1-3.zip

(requires some minimal knowledge of how Python is executed)
This version runs with RUN.BAT (no executable)

Regards
carlos

**Comment by marloscaida** [comment]
Taco:
Right now my installation works with AO version in Python and WinFSP.
I am at your disposal to collaborate with you.

Another trick: once you organize scenery_pack.ini you should change its property to be read-only, since XP12 changes the position of the virtual folder and you stop seeing your scenes.

At the bottom of the scenery_pack.ini the AO entry looks like this:

SCENERY_PACK Custom Scenery/yAutoOrtho_Overlays/
SCENERY_PACK Custom Scenery/z_ao_sa/
SCENERY_PACK Custom Scenery/z_autoortho/

regards
carlos

**Comment by TMV-NL** [comment]
Carlos,

I'm grateful for your support. I'll try the other AO version tomorrow.

As indicated, I use xOrganiser and I checked the ini file after XP crashed. The order in the file was still the same as I organised in xOrganiser, so that is covered.

Cheers,
Taco

**Comment by TMV-NL** [comment]
> Taco:
> 
> If you have Python version 3.10 installed on your computer, I would suggest that you install AO version 0.5.1-3, which you can download from here: https://github.com/kubilus1/autoortho/releases/download/0.5.1-3/autoortho_win_0.5.1-3.zip
> 
> (requires some minimal knowledge of how Python is executed) This version runs with RUN.BAT (no executable)
> 
> Regards carlos

Hi Carlos,
As it appeared, I am using the latest AO version 0.5.1-3 already, yet without succes with either DOKAN or WinFSP.
My installed are Python 2.7.17, 2.7.17 (64-bit) and 3.10.9 (64-bit).

I see that the location I indicated for the AO cache contains JPG files, so AO seems to work correctly.

Maybe you have any other suggestion?

Thanks for your time sofar.
Regards,
Taco

**Comment by marloscaida** [comment]
Taco: At the end I am going to copy a small instruction in Spanish (that you can translate with Google Translator) and that can be useful to see if you can make it work.
I don't understand what is the need to have three Python installations. Are all your applications not compatible with 3.10? If this is so, I would uninstall the older versions.
I had quite a few problems with the AO installation running with an executable and managed to get it to work with the native Python installation.
Another idea is, will you have a problem with the rights of the AutoOrtho folders? Well, here goes the instructions in Spanish.

Instrucciones prácticas para la instalación de AutoOrtho para Windows 10/11.

Muchas personas no pueden usar AutoOrtho porque no han hecho una buena instalación o no han entendido las instrucciones. Este es un intento más de darles una pequeña ayuda para que esta maravillosa aplicación, les funcione adecuadamente y puedan disfrutarla.

Debe asegurarse que su sistema operativo sea la versión de 64 bits
Funciona en X-Plane 11 o 12

Si no tiene una buena máquina, con buena placa de video y discos veloces, ni se moleste en leer el instructivo. AutoOrtho definitivamente no es para usted. Si la tiene, felicitaciones. Siga estos pasos. Si algo no entiende o no se anima a hacer, pídale ayuda algún amigo que sepa un poco más de Windoes y X-Plane.

1.- Obtenga cualquiera de los siguientes productos:

- Dokan
1.1. Descargue e instale la última versión de Dokan aca:
https://github.com/dokan-dev/dokany/tags
Use DokanSetup.exe o Dokan_x64.msi 

- WinFSP
1.2. Descargue e instale la última versión de WinFSP acá:
https://github.com/winfsp/winfsp/tree/v2.0
(Recomendamos bajar el archivo MSI para su instalación)

2.- Haga la instalación de uno de los dos productos de manera estándar o por defecto, sin cambiar nada durante la instalación.

(Si no funciona en su sistema Dokan, desinstálelo e intente con WinFSP.  Debe reiniciar el equipo, cada vez que instale o desinstale)

En mi caso, no me funcionó DOKAN, pero a mis amigos sí. 
Instalé WinFSP y funcionó (no tengo idea cual es la razón). 
Estas librerías sirven para la creación de una carpeta virtual que solo existe mientras funciona AO.

3.- Obtenga la última versión de AutoOrtho acá:

https://github.com/kubilus1/autoortho/tags

Utilice la versión AutoOrtho_win_xxx.zip (instalación manual)

4.- Descompacte el archivo zipeado  en el lugar que usted desee (puede ser en su disco principal, puede ser dentro de la raíz de X-Plane, etc)

5.- Ubique el único archivo ejecutable en la carpeta de AutoOrtho y cree un acceso directo en su escritorio.

6.- Cree una carpeta con un nombre similar a AutoOrthoCache en un disco con buen espacio y velocidad de acceso. Ahí se va a cargar  toda la cache de imágenes necesaria. Esto es muy importante. Capacidad y velocidad de acceso.

7.- Ejecute, desde el acceso directo del escritorio, el AO.  Este proceso lo va a llevar, en primer lugar a la pantalla de configuración que cuenta con dos solapas. En la primera solapa  [SETUP] debe consignar los siguientes datos:

a. La carpeta en donde se encuentra su carpeta de escenarios.  

Normalmente en:
C:\X-Plane 12\Custom Scenery o
C:\Program Files (x86)\Steam\steamapps\common\X-Plane 12 
b. La carpeta donde se van a guardar las imágenes cache que necesita AO y mencionada en el punto 6.

c. La carpeta temporal para la instalación (creo que la trae por defecto). Normalmente se encuentra en:

C:\Users\<Nombre de usuario>\.autoortho-data\downloads

d. La Fuente de las imágenes que va a utilizar (se sugiere utilizar BI que es BING) pero puede intentar con alguna otra.

e. La máxima capacidad que va a contener la carpeta de cache de imágenes mencionada en el punto 6 (se sugiere no menor a 100 Mb). Esto depende de su espacio en disco. Mientras más imágenes pueda guardar la caché, mejor performance va a tener su sistema.

NO SE OLVIDE DE PRESIONAR EL BOTON [SAVE] antes de pasar a la siguiente solapa.

8. Vaya a la solapa [SCENERY] y seleccione el área que va a alojar AutoOrtho. Se sugiere empezar con el continente donde usted vuela normalmente. Esto se hace utilizando el botón [INSTALL].

La instalación de los escenarios de AutoOrtho tarda bastante y depende de la velocidad de acceso a Internet. Sea paciente y espere que termine. 
Por ejemplo, en el caso de South America, son más de 8.700 Mb. de archivos.

Una vez que termine la instalación puede presionar el botón [RUN].

9.- En este punto, se van a generar un mínimo de 3 carpetas en Custom Scenery. Estas son las siguientes:

yAutoOrtho_Overlays
z_autoortho

y una tercera carpeta virtual que va a existir solamente mientras esté en ejecución AO.

Esta carpeta puede tener un nombre como “z_ao_sa” y supongo que si usted usa otro contienen se llamará “z_ao_na” (North America), “z_ao_au” (Australia), etc.
La verdad es que no lo sé ya que tengo instalado un solo escenario.

10.- Este proceso termina cuando usted visualice en la pantalla de ejecución de comandos el mensaje que se han terminado de descargar todos los archivos necesarios (esta pantalla está presente mientras AO se está ejecutando).

11.- Lance X-Plane y espere que termine de cargar, con el avión y aeropuerto de su preferencia. No importa cual. Asegúrese que su aeropuerto esté dentro del continente elegido. No se sorprenda si nota que ya no está ese aeropuerto o le faltan cosas. No es un problema.
Con el simulador abierto, busque y copie en otra carpeta el archivo scenery_pack.ini que se encuentra en la carpeta Custom Scenery  (sugerimos en la carpeta DESCARGAS o DOCUMENTOS). Cierre el simulador, sin cerrar AO.

12.- Edite el archivo scenery_pack.ini,  desde conde lo copio en el punto anterior  (esto lo debe hacer con el bloc de notas). Ubique las líneas:

SCENERY_PACK Custom Scenery/yAutoOrtho_Overlays/
SCENERY_PACK Custom Scenery/z_ao_sa/
SCENERY_PACK Custom Scenery/z_autoortho/

Póngalas, en el mismo orden que figura más arriba pero al final del archivo scenery_pack.ini y guarde los cambios.

Parado sobre el archivo scenery_pack.ini, use el botón derecho del mouse para que aparezca el menú contextual, elija la opción PROPIEDADES del archivo, y marque el casillero de solo lectura. 

La idea es que este archivo, a partir de ahora, no pueda ser accesible para realizar cambios, de ninguna manera, por parte de X-Plane. Solo usted podrá alterarlo para agregar algún escenario.
ESTO ES MUY IMPORTANTE.

Recuerde el orden en que van los escenarios en scenery_pack.ini:

I
1000 Version
SCENERY

Aquí van aplicaciones como SAM:

SCENERY_PACK C:\Program Files (x86)\Steam\steamapps\common\X-Plane 12\Resources\plugins\SAM\lib\SAM_GlobalTrees/
SCENERY_PACK Custom Scenery/SAM_DeveloperPack/

A partir de acá todas las carpetas que contengan escenarios. Por ejemplo:

SCENERY_PACK Custom Scenery/Aerosoft - EDLP Paderborn-Lippstadt/
SCENERY_PACK Custom Scenery/Aerosoft - LFMN Nice Cote d Azur X/

A partir de acá y al final de los escenarios los landmarks:

SCENERY_PACK Custom Scenery/X-Plane Landmarks - Berlin and Frankfurt/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Budapest/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Chicago/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Dubai/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Las Vegas/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - London/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Los Angeles/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - New York/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Paris/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Portland/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Rio De Janeiro/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Saint Louis/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - San Francisco/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Sydney/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Washington DC/

Después los escenarios propios del simulador (ejemplo de X-plane 12:

SCENERY_PACK *GLOBAL_AIRPORTS*

(en X-Plane 11 figura de otra manera)

Luego, todas las librerías necesarias para que funcionen los escenarios personalizados como:

SCENERY_PACK Custom Scenery/ NAPS_library/
SCENERY_PACK Custom Scenery/ OpenSceneryX/

Y finalmente deberían ir las entradas para AO:

SCENERY_PACK Custom Scenery/yAutoOrtho_Overlays/
SCENERY_PACK Custom Scenery/z_ao_sa/
SCENERY_PACK Custom Scenery/z_autoortho/

13.- Copie el archive scenery_pack.ini en la carpeta [CUSTOM SCENER] del simulador. Windows le va a preguntar si quiere que el viejo archivo se sobreescriba con el nuevo. ESTO ES IMPORTANTE. Verifique que scenery_pack.ini sea DE SOLO LECTURA.

14.- Arranque nuevamente el simulador. Le va a aparecer una ventanita con una advertencia, informándole que no puede tener acceso al archivo scenery_pack.ini (eso ya usted lo sabe porque así lo preparamos). 

Si no aparece esta advertencia, comience nuevamente desde el punto 11 de este instructivo.

Si, por el contrario aparece, quiere decir que ha llegado bien hasta este punto. 

Ahora va a tardar un poco más en abrir el simulador, ya que AO está bajando las imágenes y haciendo su trabajo. No se desespere. Tenga paciencia. 

Si su máquina tiene buena capacidad de procesamiento y discos veloces, podrá disfrutar de X-Plane y AO.

Consejo final: Antes de volar de un punto a otro, posicione primero su aeronave en el punto A. Luego, haga lo mismo con el punto B. Una vez finalizado estos procesos, vuele desde A a B.
Tardé toda una mañana en “actualizar” con AO todos mis aeropuertos preferidos. Espero les sea de utilidad.

**Comment by ikatergaris** [comment]
Hello all. I am on windows 11 and I am now using WinFSP (I don't think it matters. Dokan should be the same). I sometimes get the exact error reported here. What I do is this: I leave AO running and wait a couple of minutes. I then click Understood in x-plane which of course shuts down x-plane. I then open x-plane again and load the same flight as before. Most times, it just works. Otherwise I repeat. The most I have repeated is 2 times. So I get the error 2 times. If someone can replicate this, it might be useful for the developers. It might confirm that it's a timeing setting somewhere in the code? I'm just saying... I have no idea how this works. Just presenting my experience with this issue and trying to make some sense.

**Comment by TMV-NL** [comment]
@ikatergaris @marloscaida
So, I spend some testing and following Carlos' instructions. What I noticed:
1) basically the instructions of Carlos did not solve my issues;
2) I found that, sometimes, after a number of tries, it does work with loaded otho. But that takes like 10 or more restarts. In some cases I just gave up
3) In some cases, that seem to be related to the area, I get a large number of download errors, requiring even more restarts

It seems that if the files are not downloaded in time, it triggers this XP error.

So, to use AO, I have to spend quite some time reloading XP in order to download the ortho. That does not make it worthwhile for me. I do hope this will be solved in some future version. Pitty as it realy looks like a promissing tool.

**Comment by Jeff2122** [comment]
@ikatergaris said " I then open x-plane again and load the same flight as before. Most times, it just works. "
Aha! This happened to me a few times now. I have not seen anyone but you so far say this. I don't want to make people upset that they might have to wait longer until it is an actual proven thing, so I just kept it in my notes. I might add that I changed my MAXWAIT to 3.0 seconds and I hardly see the error, nor do I see green tiles that often. Of course it depends on where you are in the world and which data source is selected, xo YMMV.

**Comment by TMV-NL** [comment]
> 

That is interesting, where can I set the MAXWAIT?

**Comment by Jeff2122** [comment]
C:\Users\YOURNAME in the .autoortho file. maxwait = 0.3 change it to 3.0 or greater.

**Comment by TMV-NL** [comment]
@Jeff2122 I tried varried delay settings yet unfortunately it doesn't make a substantial difference in my case.

I'm wondering though what it is that makes XP stumble if the downloads are not done in time and what can be done to make it more stable.

**Comment by Jeff2122** [comment]
Sorry it didn't help. Could be that the data isn't there on the server or it is not being retrieved for some reason. I am still fiddling with it. I have had the retry workaround mentioned above work for me a few times already today. If it fails to load, stop and restart the whole process. I make sure my server is fully restarted and my .ini is straight before I reopen XP as usual. It is a pain in the x, but it is It is worthwhile for now. I can't pinpoint it, I believe Windows is interrupting but don't know how to prove it.
