### ISSUE TITLE
macOS 13.1 Catalina recursion error

### ISSUE THREAD

**Issue by ricardogo** [kubilus1/autoortho#34]
Hey, I'm getting an error running `python3 autoortho` on macOS. I know you haven't tested this in this system yet, happy to help debug & get this running.

The logfile is attached (too long to share here)
[autoortho.log](https://github.com/kubilus1/autoortho/files/10369370/autoortho.log)

Would love getting this running, as I can't run OrthoXP on my Mac either!

**Comment by kubilus1** [comment]
There has been some reported success when using the 'macos' branch.  Eventually I'll probably merge this in, after some cleanup.  

There is the start of a discussion thread here as well:  https://github.com/kubilus1/autoortho/discussions/32

Thanks for the logs!

**Comment by ricardogo** [comment]
Just tried it. Unfortunately, the same error — the "app" never really starts!
