### ISSUE TITLE
Xfinity security reporting a targeted network attack when ever you run auto ortho.

### ISSUE THREAD

**Issue by Awemeter** [kubilus1/autoortho#35]
Is there anything you can do from your side to fix the reporting of a targeted network attack? Xfinity blocks the connection of autoortho causing it to not work.

**Comment by Awemeter** [comment]
The issue has returned blocking me from using autoortho.

**Comment by bad-hubble** [comment]
I am also having this issue with Xfinity. Dokin/AO is being blocked at the router so I cannot fly with AO.

Is it possible to get around this via port forwarding? If so, what ports do I need to open? Thanks.

**Comment by Awemeter** [comment]
I have no idea because I switched isps for this reason 😂

**Comment by bad-hubble** [comment]
Argh. Not a possibility for me, unfortunately. Glad you got a fix.
