### ISSUE TITLE
PreRelease 6.0-1 Scenery Ortho contains many many mis-placed and duplicate tiles connected together

### ISSUE THREAD

**Issue by mvIrony** [kubilus1/autoortho#362]
The scenery produced by this pre-release 6.0-1 contains many duplicate tiles stitched together, sometimes in random numbers .  This issue seems to have to do with cache, when I change the cache directory to cache created by AO v4.4 the scenery displays correctly, changing back to the cache created by AO v6.0-1 the majority of the ortho displayed is as described.  Scenery is not usable.

**To Reproduce** run version 6.0-1 analyze results in gaame.
**Expected behavior** as with version 4.4 which despite it's configuration limitations works perfectly.
**Screenshots**  provided below.

 - OS: [e.g. Windows 11]
 - XPlane Version: 12.06b7
 - AutoOrtho Version 6.0-1 (pre-release w/winFSP)
 - Filesystem type NTFS

EVGA Z690 Dark Kingpin, i9 12900K, 64gb 6000mhz memory, nVidia RTX 4090 FE, 8tb SSD storage

**Comment by mvIrony** [comment]
![DA42 - 2023-09-04 14 48 53](https://github.com/kubilus1/autoortho/assets/69731827/72aaefef-7908-4821-b7e8-0cd67f25cf33)
![DA42 - 2023-09-04 14 48 29](https://github.com/kubilus1/autoortho/assets/69731827/4f8c18f6-d022-40c1-8b8c-42ac06b7ebbe)
![DA42 - 2023-09-04 14 49 06](https://github.com/kubilus1/autoortho/assets/69731827/54d04d76-6167-49be-b518-eecef9a49fe7)

**Comment by ClubbyMcWankfist** [comment]
Having the same issue myself...

**Comment by mvIrony** [comment]
> Having the same issue myself...

Yeah, why do I have the feeling that it is only us? I have tried every possible configuration and Dokan vs winFSP to no avail.

**Comment by Jeff2122** [comment]
It isn't just you all having this issue. It is being discussed on the Org forum as well. I have been experimenting and I get much less of this "plaid" scenery if I use AO v0.4.4. 
I have been viewing the Bing map for the location of interest to check their data at various zoom levels. I have noted this plaid scenery is visible online at some zoom levels as well.
I am starting to believe this is related to some changes that were made in the download process in v0.6.x.

**Comment by mvIrony** [comment]
Thanks, as above in my original issue submission I always revert back to v4.4. I have not looked extensively but do not remember any case of your most accurate description of "plaid scenery". 
I think I remember pointing v4.4 to cache generated in v6x and it displayed properly. Thus some problem in tile assembly.
Since it is so time consuming to switch back and forth I believe I will remain on v4 until v6 is demonstratively repaired.
It is just that I had not seen any evidence of others having an issue until you kindly commented.
Regards ...

**Comment by Jeff2122** [comment]
Yeah, it's becoming a common complaint actually, from what I'm seeing. And now that they pointed it out, I see it too much to be happy so I, too, have reverted to v0.4.4 for now to watch things. 
Try this to catch up with others having the issue. There are also others if you go one level up.

"https://forums.x-plane.org/index.php?/forums/topic/259020-autoortho-streaming-ortho-imagery-for-x-plane-12-and-11/&page=47#comments"
