### ISSUE TITLE
X-Plane 12.06r1 destroys the scenery_pack.ini

### ISSUE THREAD

**Issue by marloscaida** [kubilus1/autoortho#367]
Kubilus1:

When x-plane starts (using AO version 0.6.1) it alters the location of the line:

  SCENERY_PACK Custom Scenery/z_ao_sa/

and puts it at the beginning of the file, removing it from the end.

I think the only way is to leave that folder with the functionality of a library (I don't know what it should contain so that XP believes that it is a library and that happens).

XP puts that line (before it removed it) detecting that it is a scenery and not a library at the beginning. As a consequence, ALL custom scenery disappears.

I hope this is useful to you.

regards
carlos

**Comment by chezhj** [comment]
This is how I work around this issue https://github.com/kubilus1/autoortho/discussions/395
