### ISSUE TITLE
Autoortho 0.6.0.1 Error Loading the scenery package : Custom Scenery/z_aus_pac/ Still Exists

### ISSUE THREAD

**Issue by SimOld73** [kubilus1/autoortho#368]
I have tried version 0.5.1.3 and 0.6.01 and I get the error Loading the scenery package: Custom Scenery/z_aus_pac/.  In both version I have tried Dokan and WinFSP and I still get the error with X-Plane 12 shutting down.  I have been able to get autoortho to load and X-Plane 12 to run if I change the Debug Mode in the .autoortho file from False to True.

**Comment by Jeff2122** [comment]
Seems like a timing or race condition is changed/fixed by extra work in debug mode. (?) I just can't understand how it is helping here yet. It makes sense internally in a compiled program to adjust delays to make things work. But adjusting timing on AO by putting it in debug mode? Perhaps this tidbit will help the dev see an issue in the code.

**Comment by zippy77777** [comment]
> I have tried version 0.5.1.3 and 0.6.01 and I get the error Loading the scenery package: Custom Scenery/z_aus_pac/. In both version I have tried Dokan and WinFSP and I still get the error with X-Plane 12 shutting down. I have been able to get autoortho to load and X-Plane 12 to run if I change the Debug Mode in the .autoortho file from False to True.

where do you find debug mode?????????

**Comment by SimOld73** [comment]
The Debug mode is in the .autoortho file which is located C:\users\Your computer name

**Comment by zippy77777** [comment]
I don't see anything at all there relating to debug?

**Comment by zippy77777** [comment]
I just cannot get autoortho working, it's just crashed constantly, all day I have tried.

**Comment by SimOld73** [comment]
It is not in the .autoortho-data folder is in the .autoortho cfg file.  You have to open it in notepad see the following text.

[general]
# use gui config at startup
gui = True
# show config setup at startup everytime
showconfig = True
# hide when running
hide = True
# debug mode
debug = True

[paths]
# x-plane custom scenery path
scenery_path = H:/X-Plane 12/Custom Scenery
# directory where satellite images are cached
cache_dir = H:/.autoortho-data/cache
# changing downloader_dir is currently not supported
download_dir = C:\Users\ddash\.autoortho-data\downloads
# changing log_file dir is currently not supported
log_file = C:\Users\ddash\.autoortho-data\logs\autoortho.log

[autoortho]
# override map type with a different source
maptype_override = BI
# minimum zoom level to allow.  this will not increase the max quality of satellite imagery
min_zoom = 12
# max time to wait for images.  higher numbers mean better quality, but more
# stutters.  lower numbers will be more responsive at the expense of
# ocassional low quality tiles.
maxwait = 0.5

[pydds]
# ispc or stb for dds file compression
compressor = ISPC
# bc1 or bc3 for dxt1 or dxt5 respectively
format = BC1

[scenery]
# don't cleanup downloads
noclean = False

[fuse]
# enable or disable multi-threading when using fuse
threading = True

[winfsp]
# enable windows to use winfsp mode instead of fuse mode.  this is not typically recommended
winfsp_raw = False

[flightdata]
# local port for map and stats
webui_port = 5000
# udp port xplane listens on
xplane_udp_port = 49000

**Comment by SimOld73** [comment]
On my computer the file is C:\Users\ddash\.autoortho

**Comment by zippy77777** [comment]
![image](https://github.com/kubilus1/autoortho/assets/33657120/1719d3cb-722c-49e3-9698-d06e6dad7268)

**Comment by zippy77777** [comment]
![image](https://github.com/kubilus1/autoortho/assets/33657120/9cc580cf-1280-4423-bb7b-374f6bd1eeb7)

**Comment by zippy77777** [comment]
I don't have that file!

**Comment by zippy77777** [comment]
where is this .cfg file you talk about???

**Comment by zippy77777** [comment]
> On my computer the file is C:\Users\ddash\ .autoortho

what is ddash?

**Comment by Jeff2122** [comment]
.autoortho file is located in C:\Users\YOURUSERNAME\

ddash is his username.

**Comment by Ichnusa66** [comment]
I don't know if my contribution can be useful....I solved the problem by uninstalling Dokan, clearing the Auto Ortho cache and installing WinSfp
