### ISSUE TITLE
No ortho loaded for  my co pilot and I so its just stars for ground.

### ISSUE THREAD

**Issue by Awemeter** [kubilus1/autoortho#37]
I am currently over PONCT in USA and my first officer and I both just see stars instead of ground/

**Comment by Awemeter** [comment]
It happened again now over SLOWR.

**Comment by Awemeter** [comment]
[Log.txt](https://github.com/kubilus1/autoortho/files/10462839/Log.txt)
here is my log

**Comment by kubilus1** [comment]
Thanks for the info on this.  I'm working on some changes to scenery
generation.

**Comment by Awemeter** [comment]
Thanks for the fast reply. I am looking forward to the update. For now, I am just going to remove it so I can focus on flying and not the stars on the ground.

**Comment by Awemeter** [comment]
Still not fixed with the most recent update
