### ISSUE TITLE
Zooming creates visual bugs

### ISSUE THREAD

**Issue by thewalkingfruit** [kubilus1/autoortho#372]
Bug started on existing autoortho install, by getting errors that the scenery was not usable by xplane. To be clear this was after updating to xplane 12.06r1 from 12.06b7, when i did get it to work zooming into the ground with the camera or being at low altitude prompted these weird looking tiles with repetition all over them (screenshot attached while not zoomed in too), seems like its a radius around the camera that is created with that weird look. 

Tried to fix with uninstalling winfsp and installing dokan, which didnt let me start the sim at all, installing the newer version (0.6.0) of ao, reinstalling winfsp, and also reinstalling the scenery itself

 - OS: Windows 10
 - XPlane Version: XP12.06r1
 - AutoOrtho Version 0.5.1 (later updated to 0.6.0 with same issue)
 - Filesystem type NTFS
 
![Screenshot (180)](https://github.com/kubilus1/autoortho/assets/104994445/7b5d7f19-468c-4d65-8cef-5adc172ed06d)
![Screenshot (179)](https://github.com/kubilus1/autoortho/assets/104994445/611bdde2-5d10-4f27-83b0-635c55e13ffd)

![Screenshot (181)](https://github.com/kubilus1/autoortho/assets/104994445/191df415-502a-4ab1-95d2-92c7aa65ea1c)

**Comment by crazyforiphone** [comment]
I had the same issue, just forced it to BI for the map source instead of leaving it empty which seemed to have helped.

**Comment by thewalkingfruit** [comment]
> I had the same issue, just forced it to BI for the map source instead of leaving it empty which seemed to have helped.

Thanks for the suggestion, I tried this and unfortunately I'm still getting the visual bugs

**Comment by Jeff2122** [comment]
I got that today when I tried to use WinFSP in place of Dokan. Went back to Dokan.

**Comment by voteblake** [comment]
I'm using and have only ever used Dokan and I am seeing this. My map type override is empty, not set to BI, but I only have BI maps downloaded in my cache. Happy to dig up any more information to help troubleshoot.

**Comment by thewalkingfruit** [comment]
> Do you see the terrain change as you zoom in and out? I do. That is ortho adjusting to different levels of detail I think. Higher looks better, less pixelated. Go low and it looks pretty course. I can see it morph as I zoom. Can someone put this into better words? Ortho experts?

I understand what you mean but if you look at the screenshots attached this is not how ao without any issues looks like, there clearly is something wrong either with my install or with something in ao/xplane. I've used ao since many versions ago and this was never how it looked at low altitudes, only now in the latest version 12.06r1 has this started

**Comment by Jeff2122** [comment]
There are other comments here and on the org about this. Maybe it relates to the green tiles? Whatever it is, I think I've seen it on and off too, but I've shrugged it off because I know that the data varies from location to location in the world, and from data source to data source. You could try another data source, or get custom Ortho for that area. We'll keep watch and if there are any revelations, we'll hear about them.

**Comment by thewalkingfruit** [comment]
> There are other comments here and on the org about this. Maybe it relates to the green tiles? Whatever it is, I think I've seen it on and off too, but I've shrugged it off because I know that the data varies from location to location in the world, and from data source to data source. You could try another data source, or get custom Ortho for that area. We'll keep watch and if there are any revelations, we'll hear about them.

At this time I've switched to Bing and noticed that it does reduce the bug a bit, but it's definitely still there, I will try other providers when I get the time and if I get to a result will let people know

**Comment by Jeff2122** [comment]
Good deal. My notes show this current status from my location in U.S.:
Default - pretty good most places in the world I've tried, Eastern Europe suffers though.
BI - same as above (pretty sure default is BI anyway, I never see tiles marked any different from "bi")
EOX - works some places in EU where BI is scant, can see some green tiles many places
Firefly - works in the NW of US some places but not really worth the time to try it.
USGS - usually just produces streams of bad connections, works some places in CONUS, no map so not worth the time.

I have not tested extensively, only trial and error but the above is what I go by for now. Sorry but it isn't too helpful.

**Comment by thewalkingfruit** [comment]
> Good deal. My notes show this current status from my location in U.S.: Default - pretty good most places in the world I've tried, Eastern Europe suffers though. BI - same as above (pretty sure default is BI anyway, I never see tiles marked any different from "bi") EOX - works some places in EU where BI is scant, can see some green tiles many places Firefly - works in the NW of US some places but not really worth the time to try it. USGS - usually just produces streams of bad connections, works some places in CONUS, no map so not worth the time.
> 
> I have not tested extensively, only trial and error but the above is what I go by for now. Sorry but it isn't too helpful.

It's actually very helpful, it lets me know not to waste my time testing other providers, because from what I see too most of them come from Bing either way, hopefully this can be solved soon

**Comment by Jeff2122** [comment]
I think I might delve into these data sources. I have no understanding of who stores what where, nor how much data is available. Seems like it might be more than I need to know though. Curiosity is all it is really.

**Comment by met4leye** [comment]
I have the same issue, anyone got a fix? Source is set to Bing:/

**Comment by Jeff2122** [comment]
Yesterday I started getting the strange tiles as shown at the top of this thread. I switched from Dokan to WinFSP and problem isgone. I cannot explain why Dokan always worked for me until yesterday.

**Comment by thewalkingfruit** [comment]
> Reverted to 0.5.1 and it fixed it. Its not caused by the XP beta!

Thanks for letting us know your fix, I'll try that shortly after I land from my flight. For me it started on 0.6.0 full release so beta causing it didn't cross my mind

**Comment by Jeff2122** [comment]
Nothing has changed. The issue still remains with the latest version and is not apparent in v0.5.1-3 or previous builds.

**Comment by Jeff2122** [comment]
Don't close please. This issue remains in any version starting with v0.6.0. Plaid scenery is what it has been called, and it goes away with a second load of the scene. Not acceptable for those who don't fly the same routes all the time.

**Comment by Jeff2122** [comment]
Bad plaid tiles continue with latest version v0.6.x and above. Also there has been lots of stuttering with all version. Not sure why, tried both Dokan and WinFSP, changed maxwait, nothing seems to eliminate stutters while using AO.

**Comment by AlbertoA340** [comment]
I have the same problem!
Pixeled terrain texture at low altitude but nice texture going up !
There is any solution?
Please help!
