### ISSUE TITLE
The app won't open up

### ISSUE THREAD

**Issue by maxl-daxl** [kubilus1/autoortho#374]
With every autoortho version I install I have the problem that autoortho closes itself after 0,1 seconds after I open it up. I have tried several things like installing older versions, tried the setup and the zip files. I even tried dokan and winfsp but nothing worked out. It would be very nice if somebody could help me with this.

This would be a video showcasing the problem
https://github.com/kubilus1/autoortho/assets/141307853/abcd67f7-27ce-42d8-9ba3-015f6b609497

Mayby someone has an idea what to do.
Thanks

Windows:10
Xplane Version: 12.06
Auto Ortho Version: all
File system type NTFS

**Comment by thewalkingfruit** [comment]
Run the app as administrator, it might be your antivirus closing it down

**Comment by pntrafewl** [comment]
Had a similar issue a little while ago that stopped when I went to the
install directory and doubly clicked the auto ortho exe.

**Comment by pntrafewl** [comment]
This was on the 0.6.1 version, the one with the sweet installer.

**Comment by Jeff2122** [comment]
What did you change? Inquiring minds wanna know...

**Comment by maxl-daxl** [comment]
![Screenshot 2023-09-04 185752](https://github.com/kubilus1/autoortho/assets/141307853/f7dc5e86-7536-4bcc-aa53-b6bc7abbbdce)
Changed the yellow marked from False to True and this let the app opne up

**Comment by Jeff2122** [comment]
Oh gee, makes sense now.

**Comment by rickyelysion** [comment]
Autoortho 7.2 not starting up properly. I my case i had changed some drives including drive letters  in my machine and it seems to cause the problem.  I know the folder with the cache was in drive Z: which no longer exist but was still referenced in the config file. 

cache_dir = Z:/AutoOrtho_cache
I  just renamed my .autoortho in the c:/users/"username"/ folder and the program started with the cache folder setting missing.

X-Plane 12.0.9-rc-5 Windows 11 Home Ryzen 5 3600 32 Gig Ram NVIDIA GeForce RTX 3070

**Comment by Jeff2122** [comment]
Yeah if/when this happens the first thing to do is delete the old .autoortho file and force AO to create a new one. Of course, you must reconfig and save the config again each time. No big deal really.
