### ISSUE TITLE
"ERRORS: No installed scenery detcted WILL EXIT DUE TO ERRORS"

### ISSUE THREAD

**Issue by willjrsendo** [kubilus1/autoortho#375]
I just installed the AO v0.5.1, then I was just changing the directories (from C drive to D drive) but when I clicked save, it crashed. Now the app won't restart. It gives an error "ERRORS: No installed scenery detcted WILL EXIT DUE TO ERRORS". Tried downloading the latest v0.6.1, but for some reason the problem was carried over. 

![Capture](https://github.com/kubilus1/autoortho/assets/40930527/1ded6e33-f33b-4278-9836-81ca778f92c0)

**Comment by chezhj** [comment]
As far as I understand the python files, it can't find installed scenery in "Custom Scenery\z_autoortho\scenery"
in .autoortho (in your user directory) make sure 
# use gui config at startup
gui = True
# show config setup at startup everytime
showconfig = True
You should be able to change directories and reinstall. 
Doesn't fix the code, but hope it helps you along

**Comment by willjrsendo** [comment]
> As far as I understand the python files, it can't find installed scenery in "Custom Scenery\z_autoortho\scenery" in .autoortho (in your user directory) make sure
> 
> ```
> # use gui config at startup
> gui = True
> # show config setup at startup everytime
> showconfig = True
> ```
> 
> You should be able to change directories and reinstall. Doesn't fix the code, but hope it helps you along

Thanks, that has fixed it. I just opened the .autoortho file with wordpad and changed the aforementioned lines. 
![image](https://github.com/kubilus1/autoortho/assets/40930527/db100d77-cfcb-4a34-9c20-712e54e3e251)

**Comment by arturojgt** [comment]
Thank you.
