### ISSUE TITLE
xplane 12 cant run with this scenery package installed, (North America)

### ISSUE THREAD

**Issue by dillan4561** [kubilus1/autoortho#377]
everything in my scenery.ini is fine, but when i run xplane and load into an airport in the USA i get this error

Log is attached...
[Log.txt](https://github.com/kubilus1/autoortho/files/12515718/Log.txt)

![image](https://github.com/kubilus1/autoortho/assets/35738129/799a0395-8e69-4d2f-9e00-ae3bef5a9cd3)

**Comment by SimOld73** [comment]
Some People have fixed this by switching from Dokan to winFP.  I was able to fix the problem by changing the Debug Mode from False to True in the .autoortho configuration file see my entry in #369

**Comment by dillan4561** [comment]
i will try this, thanks

**Comment by Jeff2122** [comment]
Another data point: I sometimes see this same crash, and just restart XP12 to try again, and it loads the flight. This has happened several times during my testing of both v0.5.1-3 and v0.6.x. 
I have not put my finger on the exact cause, but I suspect a file is not present in the cache for whatever reason, maybe the server did not cough it up when requested, and XP gives up.
