### ISSUE TITLE
Autoortho 0.4.4 and xOrganizer will allow X-Plane to run with or without running Autoortho

### ISSUE THREAD

**Issue by SimOld73** [kubilus1/autoortho#379]
Version 0.4.4 by itself would not allow XP to run unless autoortho was running.  Version 0.5.1.3 & 0.6.0.1 intended to fix this problem but created other problems.  These version use mount point folders as place holders for the scenery packages.  When autoortho is running these mount points show scenery package folder which are then written to the scenery_packs file.  When it is not running the mount points are blank which allows XP to run.  The problem is since they are blank XP deletes the scenery packages in the scenery_packs file.  Then the next time autoortho is ran it reinstalls them at the top of the scenery_packs file where they then have to be moved to the proper location.  People have been making the scenery_packs file read only to prevent this which causes a write error message to show up when XP is ran.
Using version 0.4.4 and xOrganizer you don't have to make the scenery_packs file read only.  After installing 0.4.4 if you run xOrganizer with the Scenery tab at the top on it will update the scenery_packs file putting the autoortho scenery in the proper location.  If you then want to run XP without autoortho run xOrginizer and uncheck the autoortho scenery to disable it.  In the scenery_packs file you will see that these are disabled which allows XP to run without autoortho. When you want to run autoortho re-enable the scenery in xOrganizer and the scenery will now be active.
You can also use xOrganizer with versions 0.5.1.3 & 0.6.0.1 instead of making the scenery_packs file read only.  When you start and run autoortho then run xOrganizer before starting XP.  XOrganizer will see the scenery package in the custion scenery folder and put them in the scenery_packs file in the proper location.
xOrganizer is presently listed for $15.00

**Comment by chezhj** [comment]
Running 6.1 myself, didn't try xorganizer yet, but found that the junctions that autoortho makes during run are indeed handles differently by xp.
Now I start xp, it will handle the replacement links fine, start autoortho, then start a flight.
After the flight, close autoortho first, than close xplane.
I think xplane will handles the junctions better if they are a child in a scenery dir
For example ao_reg\z_ao_eur

**Comment by SimOld73** [comment]
Closed Issue
