### ISSUE TITLE
All terrain at EKVG removed with autoortho installed.

### ISSUE THREAD

**Issue by Awemeter** [kubilus1/autoortho#38]
EKVG is a very mountainous and dangerous airport but with the ortho installed it becomes flat and has zero mountains around it.

**Comment by kubilus1** [comment]
Yeah, confirming this.  This is almost certainly some kind of issue with Ortho4XP.  https://github.com/oscarpilote/Ortho4XP

**Comment by Awemeter** [comment]
Ah ok I'll make a issue there.

**Comment by kubilus1** [comment]
Thanks! I'll try to recreate just those areas and see if any warnings
standout

**Comment by Yuriala12** [comment]
As of May the 25th this issue still persists
