### ISSUE TITLE
Directory seems wierd... Are you sure the install directory needs to be set to Custom Scenery, or where the X-Plane executable is?

### ISSUE THREAD

**Issue by bhilldev** [kubilus1/autoortho#383]
"C:/Program Files (x86)/Steam/steamapps/common/X-Plane 12/Custom Scenery" seems wrong, will exit due to errors."

**Comment by Jeff2122** [comment]
This message is warning you because it is not a standard place you are putting your data. Standard would be 
C:\X-Plane 12\Custom Scenery 
I get this message because my XP lives on drive G: and my data is on drive D:. Just press OK and it works fine.

**Comment by bhilldev** [comment]
Except it closes when I press OK. Does it still run for you?

**Comment by Jeff2122** [comment]
Yes, it does continue working fine. So maybe look at your .autoortho file - perhaps delete it and start AO to create a new one. Then be careful where you point it.
I do not use Steam so maybe there is something there in the Steam setup that it doesn't like.  
As I said, that is just warning you that it does not agree with your locations. Make sure they are correct and it should play.
I hope some Steam user can reply if they've seen this problem.

**Comment by bhilldev** [comment]
The website says that the XI tried deleting all the files, reinstalling, AutoOrtho. My current "Setup" page is: 

Scenery install dir: C:/Program Files (x86)/Steam/steamapps/common/X-Plane 12/Custom Scenery
X-Plane install dir: C:/Program Files (x86)/Steam/steamapps/common/X-Plane 12/Custom Scenery

Still get the same error. 

Does it need to be:
X-Plane install dir: C:/Program Files (x86)/Steam/steamapps/common/X-Plane 12

Does the website instruction page need to be updated to reflect 0.6.0-1? 

There was no "X-Plane install dir:" box in the older versions.

**Comment by Jeff2122** [comment]
Please check out this tutorial and skim thru what you know. Maybe a tidbit will help you. Sorry.

https://forums.x-plane.org/index.php?/forums/topic/293308-autoortho-installation-tutorial/#comments
