### ISSUE TITLE
AO Crashing Desktop after Overlay verification

### ISSUE THREAD

**Issue by c777alpha** [kubilus1/autoortho#384]
Greetings.

This past weekend I have been having problems with AO ....when I went to uninstall AO and do some updates on XP12 , AO completely Uninstalled my complete XP12!
 
I spent the whole weekend re-installing XP12 and all my plugins aircraft , etc.

When I re-installed AO and started downloading  the (NA) North America scenery  everything was fine,  the zip files downloaded and when it came time for the files to be verified (overlays) AO was verifying, however when AO finished verifying  AO CTD( crashed my desktop) and the 'Blue" screen would come up.

  I tried re-stalling the NA North America scenery 5 times and the same thing happed  ALL 5 times......last night I tried to reinstall AO SA( South America) snenery and it worked fine and is installed

....however when I tried to install ER( Europe) AO CTD just like North America ( the zip files downloaded fine , when overlay verification process completed it CTD after the last overlay  is verified).......I have attached a few scrren shot othe messgaes I recieved....please advise

**To Reproduce**

**Expected behavior**

**Screenshots**

**(please complete the following information):**
 - OS: Windows 10
 - XPlane Version: 12.06r3
 - AutoOrtho Version 6.0.1
 - Filesystem type (NTFS, exFAT, etc)

**Additional context**
![ao](https://github.com/kubilus1/autoortho/assets/138440465/48c71a60-9ff1-457c-bfcc-ad3893ec770c)
![ao2](https://github.com/kubilus1/autoortho/assets/138440465/21d5df14-248c-45ba-9ba6-a99109abe85e)
[autoortho.log](https://github.com/kubilus1/autoortho/files/12579812/autoortho.log)

**Comment by c777alpha** [comment]
Here is the AUTO ORTHO log ....after verify #7  out of 13  the verfication CTD


[autoortho2.log](https://github.com/kubilus1/autoortho/files/12580049/autoortho2.log)

**Comment by Jeff2122** [comment]
It doesn't look like ao_na installed all the way. I saw somebody somewhere say they had better luck when they started the download and left the PC alone to finish. Are you multitasking when you are installing? If so, please try again but you might clean up the .jsons and delete the folders, reinstall AO, and only try to download one continent at a time then walk away. Not sure from the log if you attempted to do more than one continent at once or not. 
The only other thing I can think of is file permissions but it isn't likely. Make sure you have enough space, etc.

**Comment by c777alpha** [comment]
Thank you for replying....I do have plenty of space on my ssd....I did try  installing 1 continent at a time and I did leave the computer running and didn't bother it...... it seems that after NA finished installing the zip file's and starts verifying  the lastoverlay  is when it crashes.
How do I edit the .json file?
It's more profitable to listen than talk

Never squander the treasures of your words! 
 
  On Mon, Sep 11, 2023 at 4:12 PM, ***@***.***> wrote:   


It doesn't look like ao_na installed all the way. I saw somebody somewhere say they had better luck when they started the download and left the PC alone to finish. Are you multitasking when you are installing? If so, please try again but you might clean up the .jsons and delete the folders, reinstall AO, and only try to download one continent at a time then walk away. Not sure from the log if you attempted to do more than one continent at once or not.
The only other thing I can think of is file permissions but it isn't likely. Make sure you have enough space, etc.

**Comment by Jeff2122** [comment]
You shouldn't edit the json. Remove it and let AO replace it. 
Cleaning up AO can be messy, so I just delete all of its folders and start over. Yes, it uses lots of data every time.
You can delete the folders AO makes and start over if you have AO installed correctly using Administrator rights. And run AO as admin.

**Comment by c777alpha** [comment]
Thank you for respone.....I remove all AO folder last nigt..........Question:  Should I run AO from  .ZIP  or .EXE file ?




It's more profitable to listen than talk!
Never squander the treasures of your words! 

    On Tuesday, September 12, 2023 at 06:05:03 AM MST, Jeff2122 ***@***.***> wrote:  
 
 


You shouldn't edit the json. Remove it and let AO replace it.
Cleaning up AO can be messy, so I just delete all of its folders and start over. Yes, it uses lots of data every time.
You can delete the folders AO makes and start over if you have AO installed correctly using Administrator rights. And run AO as admin.

**Comment by Jeff2122** [comment]
If you have Python installed, the zip will run. But anyone can use the .exe version as the required Python code is embedded. 
Important: Run both the installer and autoortho.exe as administrator. 
Point the installer to wherever you want the AO program to install. Then it is a different path for the AO data download. And a different path yet for your cache folder.

**Comment by c777alpha** [comment]
I tried to do a re-installed just as you advised and I still keep getting the "blue" screen when the the overlays are being verified....I tried AO 6.0.1 and I even tried 5.1.3  and still the same thing( crash when overlays are being verified)  I attached log from 6.0.1 and 5.1.3 to see if you find anything wrong in the logs 



It's more profitable to listen than talk!
Never squander the treasures of your words! 

    On Wednesday, September 13, 2023 at 06:34:38 AM MST, Jeff2122 ***@***.***> wrote:  
 
 


If you have Python installed, the zip will run. But anyone can use the .exe version as the required Python code is embedded.
Important: Run both the installer and autoortho.exe as administrator.
Point the installer to wherever you want the AO program to install. Then it is a different path for the AO data download. And a different path yet for your cache folder.

**Comment by Jeff2122** [comment]
Is this a Blue Screen of Death (BSOD) you are getting?

My CPU becomes very active during the scenery download/unpack/install process. It is probably best not to multi-task during the install process. Start it and walk away. I don't practice what I preach though, I am typing this even as na is installing. LOL

I wonder if there isn't something about your PC environment that is at play here. That sounds like something Captain Obvious would say. But there could be something to do with your hardware causing the BSOD. Or maybe even just credentials and security settings on folders are preventing the auto unpacking for some reason. I would look at folders and add "Everyone" with full permissions on all affected folders.

**Comment by Jeff2122** [comment]
I am going to mention that I have a functional programming environment on my PC, including Python, Cygwin and Microsoft compilers because I am refreshing my programming skills. While it shouldn't matter at all with the executable version, I also run from the source code depending on my mood. The two methods work identically. I asked the dev about this and he said it does not matter as the exec has all the code built in. I have no doubt he is correct, but it is worth considering. When I do testing for others I use the .exe version just in case it might matter.

**Comment by c777alpha** [comment]
Thank you for response....here is an update:  Last night  I tried to use WINFSP instead of Dokan to install AO  and when it didn't work I removed all AO info and uninstall  AO  when I tried uninstalling AO it completely uninstalled my C drive and Windows operating system  and I lost soooooo much info....as of this email I have been trying to restore my C drive and all info.....something is terribly wrong with installing and uninstalling AO.....just giving you and update



It's more profitable to listen than talk!
Never squander the treasures of your words! 

    On Thursday, September 14, 2023 at 10:37:22 AM PDT, Jeff2122 ***@***.***> wrote:  
 
 


I am going to mention that I have a functional programming environment on my PC, including Python, Cygwin and Microsoft compilers because I am refreshing my programming skills. While it shouldn't matter at all with the executable version, I also run from the source code depending on my mood. The two methods work identically. I asked the dev about this and he said it does not matter as the exec has all the code built in. I have no doubt he is correct, but it is worth considering. When I do testing for others I use the .exe version just in case it might matter.

**Comment by Jeff2122** [comment]
Ouch. I am sorry to hear this. 
Did you install AO in your C:\ root directory? 
I made the mistake once of installing AO directly to my XP11 folder, and it uninstalled XP11 on me. In my case I was planning to remove XP11 anyway so it was no harm done.
I have noticed that if you install v0.6 over another version, it overwrites the Windows record of the previous version. So uninstalling the previous version cannot be done cleanly, it leaves remnants in your registry that you have to remove manually. I think it is the Windows installer doing this. Have not reported it yet.

**Comment by c777alpha** [comment]
I have finally got my operating system back up and running....I tried to install AO and it did the same thing( blue Screen) when AO was verifying the overlays ( it stops around  overlay 6 or 7) ....I did notice after the crash in my scenery file there is AO  Z and Y folders in scenery file.......Any Ideas on how I can get AO on my system?.....Can you do a virtual takeover of my system so you can see what going on for yourself?   please advise...thanks




It's more profitable to listen than talk!
Never squander the treasures of your words! 

    On Friday, September 15, 2023 at 05:32:57 AM PDT, Jeff2122 ***@***.***> wrote:  
 
 


Ouch. I am sorry to hear this.
Did you install AO in your C:\ root directory?
I made the mistake once of installing AO directly to my XP11 folder, and it uninstalled XP11 on me. In my case I was planning to remove XP11 anyway so it was no harm done.
I have noticed that if you install v0.6 over another version, it overwrites the Windows record of the previous version. So uninstalling the previous version cannot be done cleanly, it leaves remnants in your registry that you have to remove manually. I think it is the Windows installer doing this. Have not reported it yet.

**Comment by c777alpha** [comment]
Where is the registry at in windows so I can try and clean any remnants of AO ? (give me pathway please)




It's more profitable to listen than talk!
Never squander the treasures of your words! 

    On Friday, September 15, 2023 at 11:49:05 AM PDT, Christian Hartwell ***@***.***> wrote:  
 
 I have finally got my operating system back up and running....I tried to install AO and it did the same thing( blue Screen) when AO was verifying the overlays ( it stops around  overlay 6 or 7) ....I did notice after the crash in my scenery file there is AO  Z and Y folders in scenery file.......Any Ideas on how I can get AO on my system?.....Can you do a virtual takeover of my system so you can see what going on for yourself?   please advise...thanks




It's more profitable to listen than talk!
Never squander the treasures of your words! 

    On Friday, September 15, 2023 at 05:32:57 AM PDT, Jeff2122 ***@***.***> wrote:  
 
 


Ouch. I am sorry to hear this.
Did you install AO in your C:\ root directory?
I made the mistake once of installing AO directly to my XP11 folder, and it uninstalled XP11 on me. In my case I was planning to remove XP11 anyway so it was no harm done.
I have noticed that if you install v0.6 over another version, it overwrites the Windows record of the previous version. So uninstalling the previous version cannot be done cleanly, it leaves remnants in your registry that you have to remove manually. I think it is the Windows installer doing this. Have not reported it yet.

**Comment by Jeff2122** [comment]
Please don't mess with your registry if you don't know what you are doing. Just because I said that there are remnants doesn't mean you need to worry about it. The remnants are not hurting anything - I am just anal about keeping my system clean. And I have crashed Windows and had to restore it so please don't do that on my account.
I can't link up remotely. I think the best answer is that you have to work it out over time. File management skills and Windows troubleshooting skills are something I don't know how to pass along to another. I just do it, winging it usually.  
Something is going on with your Windows.  Or maybe you can get a local friend to come over and help. I would recommend Geek Squad but I never recommend Geek Squad for anything.

**Comment by chezhj** [comment]
@c777alpha if you are on discord I'm willing to give it a try, when schedules match

**Comment by c777alpha** [comment]
Thank you I would definitely take you on that!! I have had some major issues and blue screens and other issues..lets set up a time 




It's more profitable to listen than talk!
Never squander the treasures of your words! 

    On Tuesday, September 19, 2023 at 02:19:47 PM PDT, chezhj ***@***.***> wrote:  
 
 


@c777alpha if you are on discord I'm willing to give it a try, when schedules match

**Comment by chezhj** [comment]
Are you on a discord server were we can meet? Or if you share your username, I will try to find you

**Comment by c777alpha** [comment]
Join the 777alpha's server Discord Server!


| 
| 
|  | 
Join the 777alpha's server Discord Server!

Check out the 777alpha's server community on Discord - hang out with 13 other members and enjoy free voice and t...
 |

 |

 |








It's more profitable to listen than talk!
Never squander the treasures of your words! 

    On Wednesday, September 20, 2023 at 10:54:42 AM PDT, chezhj ***@***.***> wrote:  
 
 


Are you on a discord server were we can meet? Or if you share your username, I will try to find you

**Comment by chezhj** [comment]
I need a link to join

**Comment by c777alpha** [comment]
https://discord.gg/3xvgFJ3G
It's more profitable to listen than talk

Never squander the treasures of your words! 
 
  On Thu, Sep 21, 2023 at 1:42 PM, ***@***.***> wrote:   


I need a link to join

**Comment by c777alpha** [comment]
Join the 777alpha's server Discord Server!


| 
| 
|  | 
Join the 777alpha's server Discord Server!

Check out the 777alpha's server community on Discord - hang out with 13 other members and enjoy free voice and t...
 |

 |

 |







It's more profitable to listen than talk!
Never squander the treasures of your words! 

    On Thursday, September 21, 2023 at 01:42:22 PM PDT, chezhj ***@***.***> wrote:  
 
 


I need a link to join

**Comment by c777alpha** [comment]
Join the 777alpha's server Discord Server!


| 
| 
|  | 
Join the 777alpha's server Discord Server!

Check out the 777alpha's server community on Discord - hang out with 13 other members and enjoy free voice and t...
 |

 |

 |








It's more profitable to listen than talk!
Never squander the treasures of your words! 

    On Thursday, September 21, 2023 at 01:42:22 PM PDT, chezhj ***@***.***> wrote:  
 
 


I need a link to join

**Comment by c777alpha** [comment]
Greetings,
AO is still causing Blue Screen when Verifying the zip files after downloading all the Zip files for NA( North America)....After
I completely wiped cleaned my hard drive (SSD) and reinstalled Windows 10 Pro and installed DOKAN and AO 0.6.0-1........I reinstalled AO and AO ONLY causes BSOD when verifying the zip files.....I have talked to multiple people and they told me that when I wiped my SDD clean and did the reinstall of Window it "Cleaned" my registry file so there must be something in the AO program that is messing up....if anyone has any Ideas please advise

**Comment by c777alpha** [comment]
Greetings,AO is still causing Blue Screen when Verifying the zip files after downloading all the Zip files for NA( North America)....AfterI completely wiped cleaned my hard drive (SSD) and reinstalled Windows 10 Pro and installed DOKAN and AO 0.6.0-1........I reinstalled AO and AO ONLY causes BSOD when verifying the zip files.....I have talked to multiple people and they told me that when I wiped my SDD clean and did the reinstall of Window it "Cleaned" my registry file so there must be something in the AO program that is messing up....if anyone has any Ideas please advise





It's more profitable to listen than talk!
Never squander the treasures of your words! 

    On Thursday, September 21, 2023 at 01:46:44 PM MST, Christian Hartwell ***@***.***> wrote:  
 
 Join the 777alpha's server Discord Server!


| 
| 
|  | 
Join the 777alpha's server Discord Server!

Check out the 777alpha's server community on Discord - hang out with 13 other members and enjoy free voice and t...
 |

 |

 |








It's more profitable to listen than talk!
Never squander the treasures of your words! 

    On Thursday, September 21, 2023 at 01:42:22 PM PDT, chezhj ***@***.***> wrote:  
 
 


I need a link to join
