### ISSUE TITLE
AutoOrtho 0.6.0 Rendering Bugs

### ISSUE THREAD

**Issue by confile** [kubilus1/autoortho#387]
I have installed AutoOrtho 0.6.0 release and experienced some strange rendering issues. Some of the scenery looks very good, but for example at Zuerich Airport I got some strange rendering. On the first image you see some strange quares. 

image.thumb.jpeg.ddff38defb678f6567830f14d6fb3aa9.jpeg

image.thumb.jpeg.44a565df408d70ab4f0cd346653469f9.jpeg

I use Simheaven as well as Global Forests V2 with X-Plane 12. 

Here is my configuration file (scenery_packs.ini):
https://forums.x-plane.org/applications/core/interface/file/attachment.php?id=797765&key=9568489d18d67fe1d15682d9e9f741ed

Here is my Log.txt:

https://forums.x-plane.org/applications/core/interface/file/attachment.php?id=797766&key=79787bae943a19bbf29ae4f5335a0d54

I posted this issue here as well: https://forums.x-plane.org/index.php?/forums/topic/294102-autoortho-060-rendering-bugs/#comment-2605916

**Comment by Berniepe94** [comment]
i think that you are not getting the z_ao_eu on your scenery_acks.ini... its only... its suppoused to be in the middle of 

SCENERY_PACK Custom Scenery/yAutoOrtho_Overlays/
SCENERY_PACK Custom Scenery/z_ao_eu/
SCENERY_PACK Custom Scenery/z_autoortho/

im also having the same issue, if i dont take a look into that ini file also my sim start to getting in troubless. i dont know if its a error on their side!

**Comment by Jeff2122** [comment]
You are not alone. I see the strange tiles when I zoom in, but if I zoom way out they clear up. I call it "plaid" tiles. 

![Twin Otter - 2023-09-16 08 17 29](https://github.com/kubilus1/autoortho/assets/124176597/2c0b4447-341f-4a17-a96e-950f2dfe79d1)

**Comment by confile** [comment]
Is there any workaround?

**Comment by sidorovich** [comment]
have the same problem and duplicate tiles

![X-Plane Screenshot 2023 09 17 - 15 13 44 46](https://github.com/kubilus1/autoortho/assets/3040359/7eeb9b89-9618-4227-aec7-e6d38d0f8893)

**Comment by Jeff2122** [comment]
I have tried going back to v0.4.4 and it works but I get pauses intermittently while the scenery catches up. I then tried v0.5.1-3 and it seems to work just fine. It uses the same new folder structure of v0.6.0 but doesn't exhibit the plaid tile problem and doesn't pause. YMMV

**Comment by kubilus1** [comment]
> You are not alone. I see the strange tiles when I zoom in, but if I zoom way out they clear up. I call it "plaid" tiles.
> 
> ![Twin Otter - 2023-09-16 08 17 29](https://user-images.githubusercontent.com/124176597/268457323-2c0b4447-341f-4a17-a96e-950f2dfe79d1.jpg)

Those just look like low mipmap images that have been zoomed in.  I'm not sure that XPlane requests higher mipmaps when zooming.  Could also be just due to slow retrieval.  Not much to be done about that.

**Comment by kubilus1** [comment]
> have the same problem and duplicate tiles
> 
> ![X-Plane Screenshot 2023 09 17 - 15 13 44 46](https://user-images.githubusercontent.com/3040359/268500976-7eeb9b89-9618-4227-aec7-e6d38d0f8893.png)

This one is odd.  I can't reproduce duplicate tiles yet, but will take a look.

**Comment by confile** [comment]
I have a lot of this strange squares. 
![Cessna_172SP_G1000_-_2023-09-11_22_45_45_png](https://github.com/kubilus1/autoortho/assets/64265/7830ce8b-83b3-4b3f-8399-610ea208ab34)

**Comment by Jeff2122** [comment]
This is not happening to me when I use v0.5.1-3. If I switch to v0.6.x, boom!

**Comment by sidorovich** [comment]
> > have the same problem and duplicate tiles
> > ![X-Plane Screenshot 2023 09 17 - 15 13 44 46](https://user-images.githubusercontent.com/3040359/268500976-7eeb9b89-9618-4227-aec7-e6d38d0f8893.png)
> 
> This one is odd. I can't reproduce duplicate tiles yet, but will take a look.

Its reproducing for me in every flight. I can sent more information about my environment if you need. 

Could this bug be related to the fractional delimiter when float parsing as string?

**Comment by confile** [comment]
@kubilus1 any ideas how to solve that?

**Comment by Jeff2122** [comment]
@confile  The duplicate tiles have been fixed in v0.7.0 release. Download and enjoy.

**Comment by confile** [comment]
@kubilus1 thank you.

**Comment by crisk73** [comment]
> @confile The duplicate tiles have been fixed in v0.7.0 release. Download and enjoy.

Yes but the plaid tiles on the first loading remains in 0.7.0 doesn't it? Are there any params to tweak to solve this?
