### ISSUE TITLE
Autoortho scenery failing to load, failures detected

### ISSUE THREAD

**Issue by ShiforGitHub222** [kubilus1/autoortho#388]
Not sure what to make of this error but I can't get autoortho working

[autoortho.log](https://github.com/kubilus1/autoortho/files/12607268/autoortho.log)

**Comment by chezhj** [comment]
From the log I read the links can't be made some how. Did you try Dokan? For me autoortho is working with both Dokan as well as winfs installed.
I also notice you have autoortho on your C drive and xplane (steam) is on e: is that a normal accessible drive?

**Comment by Klassikfreund** [comment]
Also, ich habe das gleiche Problem. Ich wollte wieder mal XPlane11 aktivieren, weil ich mit dem Flugverhalten vom MSFS nicht zufrieden bin. Voraussetzung dafür wäre allerdings, das Autoortho funktioniert.
Ich verwende Autoortho Version 0.7.2.bin unter Ubuntu 22.04.
Das Programm läuft auch ohne Probleme, bringt mir nach dem erfolgreichen Start aber ständig o.g. Fehlermeldung!
Wer kann helfen?
