### ISSUE TITLE
Lost Autogen Scenery

### ISSUE THREAD

**Issue by rjdahlen** [kubilus1/autoortho#393]
I am running AO 0.6.0-1 using X-plane 12. I have great scenery without AO but as soon as I open AO I lose all my autogen buildings and trees. I do, however, have the ortho scenery. I run both AO and X-plane in admin mode. I did notice that the z_ao_na file does not appear in my custom scenery folder. Not sure why but that may be an issue. I have deleted and reloaded the scenery twice but that did not help. Any suggestions would be appreciated. My scenery_packs.ini file is:

I
1000 Version
SCENERY

SCENERY_PACK Custom Scenery/X-Plane Airports - KBTV Burlington/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Berlin and Frankfurt/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Budapest/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Chicago/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Dubai/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Las Vegas/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - London/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Los Angeles/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - New York/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Paris/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Portland/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Rio De Janeiro/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Saint Louis/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - San Francisco/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Sydney/
SCENERY_PACK Custom Scenery/X-Plane Landmarks - Washington DC/
SCENERY_PACK *GLOBAL_AIRPORTS*
SCENERY_PACK Custom Scenery/us-forests/
SCENERY_PACK Custom Scenery/simHeaven_X-World_America-1-vfr/
SCENERY_PACK Custom Scenery/simHeaven_X-World_America-2-regions/
SCENERY_PACK Custom Scenery/simHeaven_X-World_America-3-details/
SCENERY_PACK Custom Scenery/simHeaven_X-World_America-4-extras/
SCENERY_PACK Custom Scenery/simHeaven_X-World_America-5-footprints/
SCENERY_PACK Custom Scenery/simHeaven_X-World_America-6-scenery/
SCENERY_PACK Custom Scenery/simHeaven_X-World_America-7-forests/
SCENERY_PACK Custom Scenery/simHeaven_X-World_America-8-network/
SCENERY_PACK Custom Scenery/simHeaven_X-World_Vegetation_Library/
SCENERY_PACK Custom Scenery/yAutoOrtho_Overlays/
SCENERY_PACK Custom Scenery/z_autoortho/

Thanks for any help you can provide!!

**Comment by marloscaida** [comment]
Rjdahlen:

You must manually edit scenery_pack.ini and put the following lines at the end of everything:

SCENERY_PACK Custom Scenery/yAutoOrtho_Overlays/
SCENERY_PACK Custom Scenery/z_ao_na/
SCENERY_PACK Custom Scenery/z_autoortho/

Save the changes to the file, then open the properties of scenery_pack.ini and mark it as read-only, so that XP12 cannot overwrite it.

When you open the simulator it will generate a warning that it cannot read scenery_pack.ini, accept it and that's it.
With this you will recover all your airports.

Regards
carlos

**Comment by rjdahlen** [comment]
Thanks, Carlos!! Somewhere I missed the part about making it read only. Works great now!! Appreciate you help.
