### ISSUE TITLE
X-Plane 12 stuck at "Reading new scenery files"

### ISSUE THREAD

**Issue by Meistari** [kubilus1/autoortho#397]
**Describe the bug**
Mostly the same as described here: https://github.com/kubilus1/autoortho/issues/262

**To Reproduce**

    Open auto-ortho
    Click Run
    Open XP-12
    Start a flight

**Expected behavior**
Sim should load the scenery files and open

(please complete the following information):

    OS: Windows 11 64-bit
    XPlane Version: X-Plane 12.07r1
    AutoOrtho Version 0.6.1
    Filesystem type NTFS

**Additional context**
No errors were found. X-Plane starts normally if I don't start Autoortho before it. I added custom terrain files to resolve the previous issue (https://github.com/kubilus1/autoortho/issues/247), but such behavior happened previously sometimes too.
[Log.txt](https://github.com/kubilus1/autoortho/files/12702618/Log.txt)

**Comment by marloscaida** [comment]
Meistari:
Please try with this:

https://github.com/kubilus1/autoortho/discussions/395

work for me.

Regards
carlos

**Comment by Meistari** [comment]
> Meistari: Please try with this:
> 
> #395
> 
> work for me.
> 
> Regards carlos

Thanks, Carlos!

Doesn't work for me, unfortunately. Every time I start XP before AO all AO folders are deleted from scenery_packs.ini and now ortho loaded into sim.

**Comment by marloscaida** [comment]
unzip autoortho_win_*.zip to a directory of your choice
run the exe (I ran as admin, but don't think that is needed)
set directories & cache
install scenery and WAIT
If finished, run and then exit (ctrl-c)
run X-Plane (without running AO)
from the main menu, quit
modify scenery_packs.ini
SCENERY_PACK Custom Scenery/yAutoOrtho_Overlays/
SCENERY_PACK Custom Scenery/z_ao_eur/
SCENERY_PACK Custom Scenery/z_ao_*/ <- any other scenery you have installed
SCENERY_PACK Custom Scenery/z_autoortho/

**Comment by Meistari** [comment]
> unzip autoortho_win__.zip to a directory of your choice run the exe (I ran as admin, but don't think that is needed) set directories & cache install scenery and WAIT If finished, run and then exit (ctrl-c) run X-Plane (without running AO) from the main menu, quit modify scenery_packs.ini SCENERY_PACK Custom Scenery/yAutoOrtho_Overlays/ SCENERY_PACK Custom Scenery/z_ao_eur/ SCENERY_PACK Custom Scenery/z_ao__/ <- any other scenery you have installed SCENERY_PACK Custom Scenery/z_autoortho/

Yes, I read it. But I think that XP goes through checks itself and removes links to the sceneries if they are not called by some software. So, without starting AO before XP, every time I end up with scenery_pacs.ini without z_ao_ sceneries

**Comment by Meistari** [comment]
> unzip autoortho_win__.zip to a directory of your choice run the exe (I ran as admin, but don't think that is needed) set directories & cache install scenery and WAIT If finished, run and then exit (ctrl-c) run X-Plane (without running AO) from the main menu, quit modify scenery_packs.ini SCENERY_PACK Custom Scenery/yAutoOrtho_Overlays/ SCENERY_PACK Custom Scenery/z_ao_eur/ SCENERY_PACK Custom Scenery/z_ao__/ <- any other scenery you have installed SCENERY_PACK Custom Scenery/z_autoortho/

What ACTUALLY kinda helped me is to clean the cache every time I start AO. But then, again, I downgraded back to 0.5.1.

**Comment by marloscaida** [comment]
I think there are steps that you skip or don't attend to. Download this version which has automated closing of the CMD screen. It's a trial version but it works for me.

https://github.com/kubilus1/autoortho/releases/download/unstable/autoortho_win_unstable.zip

Run AO until the test screen appears and you have passed the test well enough. Then close AO.
Then go to scenery_pack.ini and manually add the entries corresponding to AO to the end of the file. I insist: AT THE END.
Then boot the sim until the screen appears allowing you to choose what you want to do. Stay there without doing anything.
Now, run AO with the new unstable version and wait for it to finish testing. Now the CMD display is integrated. Once this happens, choose your airport and aircraft and watch AO start to work its magic.

**Comment by marloscaida** [comment]
ATTENTION: Please verify that in the Custom Scenery folder there are no folders created by AO that repeat folders of the type z_ao_xx (where xx represents the region).

For example: z_ao_na_bk or similar folder.

This causes XP to detect them and add them to the first line of the scenery_pack.ini file, so you CANNOT see your custom or third-party airports.

Something went wrong and AO "duplicated" the symlinks. There should only be one AO folder per region.

This happened to me today and it took me a while to realize what was wrong.

Regards
carlos
