### ISSUE TITLE
No Buildings in autoortho 0.6.1

### ISSUE THREAD

**Issue by confile** [kubilus1/autoortho#407]
Hi, 

 I am using autoortho 0.6.1 and X-Plane 12.07. It turns out that there are no buildings from different libraries.

![Cessna_172SP_G1000_-_2023-10-06_23_19_53_png](https://github.com/kubilus1/autoortho/assets/64265/385f9295-3b84-43e3-9210-8ba37ccab247)

Here is my scenery_packs.ini:

[scenery_packs-ini.txt](https://github.com/kubilus1/autoortho/files/12835573/scenery_packs-ini.txt)

**Comment by jonaseberle** [comment]
You have to put your `z_*` directories in`scenery_packs.ini` below any airports (at the very bottom is usually what you want).

(You could also set `SCENERY_PACK_DISABLED Custom Scenery/yAutoOrtho_Overlays/` since you are using X-World for overlays)
