### ISSUE TITLE
Blurred/low res pictures only upon the first (i.e. not cached) loading

### ISSUE THREAD

**Issue by crisk73** [kubilus1/autoortho#417]
**Describe the bug**
The first loading of a scenery results in blurred/duplicated/low res pictures.
Subsequent loadings are ok.

**To Reproduce**
1) Empty the cache folder
2) Spawn at an airport
3) Check tile
4) Quit Xplane
5) Re-spawn at the same place
6) Check tile

**Expected behavior**
Expecting tiles to be loaded correctly since the first time.

**Screenshots**

**(please complete the following information):**
 - OS: Win 10
 - XPlane Version: XP12.07
 - AutoOrtho Version 0.7.0

This problem for me started since version 6.

Screenshots:
First loading LEBL
![first loading](https://github.com/kubilus1/autoortho/assets/74656690/e4339dac-a1a2-4a73-85b7-7a370275cb97)
Subsequent loadings LEBL
![second loading](https://github.com/kubilus1/autoortho/assets/74656690/e33ff96d-23b0-4fe4-a7cd-ba43cb7e3689)

**Comment by amg433** [comment]
Exact same problem here. Very annoying.

**Comment by crisk73** [comment]
Seems like increasing the fetch_threads value from 32 to something bigger helps in reducing the "plaid" textures.
In my tests at LEBL fetch_threads = 256 does the job by removing completely the low res areas.

**Comment by amg433** [comment]
> Seems like increasing the fetch_threads value from 32 to something bigger helps in reducing the "plaid" textures. In my tests at LEBL fetch_threads = 256 does the job by removing completely the low res areas.

I think that did it! Great find!
