### ISSUE TITLE
0.7.0

### ISSUE THREAD

**Issue by erwin4711** [kubilus1/autoortho#418]
### Discussed in https://github.com/kubilus1/autoortho/discussions/414

<div type='discussions-op-text'>

<sup>Originally posted by **kubilus1** October 13, 2023</sup>
## What's Changed
* Show logs in config UI.  Adjust how we kick off execution by @kubilus1 in https://github.com/kubilus1/autoortho/pull/398
* Fix 'duplicate' best chunk tile matches by @kubilus1 in https://github.com/kubilus1/autoortho/pull/409
* Only validate existing sceneries when necessary by @kubilus1 in https://github.com/kubilus1/autoortho/pull/411

**Full Changelog**: https://github.com/kubilus1/autoortho/compare/0.6.1...0.7.0

<hr /><em>This discussion was created from the release <a href='https://github.com/kubilus1/autoortho/releases/tag/0.7.0'>0.7.0</a>.</em></div>

**Comment by erwin4711** [comment]
6.1. ran fine on my system . After installing 7.0 menu appears but dissapears;  so no starting up anymore ( used WinFSP and tried Dokan) . ( bytheway: didn't delete autoortho cache

**Comment by marloscaida** [comment]
erwin4711:
You should see the AO log. But I'm almost sure that AO has generated an extra folder with a name similar to z_ao_xx_bkp or something like that. You have to delete these AO backup folders from Custom Scenery, rearrange the order in scenery_pack.ini and then run AO.
Remember that you must start the simulator until the screen that asks you for an aircraft and airport. You stop there and start AO until you perform the test and it passes OK. Then, continue with the start of the simulator.
Regards
carlos

**Comment by erwin4711** [comment]
In fact what happened was: i made the terrible mistake by assuming the program STOPT working but that was not the case: It had just minimized on starup!!! OMG my bad.
So conclusion : It runs fine!
