### ISSUE TITLE
2023/10/23

### ISSUE THREAD

**Issue by PacifickFR42** [kubilus1/autoortho#426]
**Describe the bug**
X-Plane 11.55 random crash when use AutoOrtho (0.7.0)

0:45:55.088 I/ATC: ROBIN 2+2 (DR-400) 3YV, Gap Tallard altimeter 2 9 8 7.
0:46:30.560 E/ATC: Tried playing a wave file that doesn't exist: ')'
0:46:32.827 I/SCN: DSF load time: 286 for file Custom Scenery/simHeaven_VFR-Aerials/Earth nav data/+40+000/+45+008.dsf (0 tris, 0 skipped for 0.0 m^2)
0:46:32.827 I/SCN: DSF load time: 1293 for file Custom Scenery/simHeaven_VFR-Aerials/Earth nav data/+40+000/+45+006.dsf (0 tris, 0 skipped for 0.0 m^2)
0:46:32.827 I/SCN: DSF load time: 21084 for file Custom Scenery/simHeaven_VFR-Landmarks/Earth nav data/+40+000/+45+006.dsf (0 tris, 0 skipped for 0.0 m^2)
0:46:32.827 I/SCN: DSF load time: 26983 for file Custom Scenery/simHeaven_VFR-Landmarks/Earth nav data/+40+000/+45+008.dsf (0 tris, 0 skipped for 0.0 m^2)
0:46:32.827 I/SCN: DSF load time: 878 for file Custom Scenery/simHeaven_X-Europe-1-vfr/Earth nav data/+40+000/+45+008.dsf (0 tris, 0 skipped for 0.0 m^2)
0:46:32.827 I/SCN: DSF load time: 13013 for file Custom Scenery/simHeaven_X-Europe-3-details/Earth nav data/+40+000/+45+006.dsf (0 tris, 0 skipped for 0.0 m^2)
0:46:32.827 I/SCN: DSF load time: 10997 for file Custom Scenery/simHeaven_X-Europe-3-details/Earth nav data/+40+000/+45+008.dsf (0 tris, 0 skipped for 0.0 m^2)
0:46:32.971 I/SCN: DSF load time: 96884 for file Custom Scenery/simHeaven_X-Europe-4-extras/Earth nav data/+40+000/+45+006.dsf (0 tris, 0 skipped for 0.0 m^2)
0:46:33.016 I/SCN: DSF load time: 31756 for file Custom Scenery/simHeaven_X-Europe-5-footprints/Earth nav data/+40+000/+45+006.dsf (0 tris, 0 skipped for 0.0 m^2)
0:46:33.016 I/SCN: DSF load time: 134706 for file Custom Scenery/simHeaven_X-Europe-4-extras/Earth nav data/+40+000/+45+008.dsf (0 tris, 0 skipped for 0.0 m^2)
0:46:33.113 I/SCN: DSF load time: 104699 for file Custom Scenery/simHeaven_X-Europe-5-footprints/Earth nav data/+40+000/+45+008.dsf (0 tris, 0 skipped for 0.0 m^2)
0:46:33.156 I/SCN: DSF load time: 146511 for file Custom Scenery/simHeaven_X-Europe-6-scenery/Earth nav data/+40+000/+45+006.dsf (0 tris, 0 skipped for 0.0 m^2)
0:46:33.200 I/SCN: DSF load time: 47602 for file Custom Scenery/simHeaven_X-Europe-7-forests/Earth nav data/+40+000/+45+006.dsf (0 tris, 0 skipped for 0.0 m^2)
0:46:33.431 I/SCN: DSF load time: 291357 for file Custom Scenery/simHeaven_X-Europe-6-scenery/Earth nav data/+40+000/+45+008.dsf (0 tris, 0 skipped for 0.0 m^2)
0:46:33.431 I/SCN: DSF load time: 202694 for file Custom Scenery/simHeaven_X-Europe-8-network/Earth nav data/+40+000/+45+006.dsf (0 tris, 0 skipped for 0.0 m^2)
0:46:33.478 I/SCN: DSF load time: 55146 for file Custom Scenery/simHeaven_X-Europe-7-forests/Earth nav data/+40+000/+45+008.dsf (0 tris, 0 skipped for 0.0 m^2)
0:46:33.529 I/SCN: DSF load time: 80869 for file Custom Scenery/Global Airports/Earth nav data/+40+000/+45+006.dsf (0 tris, 0 skipped for 0.0 m^2)
0:46:33.666 I/SCN: DSF load time: 118987 for file Custom Scenery/yAutoOrtho_Overlays/Earth nav data/+40+000/+45+006.dsf (0 tris, 0 skipped for 0.0 m^2)
0:46:33.921 I/SCN: DSF load time: 411455 for file Custom Scenery/simHeaven_X-Europe-8-network/Earth nav data/+40+000/+45+008.dsf (0 tris, 0 skipped for 0.0 m^2)
0:46:34.195 I/SCN: DSF load time: 218216 for file Custom Scenery/Global Airports/Earth nav data/+40+000/+45+008.dsf (0 tris, 0 skipped for 0.0 m^2)
0:46:34.408 I/SCN: DSF load time: 181024 for file Custom Scenery/yAutoOrtho_Overlays/Earth nav data/+40+000/+45+008.dsf (0 tris, 0 skipped for 0.0 m^2)
--=={This application has crashed!}==--
**(please complete the following information):**
 - OS: Linux Ubuntu 22.04
 - XPlane Version: 11
 - AutoOrtho Version 0.7.0
 - Filesystem type EXT4 with FUSE (documentation)

**Comment by chezhj** [comment]
What does autoOrtho log say... because xplane can crash because of many reasons

**Comment by PacifickFR42** [comment]
> Que dit le journal autoOrtho... parce que xplane peut planter pour de nombreuses raisons

AutoOrtho : 
INFO:aostats:STATS: ID: {'cur_mem_mb': 2685, 'chunk_miss': 168720, 'req_ok': 139633, 'bytes_dl': 1987352414, 'tile_mem_miss': 17425, 'count': 404804, 'chunk_hit': 268096, 'partial_mm_averages': {0: 0.001}, 'partial_mm_counts': {0: 17570}, 'mm_counts': {0: -1, 1: 390, 2: 962, 3: 1672, 4: 14561}, 'mm_averages': {0: -1, 1: 0.034, 2: 0.01, 3: 0.003, 4: 0.001}, 'retry_chunk_count': 10569, 'backup_chunk_count': 2919, 'chunk_missing_count': 1111, 'tile_mem_hits': 143, 'minutes_to_start': 3.96}
INFO:aostats:STATS: ID: {'cur_mem_mb': 2685, 'chunk_miss': 168797, 'req_ok': 139707, 'bytes_dl': 1987993332, 'tile_mem_miss': 17428, 'count': 404945, 'chunk_hit': 268163, 'partial_mm_averages': {0: 0.001}, 'partial_mm_counts': {0: 17573}, 'mm_counts': {0: -1, 1: 391, 2: 962, 3: 1673, 4: 14562}, 'mm_averages': {0: -1, 1: 0.034, 2: 0.01, 3: 0.003, 4: 0.001}, 'retry_chunk_count': 10570, 'backup_chunk_count': 2919, 'chunk_missing_count': 1111, 'tile_mem_hits': 143, 'minutes_to_start': 3.96}
INFO:aostats:STATS: ID: {'cur_mem_mb': 2685, 'chunk_miss': 168843, 'req_ok': 139747, 'bytes_dl': 1988337573, 'tile_mem_miss': 17433, 'count': 405088, 'chunk_hit': 268266, 'partial_mm_averages': {0: 0.001}, 'partial_mm_counts': {0: 17578}, 'mm_counts': {0: -1, 1: 391, 2: 964, 3: 1673, 4: 14565}, 'mm_averages': {0: -1, 1: 0.034, 2: 0.01, 3: 0.003, 4: 0.001}, 'retry_chunk_count': 10573, 'backup_chunk_count': 2919, 'chunk_missing_count': 1111, 'tile_mem_hits': 143, 'minutes_to_start': 3.96}
INFO:autoortho_fuse:OPEN: Detected DSF open: /Earth nav data/+40+030/+48+031.dsf
INFO:autoortho_fuse:OPEN: Detected DSF open: /Earth nav data/+40+030/+48+031.dsf
INFO:autoortho_fuse:RELEASE: Detected DSF close: /Earth nav data/+40+030/+48+031.dsf
INFO:autoortho_fuse:OPEN: Detected DSF open: /Earth nav data/+40+020/+48+029.dsf
INFO:aostats:STATS: ID: {'cur_mem_mb': 2685, 'chunk_miss': 168939, 'req_ok': 139832, 'bytes_dl': 1989406182, 'tile_mem_miss': 17444, 'count': 405363, 'chunk_hit': 268456, 'partial_mm_averages': {0: 0.001}, 'partial_mm_counts': {0: 17589}, 'mm_counts': {0: -1, 1: 391, 2: 966, 3: 1677, 4: 14570}, 'mm_averages': {0: -1, 1: 0.034, 2: 0.01, 3: 0.003, 4: 0.001}, 'retry_chunk_count': 10577, 'backup_chunk_count': 2919, 'chunk_missing_count': 1111, 'tile_mem_hits': 143, 'minutes_to_start': 3.96}
INFO:flighttrack:FT: Flight disconnected.
INFO:flighttrack:UDP listen thread exiting...
INFO:flighttrack:UDP listen thread exiting...
INFO:flighttrack:UDP listen thread exiting...


X-plane 11 : 
3:46:34.131 I/ATC: S-76 6XP, Climb and maintain 9 thousand.
124thATC v2.0-a61 01:14:15: DEBUG: Checking obstacles...
3:46:39.173 I/ATC: Up to 9 thousand, S-76 6XP.
3:46:39.403 I/SCN: DSF load time: 12217 for file Custom Scenery/simHeaven_VFR-Landmarks/Earth nav data/+40+030/+48+031.dsf (0 tris, 0 skipped for 0.0 m^2)
3:46:39.403 I/SCN: DSF load time: 5417 for file Custom Scenery/simHeaven_VFR-Landmarks/Earth nav data/+40+020/+48+029.dsf (0 tris, 0 skipped for 0.0 m^2)
3:46:39.403 I/SCN: DSF load time: 3243 for file Custom Scenery/simHeaven_X-Europe-3-details/Earth nav data/+40+030/+48+031.dsf (0 tris, 0 skipped for 0.0 m^2)
3:46:39.403 I/SCN: DSF load time: 2404 for file Custom Scenery/simHeaven_X-Europe-3-details/Earth nav data/+40+020/+48+029.dsf (0 tris, 0 skipped for 0.0 m^2)
3:46:39.444 I/SCN: DSF load time: 40047 for file Custom Scenery/simHeaven_X-Europe-4-extras/Earth nav data/+40+030/+48+031.dsf (0 tris, 0 skipped for 0.0 m^2)
3:46:39.444 I/SCN: DSF load time: 46310 for file Custom Scenery/simHeaven_X-Europe-4-extras/Earth nav data/+40+020/+48+029.dsf (0 tris, 0 skipped for 0.0 m^2)
3:46:39.516 I/SCN: DSF load time: 62216 for file Custom Scenery/simHeaven_X-Europe-5-footprints/Earth nav data/+40+030/+48+031.dsf (0 tris, 0 skipped for 0.0 m^2)
3:46:39.516 I/SCN: DSF load time: 74237 for file Custom Scenery/simHeaven_X-Europe-5-footprints/Earth nav data/+40+020/+48+029.dsf (0 tris, 0 skipped for 0.0 m^2)
3:46:39.561 I/SCN: DSF load time: 64802 for file Custom Scenery/simHeaven_X-Europe-6-scenery/Earth nav data/+40+030/+48+031.dsf (0 tris, 0 skipped for 0.0 m^2)
3:46:39.603 I/SCN: DSF load time: 23377 for file Custom Scenery/simHeaven_X-Europe-7-forests/Earth nav data/+40+030/+48+031.dsf (0 tris, 0 skipped for 0.0 m^2)
3:46:39.603 I/SCN: DSF load time: 72153 for file Custom Scenery/simHeaven_X-Europe-6-scenery/Earth nav data/+40+020/+48+029.dsf (0 tris, 0 skipped for 0.0 m^2)
3:46:39.603 I/SCN: DSF load time: 18776 for file Custom Scenery/simHeaven_X-Europe-7-forests/Earth nav data/+40+020/+48+029.dsf (0 tris, 0 skipped for 0.0 m^2)
3:46:39.643 I/SCN: DSF load time: 40999 for file Custom Scenery/simHeaven_X-Europe-8-network/Earth nav data/+40+030/+48+031.dsf (0 tris, 0 skipped for 0.0 m^2)
3:46:39.688 I/SCN: DSF load time: 38788 for file Custom Scenery/simHeaven_X-Europe-8-network/Earth nav data/+40+020/+48+029.dsf (0 tris, 0 skipped for 0.0 m^2)
3:46:39.688 I/SCN: DSF load time: 21141 for file Custom Scenery/yAutoOrtho_Overlays/Earth nav data/+40+030/+48+031.dsf (0 tris, 0 skipped for 0.0 m^2)
3:46:39.688 I/SCN: DSF load time: 21852 for file Custom Scenery/yAutoOrtho_Overlays/Earth nav data/+40+020/+48+029.dsf (0 tris, 0 skipped for 0.0 m^2)
--=={This application has crashed!}==--

I Joint scenery_packs.ini
[scenery_packs.ini.txt](https://github.com/kubilus1/autoortho/files/13080764/scenery_packs.ini.txt)

**Comment by PacifickFR42** [comment]
Autre plantage, là aucune info pertinente dans le log de AutoOrtho, seul celui de XP11 : 

1:39:43.856 I/SCN: DSF load time: 78606 for file Custom Scenery/simHeaven_X-Europe-8-network/Earth nav data/+40+020/+46+029.dsf (0 tris, 0 skipped for 0.0 m^2)
1:39:43.901 I/SCN: DSF load time: 52112 for file Custom Scenery/yAutoOrtho_Overlays/Earth nav data/+40+020/+46+029.dsf (0 tris, 0 skipped for 0.0 m^2)
1:39:45.541 I/SCN: DSF load time: 1809371 for file Custom Scenery/z_ao_eur/Earth nav data/+40+030/+46+031.dsf (219320 tris, 21 skipped for -2.9 m^2)
1:39:46.179 E/DSF: The DSF Custom Scenery/simHeaven_X-Europe-8-network/Earth nav data/+40+030/+46+031.dsf has a number of problems with its road network: 1 doubled nodes, 0 direction reverses, 0 short segments, 1 roads deleted.
--=={This application has crashed!}==--

**Comment by chezhj** [comment]
Although my French is not that good, I find nothing that suggest AO is the problem of XP11 crashing. Have a look at the windows events and see if there was an error reported.

**Comment by PacifickFR42** [comment]
> Bien que mon français ne soit pas très bon, je ne trouve rien qui suggère qu'AO soit le problème du crash de XP11. Jetez un œil aux événements Windows et voyez si une erreur a été signalée.

Hello,
No, I'm on Linux, without AO, my flight has no problem...
So obviously something goes wrong at some point.

**Comment by chezhj** [comment]
Then I don't know, not on linux myself. Still I suggest to look at other logs, as AO is using fuse, might be a problem there..

**Comment by PacifickFR42** [comment]
> Alors je ne sais pas, pas moi-même sous Linux. Je suggère néanmoins de consulter d'autres journaux, car AO utilise un fusible, cela pourrait y être un problème.

Good idea, I'll look at that and come back...

**Comment by helixcraig** [comment]
Just raised another issue - but it's the same as this I realised. I get random crashes - most flights in fact crash mid-flight. I'm on Linux Mint 21.2 (Ubuntu based). Have a look at the issue I created.
I rolled back to 0.4.4 which is the last version I can run without the issue so it's definitely introduced since then. I also am very confident that it's AO causing the crashes as I removed all other plug-ins and scenery additions. Still got problem. Removed AO and problem went away. Added AO v0.7.0 back and problem back again.

**Comment by PacifickFR42** [comment]
"Je suis revenu à la version 0.4.4" Do you have some link ?

**Comment by helixcraig** [comment]
You can get 0.4.4 here. https://github.com/kubilus1/autoortho/releases/download/0.4.4/autoortho_lin.bin
0.4.4 runs on my system flawlessly. I haven't tested 0.5.1, but 0.6.0 and above introduces this issue.
Usually about an hour into a flight before X-Plane crashes.
