### ISSUE TITLE
AutoOrtho incorrectly assumes that Dokan is installed by the existence of the file dokanfuse2.dll

### ISSUE THREAD

**Issue by toadlife** [kubilus1/autoortho#435]
**Describe the bug**
I've found that the the Dokan uninstaller fails to remove three .dll files from the %systemroot%\system32 directory. These files are dokan2.dll, dokanfuse2.dll and dokannp2.dll.  After Dokan is uninstalled, Autoortho incorrectly assumes that dokan is installed by the existence of the file dokanfuse2.dl and tries to use it, causing Autoortho to fail to mount the scenery. I found this by turning on debug mode and looking a the log.  See attached log.

[autoortho.log](https://github.com/kubilus1/autoortho/files/13185713/autoortho.log)

Most Windows users don't read logs, so perhaps it would be better to make WinFSP or Dokan an option that is settable on the settings GUI, so that autoortho doesn't have to get in the mess of detecting whether or not Dokan is really installed on Windows.

**To Reproduce**
1. Install Dokan 2.0
2. Uninstall Dokan 2.0
3. Run autoortho and try to mount the scenery

**(please complete the following information):**
 - OS: Windows 11
 - XPlane Version: 12.07
 - AutoOrtho Version 0.7
 - Filesystem type NTFS

**Additional context**

**Comment by Peppone220** [comment]
All solved
On my computer Dokan created problems. I uninstalled Dokan and installed Winfsp then I completely uninstalled Orto Auto and then installed Ortho 0.7.0 again. And everything works perfectly.

**Comment by toadlife** [comment]
@Peppone220 unfortunately, those steps don't work for everyone.  Dokan doesn't work on my computer no matter what I do. I uninstalled and reinstalled everything ad nauseum. When Dokan mounts the directories I can read the mounted folder via browsing them in Windows explorer but X-Plane immediately throws an error upon reading the scenery. For now, I'm using WinFSP. Before it stopped working, the only change on my system I can think of is the installation of the latest Microsoft updates.

**Comment by Peppone220** [comment]
> @Peppone220 unfortunately, those steps don't work for everyone. Dokan doesn't work on my computer no matter what I do. I uninstalled and reinstalled everything ad nauseam. When Dokan mounts the directories I can read the mounted folder via browsing them in Windows explorer but X-Plane immediately throws an error upon reading the scenery. For now, I'm using WinFSP. Before it stopped working, the only change on my system I can think of is the installation of the latest Microsoft updates.
-------------------------------------
![LEZL](https://github.com/kubilus1/autoortho/assets/74368213/463050e3-185e-4460-97a7-f8de5e721f0d)

Yes, in fact, it always works, for example, now I have problems in loading X-Plane because immediately after that autoporto I finished loading the tiles of an airport (LPPT or Lezl) and begins to prepare the X-Plane scenario crashes. This does not happen if take -off from LPFR.
However, after landing in Lezl, when I go to a gate the airport buildings disappear as you can see in the image that I am attachment
