### ISSUE TITLE
0.7.0

### ISSUE THREAD

**Issue by libello123** [kubilus1/autoortho#436]
Hi
Windows 10
12.07r1

europa download always hangs like this:[[](url)
![Autoortho](https://github.com/kubilus1/autoortho/assets/70951562/b251d191-5e14-42c6-a384-13e2f4d31336)

**Comment by Peppone220** [comment]
I have the same problem, after various attempts, the download speed is really very low, I managed to do it completely, after 8 hours of download, but it does not go out.
Just now I'm reinstating Autortho 0.7.0 again after having uninstall the entire previous installation.
I also saw that on my computer it doesn't work with Dokan while it seems to work with Winfsp.
I hope that the ongoing installation is the problem.
Now the download has a speed of 1.28 Mbps, indeed now 0.69 the day before yesterday was 0.18 truly unacceptable.
If you have other news please keep me informed, my post is at this link https://github.com/kublus1/autotoHOHo/issues/435
Have a good evening

**Comment by Peppone220** [comment]
All solved
On my computer Dokan created problems. I uninstalled Dokan and installed Winfsp then I completely uninstalled Orto Auto and then installed Ortho 0.7.0 again. And everything works perfectly.
