### ISSUE TITLE
Error multiple times with diferrents continents

### ISSUE THREAD

**Issue by Rodreca** [kubilus1/autoortho#442]
Hello guys could you please help me..

I try to start the download and start as normal but in some point i get this error, other time a get the error 233 relared with the Windows

**Screenshots**
![image](https://github.com/kubilus1/autoortho/assets/65636040/f4ea7802-692d-4185-bcc3-ec821b5d665c)

**(please complete the following information):**
 - Windows 11
 - XPlane Version: XP11 v11.0.55.1
 - AutoOrtho Version 0.7.0

**Comment by Neuse87** [comment]
Same issue here

**Comment by mojo130** [comment]
This is happening to me. Initially with Europe but that finally downloaded, Australia and North America same if not similar errors all the time.
