### ISSUE TITLE
AutoOrtho 0.7.0 with WinFSP: X-plane 12 rearranges sceneries order so autoOrtho packs are placed at the top

### ISSUE THREAD

**Issue by StamTso** [kubilus1/autoortho#443]
**Describe the bug**
This is the same behavior described in [this bug report](https://github.com/kubilus1/autoortho/issues/356) but for the 0.7.0 version. When running with winFSP, X-Plane will rearrange the sceneries to the top, even if they were at the bottom of the file before. Also, when X-Plane closes, it will delete the references from the sceneries file. When using Dokan the issue doesn't exist, files remain in the correct order.

**To Reproduce**
1. Install winFSP
2. Modify scenery_packs.ini file and add the AutoOrtho packs in the correct order
3. Start X-Plane and wait till it loads in the initial screen
4. Notice the pack order has changed
5. Close X-Plane
6. Notice z_ao_xx packs have been deleted from scenery_packs.ini

**Expected behavior**
Pack order should be maintained similarly to how it works with Dokan.

**(please complete the following information):**
 - OS: Windows 11
 - XPlane Version: XP12 12.07r1
 - AutoOrtho Version 0.7.0
 - Filesystem type NTFS

**Additional context**
This bug was supposedly fixed in the previous version (0.6.1).

**Comment by chezhj** [comment]
Are you using SAM? Because changing to manual links in SAM fixed this for me

**Comment by StamTso** [comment]
Yes I'm using SAM, I'll try to make the change and see if it fixes it.
