### ISSUE TITLE
autoortho 7 exe crashes instantly

### ISSUE THREAD

**Issue by rboven** [kubilus1/autoortho#455]
**Describe the bug**
XP12 8 windows 10
Dokan loaded
clicking exe opening screen shows 2 sec and closes
log attached
[autoortho.log](https://github.com/kubilus1/autoortho/files/13316774/autoortho.log)

**To Reproduce**

**Expected behavior**

**Screenshots**

**(please complete the following information):**
 - OS: [e.g. Windows 11]
 - XPlane Version: [e.g. XP12 beta 4]
 - AutoOrtho Version [e.g. 0.4.3]
 - Filesystem type (NTFS, exFAT, etc)

**Additional context**

**Comment by FuchyBe** [comment]
Hello, I have the exact same issue here
[autoortho.log](https://github.com/kubilus1/autoortho/files/13335012/autoortho.log)

**Comment by rboven** [comment]
Solved--installed AO on other drive and that worked
