### ISSUE TITLE
'Chunk_miss' Error prohibits using AO

### ISSUE THREAD

**Issue by srothe-oslo** [kubilus1/autoortho#462]
**Describe the bug**

As reported by others, an issue occurs when using AO after first run and restarting the pc (e.g. next day).
AO works as should directly after installation. After restart of the PC and "RUN" AO, the initial checks look fine in the log, but then a repetitive message (see below) appears.  X-Plane 12 throws an error message about not being able to run with the scenery.

Seems to be an unsolved issue for more than just a few users.

This is the repetitive error message from the AO log.

> INFO:aostats:STATS: ID: {'cur_mem_mb': 95, 'chunk_miss': 6, 'req_ok': 6, 'bytes_dl': 98930}

Everything before looks perfectly normal.
**To Reproduce**

**Expected behavior**
I expected the sceneries to load correctly into X-Plane 12.

**Screenshots**

**(please complete the following information):**
 - OS: Windows 10
 - XPlane Version: X-Plane 12.0.7
 - AutoOrtho Version 0.7.1
 - Filesystem type NTFS

**Additional context**
Seems to be an issue for many users and is a showstopper

**Comment by devidin** [comment]
Same issue for me...

**Comment by Maxmotoring** [comment]
Same here:

INFO:aostats:STATS: ID: {'cur_mem_mb': 96, 'chunk_miss': 6, 'req_ok': 6, 'bytes_dl': 89597}

Windows 10
AutoOrtho 0.7.2

No joy

**Comment by comandantefelipe674** [comment]
@srothe-oslo This can happen, if some Mesh Sceneries are above the orthos in the scenery_pack.ini Maybe you have some Airport Mesh above the orthos?
