### ISSUE TITLE
Autoortho just crash 2-3 sec after the UI open

### ISSUE THREAD

**Issue by FuchyBe** [kubilus1/autoortho#463]
**Describe the bug**
Autoortho just crash 2-3 sec after the UI open

**To Reproduce**

**Expected behavior**

**Screenshots**

**(please complete the following information):**
 - OS: [e.g. Windows 11]
 - XPlane Version: [12.0.8-rc-3]
 - AutoOrtho Version [0.7.1]
 - Filesystem type (NTFS)

**Additional context**

**Comment by FuchyBe** [comment]
[autoortho.log](https://github.com/kubilus1/autoortho/files/13627209/autoortho.log)

**Comment by FuchyBe** [comment]
find the solution:
in: C:\Users\your username
erase the file: .autoortho.

**Comment by rtc79clm** [comment]
I am experiencing the same issue, just a sudden crash to desktop and crash report.
