### ISSUE TITLE
"Error loading scenery: z_ao_sa. - X-Plane can't run with this packaged installed."

### ISSUE THREAD

**Issue by filis14325** [kubilus1/autoortho#471]
I can't run AutoOrtho in X-Plane 12. I ran AO before starting xp, i had my .ini file organized. Re-installed it 3 times, 1 using only Dokan, the other only WinFSP and the other tried both on the same run; nothing worked, same error message. Is it a problem with 0.7.1? 
![image](https://github.com/kubilus1/autoortho/assets/155380227/0a0aced2-ab18-4d5f-8af9-efe03b1360eb) - Full error message
[Log.txt](https://github.com/kubilus1/autoortho/files/13842691/Log.txt) - Log file of the last run using Dokan that resulted in same error message for all of the other runs.

 - OS: Windows 10
 - XPlane Version: 12.0.8
 - AutoOrtho Version 0.7.1
 - Filesystem type NTFS

**Comment by mikecbr** [comment]
Same here

**Comment by nicknystrom** [comment]
Same, my log file has nearly identical lines like:
```
0:00:43.586 E/SCN: ***Error with scenery file "+43-096.dsf" (io_dsf.cpp:776.)***
0:00:43.586 E/SCN: The terrain file 'terrain/95952_61344_BI18.ter' could not be loaded.
```

**Comment by ArashHosseini** [comment]
Same issue here however this happens during flight. Crash on startup just happend if my ```scenery_pack.ini``` config file was messy, @filis14325 can you pls post your ```scenery_pack.ini```.
I found for myself, reducing the [fetch_threads](https://github.com/kubilus1/autoortho/blob/7f5b3f265d128d8860cbe0c2fa0d0a570a18c28c/autoortho/getortho.py#L89) in autoortho conf helps me to do first successful landing without crash on approach. According to the documentation, fetch_threads are passed to requests's HTTPAdapter.
`:param pool_connections: The number of urllib3 connection pools to cache.
 :param pool_maxsize: The maximum number of connections to save in the pool.`
i did following steps:
1. In my case it was the single core threads index of 32, reduce it to ~25
2. going from DOKAN to WinFSP
3. reducing graphhical setting in xplane to give autoortho processes some reserve

**Comment by filis14325** [comment]
> Same issue here however this happens during flight. Crash on startup just happend if my `scenery_pack.ini` config file was messy, @filis14325 can you pls post your `scenery_pack.ini`. I found for myself, reducing the [fetch_threads](https://github.com/kubilus1/autoortho/blob/7f5b3f265d128d8860cbe0c2fa0d0a570a18c28c/autoortho/getortho.py#L89) in autoortho conf helps me to do first successful landing without crash on approach. According to the documentation, fetch_threads are passed to requests's HTTPAdapter. `:param pool_connections: The number of urllib3 connection pools to cache. :param pool_maxsize: The maximum number of connections to save in the pool.` i did following steps:
> 
> 1. In my case it was the single core threads index of 32, reduced it to ~25 (i saw in my config that xplane(vulkan) is facing memory issues, i assume this high thread number will create instability during Load Time and Execution Time)
> 2. reducing graphhical setting in xplane according to your system's bottleneck to give autoortho processes some space

My `scenery_pack.ini` currently looks like this:
[scenery_packs.txt](https://github.com/kubilus1/autoortho/files/13874127/scenery_packs.txt)

If you think it's fine and could assist me through the steps of changing the core threads are used, I'd be glad

**Comment by ArashHosseini** [comment]
@filis14325 your scenery_pack.ini is fine so far i see. Search in your main autoortho install folder for the config file, and post pls your CPU type

**Comment by filis14325** [comment]
I'm running on a i3-12100f
As a note, I've already found the configuration and changed it to the value you did. I'll test it soon and get back to you

**Comment by ArashHosseini** [comment]
Perfect, what was the original value? I assume 8, You have to understand that you have adopt the value based on your CPU, for example I would reduce it to 5 in your case *if it was 8

**Comment by ArashHosseini** [comment]
Ok I assumed 32 is calculated based on max cpu threads, I will check the documentation, can you post your graphical settings in meantime?

**Comment by filis14325** [comment]
I'm also running on a RTX4060, 
Textures - High
SSAO - Medium
TSR - Off
Antialiasing - 2X MSAA
Anisotropic - 16x
Clouds - High
Shadows - Aircraft only
Render distance - High
Object density - High
Tree density - High

**Comment by ArashHosseini** [comment]
if able, pls reduce everything down, specially the cpu related settings and repeat the process.

**Comment by filis14325** [comment]
Just tried that - same result. It also gets the problem on the "reading new scenery" part of the loading process, which took longer, but just crashed anyway. I might just give up on AO for now and wait for XP12.1.0 which improves overall CPU performance

**Comment by SandaleAir** [comment]
Hello,

I have the same Problem with Version 0.7.1! This problem does not occur with version 0.4.4.

Greetings,
Sascha.

**Comment by AlbertoA340** [comment]
Same here.
I tried changing the fetch_threds and also installing winsp and nothing 
CPU:i713700k
GPU RTX4080
RAM 32gbddr5
