### ISSUE TITLE
scenery download stuck

### ISSUE THREAD

**Issue by iMurofaca** [kubilus1/autoortho#473]
hi my download is stuck and wont download anything
![Captura de pantalla 2024-01-06 221507](https://github.com/kubilus1/autoortho/assets/66839666/f5e4b148-60ed-49b1-84dc-8fc8ab1d0ad6)

**Comment by BenjaCalj** [comment]
have you found any solution to this??

**Comment by iMurofaca** [comment]
Unfortunately no

**Comment by BenjaCalj** [comment]
Try leaving your pc on for several hours even if you get the loop message on the log , sa took me like 6 hours to download

**Comment by iMurofaca** [comment]
8h stuck

**Comment by muff11n** [comment]
easy fix download manually from that link here on github, you can download in parallel too, the app recognizes already downloaded scenery files, tested multiple times
