### ISSUE TITLE
Ortho tiles not showing since 12.0.9 scenery update

### ISSUE THREAD

**Issue by tommypank** [kubilus1/autoortho#477]
**Describe the bug**
AO tiles not showing

**To Reproduce**
Run as normal

**Expected behavior**
Tiles load as normal, no tiles loading

**Screenshots**
n/a

**(please complete the following information):**
 - OS: [e.g. Windows 11]
 - XPlane Version: 12.0.9 RC4 (w Scenery update)
 - AutoOrtho Version 0.7.1
 - Filesystem type NTFS

**Additional context**
Checks complete in log and everything checks out ok

Seems to be 'miss chunk' for each tile in the log

**Comment by StamTso** [comment]
I'm in the same system and X-Plane version and everything works like before. Double-check your AO installation, particularly in your Custom Scenery folder if you miss any *z_ao_xx* or the *yAutoOrtho_Overlays* folders. Also, check if you have any interfering custom sceneries/ortho/overlays around the airport/area you are testing. A lot of times custom airports that come with their own ortho and mesh don't play nice with AO tiles.

**Comment by CaptainAbeer** [comment]
Hi Sam, I tried what you suggested. The Xplane 12 worked perfectly once but after a restart it again gave errors. The same working perfectly for Xplane 11 but not for 12.

**Comment by muff11n** [comment]
I can confirm ortho works, problems are:

low res/pixelated tiles, would be nice to be able to increase quality
no seasons support
tested multiple times heathrow airport tiles fail to download, doesn't matter what map source
