### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by fascox** [kubilus1/autoortho#495]
**Describe the bug**
Short flight (less than 200 miles) 
python process memory allocation 
reaches over 30 GB and more. 
also from log NUM OPEN TILES never decrease 

**Expected behavior**
Correct memory management involves freeing allocated unused memory when closing tiles.

**Screenshots**
![image](https://github.com/kubilus1/autoortho/assets/700221/7bbfa9af-94f6-4044-a323-dfe6a2fc0911)

**(please complete the following information):**

 - OS: MacOS Sonoma 14.3.1
 - XPlane Version: XP12 1.0.9 RC5
 - AutoOrtho Version 0.7.2
 - Filesystem type APFS

**Comment by SkyDog** [comment]
Had the same Problem with Linux. Currently testing with Windows.

**Comment by pavlozs** [comment]
I had the same problem and downgrading Python from 3.12 to 3.10 helped me. 

Apple M3 pro Sonoma 14.4.1

**Comment by fascox** [comment]
> I had the same problem and downgrading Python from 3.12 to 3.10 helped me. 
> 
> 
> 
> Apple M3 pro Sonoma 14.4.1

I tried using Python version 3.10, but unfortunately the issue persists. I'm using an Apple MacMini M2 with Sonoma@latest.

**Comment by ninjazx12r** [comment]
Mini M2, same problem.

**Comment by max-h-silverman** [comment]
Ditto here. Macbook pro M1 sequoia. 60gb used by python after 45min

**Comment by max-h-silverman** [comment]
@kubilus1 Any thoughts on this? Everything is working perfectly on mac M1 except for this memory leak.
