### ISSUE TITLE
AutoOrtho does nothing on launch

### ISSUE THREAD

**Issue by LoneAviator41** [kubilus1/autoortho#501]
**Describe the bug**
I've always had bugs with Ortho. Got it for XP12 about 8 months ago, and never got it to work properly. Several chunks wouldn't load and it just impacted my frames way too much for vatsim, so I ended up installing it. Tried it again on XP11. Worked decently, but was having issues with my NVME drive constantly blue-screening my PC when playing XP11, and uninstalled Ortho hoping it might fix the issue (it did not). So third times a charm now, and I reinstalled it, and now it does nothing when I click the launcher. I just get the little blue loading circle next to my mouse for about 5 seconds, then nothing happens (yes, I have tried running as admin. Same result). I did a fresh reinstall on Dokan as well and WinFSP too. I completely deleted all AO sceneries from my custom scenery folder, deleted my .autoortho-data folder in the users folder as well. 

**(please complete the following information):**
 - OS: Windows 10
 - XPlane Version: XP12
 - AutoOrtho Version: 0.7.2
 - Filesystem type: not sure.

**Comment by derekhe** [comment]
Maybe another choice here? https://github.com/derekhe/xplane-map-enhancement-release/wiki

**Comment by approxdec** [comment]
i feel your pain @LoneAviator41 
i ahve a new system, windows 11.
AutoOrtho worked for me on first install but now there is no response
from either clicking on the .exe or using the start menu.

i was hopeful for a while when you mention the NVME drive issue.
x plane 12 begins but crashes to reboot or shutdown on my system
and after reading your comments i moved the x plane folder to 
SSD drive. x plane 12 ran for a short while but crashed to reboot.
it was worth a try
