### ISSUE TITLE
AutoOrtho app not showing available scenery to download

### ISSUE THREAD

**Issue by tomer1290** [kubilus1/autoortho#506]
**Describe the bug**
When I enter the app I cant download the scenery

**To Reproduce**
1. download Download AutoOrtho 0.7.0
2. set up everything according to the tutorial
4. save and restart the app and go to the scenery tab

**Expected behavior**
download the satellite scenery 

**Screenshots**
![image](https://github.com/kubilus1/autoortho/assets/103571550/9aa10210-9ee1-4fbf-acf8-7818bd4700bb)

**(please complete the following information):**
 - OS: Windows 10 
 - XPlane Version: XP12.0.9
 - AutoOrtho Version 0.7.2
 - Filesystem type NTFS

**Additional context**
i see this error on the log: 
WARNING:downloader:Couldn't update release info <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>.

**Comment by tomer1290** [comment]
I was able to solve the problem by downloading the "--upgrade certifi" folder in Python

**Comment by ctilley83** [comment]
> I was able to solve the problem by downloading the "--upgrade certifi" folder in Python

What do you mean by this?

**Comment by tkalfaoglu** [comment]
I think he meant:
$ pip3 install certifi --upgrade
