### ISSUE TITLE
KBHM UNDER WATER 

### ISSUE THREAD

**Issue by mikecbr** [kubilus1/autoortho#508]
**Describe the bug**
KBH, airport and alabama in usa is underwatter

**To Reproduce**
1. Go to '...' KBHM airport

**Expected behavior**
not underwater

**(please complete the following information):**
 - OS: [e.g. Windows 11]
 - XPlane Version:  XP1209
 - AutoOrtho Version 7.2
 - Filesystem type (NTFS, exFAT, etc)

**Additional context**

**Comment by A9qx** [comment]
While I haven't spawned into KBHM myself, I can verify there is some weird tiling issues in that region. I was flying KORD - KTPA earlier today and as I was crossing over Alabama/Mississippi/Georgia/Tennessee area there was this huge ocean that was covering a chunk of that region that obviously isn't supposed to be there. So I can verify there is something odd going on in this region, I agree.

**Comment by marekschneider** [comment]
There is a patch for it on x-plane.org: https://forums.x-plane.org/index.php?/files/file/90288-autoortho-scenery-sets-patches/
