### ISSUE TITLE
AutoOrtho no buildings when running

### ISSUE THREAD

**Issue by Ts-Matvey** [kubilus1/autoortho#526]
I have tried downloading AutoOrtho. It works well: all tiles load with the correct satellite imagery. I, however, get no buildings or roads or airports spawning in. I tried searching on YouTube and forums for an answer with no luck. I am using WinFSP instead of Dokan because of a separate issue. When I check my X-Plane 11 log file, I have a suspicion that x-Plane loads the overlays above everything else, which s why I don't get the buildings. My scenery.ini file seems to be in the correct order. I already tried restarting my PC and trying different load orders in the scenery.ini file with no success. I'll attach my log and scenery.ini file below. All help is appreciated

[Log.txt](https://github.com/user-attachments/files/16055456/Log.txt)
[Scenery.ini copy.txt](https://github.com/user-attachments/files/16055504/Scenery.ini.copy.txt)

**Comment by dedebublitz** [comment]
I am having the same issue.

**Comment by sebasop320** [comment]
Same issue.
