### ISSUE TITLE
AO issues on M2 Mac Pro

### ISSUE THREAD

**Issue by Birbsayshennlo** [kubilus1/autoortho#539]
I am not very sufficient in knowledge about these three things, AO, MacFuse and Python. I went on a school trip and was away for 2 nights. i come back and open terminal to run autoortho. The first thing i notice is that it says my name and then IP. Before I can't remember, but I think it said my name. Then here is the big part. I run autoortho with:

cd autoortho

python3.10 autoortho

I then see Autoortho starting, but...

No Autoortho window. I can't configure autoortho, run or download sceneries, whatsoever. I am in a stage without Autoortho.

Here's my log

Last login: Wed Sep  4 21:26:11 on ttys000

ryanxu@{IP Address} ~ % cd autoortho

ryanxu@{IP} autoortho % python3.10 autoortho

Config file found /Users/ryanxu/.autoortho reading...

Found sceneries: ['z_ao_Alps_HD_XP12', 'z_ao_afr', '.DS_Store', 'z_ao_aus_pac', 'z_ao_asi', 'z_ao_sa', 'z_ao_afr copy 2', 'z_ao_eur', 'z_ao_na']

[{'root': '/Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_Alps_HD_XP12', 'mount': '/Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_Alps_HD_XP12'}, {'root': '/Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_afr', 'mount': '/Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_afr'}, {'root': '/Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/.DS_Store', 'mount': '/Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/.DS_Store'}, {'root': '/Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_aus_pac', 'mount': '/Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_aus_pac'}, {'root': '/Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_asi', 'mount': '/Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_asi'}, {'root': '/Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_sa', 'mount': '/Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_sa'}, {'root': '/Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_afr copy 2', 'mount': '/Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_afr copy 2'}, {'root': '/Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_eur', 'mount': '/Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_eur'}, {'root': '/Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_na', 'mount': '/Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_na'}]

Saving config ... 

Wrote config file: /Users/ryanxu/.autoortho

Mac OS Version is 14.5 and patch enabled so applying the patch

Applyting Mac OS 12.3+ Alpha Channel fix.  Your default Alpha Channel is now 0.99

INFO:__main__:Setup logs: /Users/ryanxu/.autoortho-data/logs, log level: 20

INFO:autoortho:AutoOrtho version: ref: refs/heads/macos-0.7.2

INFO:aostats:Creating stats object

INFO:flighttrack:Start flighttracker...

INFO:aostats:Starting stats thread

INFO:autoortho:Running headless

INFO:autoortho:Running in multi-threaded mode.

INFO:autoortho:Running in multi-threaded mode.

INFO:autoortho:Running in multi-threaded mode.

INFO:autoortho:Running in multi-threaded mode.

INFO:autoortho:Running in multi-threaded mode.

INFO:autoortho:Running in multi-threaded mode.

INFO:autoortho:Existing mountpoint detected: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_afr

INFO:autoortho:Existing mountpoint detected: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_Alps_HD_XP12

INFO:autoortho:Running in multi-threaded mode.

INFO:autoortho:Running in multi-threaded mode.

INFO:autoortho:Setting up mountpoint: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/.DS_Store

INFO:autoortho:Running in multi-threaded mode.

INFO:autoortho:Existing mountpoint detected: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_aus_pac

INFO:autoortho:Existing mountpoint detected: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_sa

INFO:autoortho:Existing mountpoint detected: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_asi

ERROR:autoortho:Exception detected when running FUSE mount: Failed to setup mount point /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/.DS_Store!.  Exiting...

INFO:autoortho:Existing mountpoint detected: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_na

INFO:autoortho:Detected placeholder dir.  Removing: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_na

INFO:autoortho:Existing mountpoint detected: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_afr copy 2

INFO:autoortho:Existing mountpoint detected: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_eur

INFO:autoortho:Setting up mountpoint: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_asi

INFO:autoortho:Setting up mountpoint: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_sa

INFO:autoortho:Setting up mountpoint: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_afr

INFO:autoortho:Setting up mountpoint: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_aus_pac

INFO:autoortho:Setting up mountpoint: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_Alps_HD_XP12

INFO:autoortho:Running in FUSE mode.

INFO:autoortho:Setting up mountpoint: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_eur

INFO:autoortho:Setting up mountpoint: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_afr copy 2

INFO:autoortho:Running in FUSE mode.

INFO:autoortho:Setting up mountpoint: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_na

INFO:autoortho:Running in FUSE mode.

INFO:autoortho:Running in FUSE mode.

INFO:autoortho:AutoOrtho:  root: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_asi  mountpoint: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_asi

INFO:autoortho:Running in FUSE mode.

INFO:autoortho:Running in FUSE mode.

INFO:autoortho:AutoOrtho:  root: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_sa  mountpoint: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_sa

INFO:autoortho:Running in FUSE mode.

INFO:autoortho:AutoOrtho:  root: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_afr  mountpoint: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_afr

INFO:autoortho:AutoOrtho:  root: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_aus_pac  mountpoint: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_aus_pac

INFO:autoortho:Running in FUSE mode.

INFO:autoortho:AutoOrtho:  root: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_Alps_HD_XP12  mountpoint: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_Alps_HD_XP12

INFO:autoortho:AutoOrtho:  root: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_eur  mountpoint: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_eur

INFO:autoortho:AutoOrtho:  root: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_afr copy 2  mountpoint: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_afr copy 2

INFO:autoortho:AutoOrtho:  root: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_na  mountpoint: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_na

INFO:getortho:chunk_getter: <getortho.ChunkGetter object at 0x118596830>

LIBFUSE: 4703473568 : <CDLL '/usr/local/lib/libfuse.dylib', handle 9fde1430 at 0x118594fa0>

INFO:autoortho_fuse:ROOT: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_asi

INFO:autoortho_fuse:ROOT: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_sa

INFO:autoortho_fuse:ROOT: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_afr

INFO:autoortho_fuse:ROOT: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_aus_pac

INFO:autoortho_fuse:ROOT: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_Alps_HD_XP12

INFO:autoortho_fuse:ROOT: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_eur

INFO:autoortho_fuse:ROOT: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_afr copy 2

INFO:getortho:Maptype override not set, will use default.

INFO:autoortho_fuse:ROOT: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_na

INFO:getortho:Maptype override not set, will use default.

INFO:getortho:Maptype override not set, will use default.

INFO:getortho:Maptype override not set, will use default.

INFO:getortho:Maptype override not set, will use default.

INFO:getortho:Maptype override not set, will use default.

INFO:getortho:Maptype override not set, will use default.

INFO:getortho:Will use Compressor: ISPC

INFO:getortho:Maptype override not set, will use default.

INFO:getortho:Will use Compressor: ISPC

INFO:getortho:Will use Compressor: ISPC

INFO:getortho:Will use Compressor: ISPC

INFO:getortho:Will use Compressor: ISPC

INFO:getortho:Will use Compressor: ISPC

INFO:getortho:Will use Compressor: ISPC

INFO:getortho:Cache dir: /Users/ryanxu/.autoortho-data/cache

INFO:getortho:Will use Compressor: ISPC

INFO:getortho:Cache dir: /Users/ryanxu/.autoortho-data/cache

INFO:getortho:Cache dir: /Users/ryanxu/.autoortho-data/cache

INFO:getortho:Cache dir: /Users/ryanxu/.autoortho-data/cache

INFO:getortho:Cache dir: /Users/ryanxu/.autoortho-data/cache

INFO:getortho:Cache dir: /Users/ryanxu/.autoortho-data/cache

INFO:getortho:Cache dir: /Users/ryanxu/.autoortho-data/cache

INFO:getortho:Started tile clean thread.  Mem limit 1073741824

INFO:autoortho_fuse:MOUNT: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_asi

INFO:getortho:Cache dir: /Users/ryanxu/.autoortho-data/cache

INFO:getortho:Started tile clean thread.  Mem limit 1073741824

INFO:autoortho_fuse:MOUNT: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_sa

INFO:getortho:Started tile clean thread.  Mem limit 1073741824

INFO:autoortho_fuse:MOUNT: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_afr

INFO:getortho:Started tile clean thread.  Mem limit 1073741824

INFO:autoortho_fuse:MOUNT: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_aus_pac

INFO:getortho:Started tile clean thread.  Mem limit 1073741824

INFO:autoortho_fuse:MOUNT: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_Alps_HD_XP12

INFO:getortho:Started tile clean thread.  Mem limit 1073741824

INFO:autoortho_fuse:MOUNT: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_eur

INFO:getortho:Started tile clean thread.  Mem limit 1073741824

INFO:autoortho_fuse:MOUNT: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_afr copy 2

INFO:getortho:Started tile clean thread.  Mem limit 1073741824

INFO:autoortho_fuse:MOUNT: /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_na

mount_macfuse: mount point /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_sa is itself on a macFUSE volume

ERROR:autoortho:Exception detected when running FUSE mount: 1.  Exiting...

mount_macfuse: mount point /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_afr is itself on a macFUSE volume

ERROR:autoortho:Exception detected when running FUSE mount: 1.  Exiting...

mount_macfuse: mount point /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_aus_pac is itself on a macFUSE volume

ERROR:autoortho:Exception detected when running FUSE mount: 1.  Exiting...

mount_macfuse: mount point /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_asi is itself on a macFUSE volume

ERROR:autoortho:Exception detected when running FUSE mount: 1.  Exiting...

INFO:geocoder.base:Requested http://ipinfo.io/json

INFO:autoortho:Waiting for mounts...

INFO:autoortho:.

mount_macfuse: mount point /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_eur is itself on a macFUSE volume

ERROR:autoortho:Exception detected when running FUSE mount: 1.  Exiting...

mount_macfuse: mount point /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_afr copy 2 is itself on a macFUSE volume

ERROR:autoortho:Exception detected when running FUSE mount: 1.  Exiting...

mount_macfuse: mount point /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_ao_Alps_HD_XP12 is itself on a macFUSE volume

ERROR:autoortho:Exception detected when running FUSE mount: 1.  Exiting...

INFO:autoortho:.

INFO:autoortho:.

INFO:autoortho:.

INFO:aostats:STATS: ID: {'cur_mem_mb': 67}

INFO:autoortho:.

INFO:autoortho:

INFO:autoortho:------------------------------------

INFO:autoortho: Diagnostic check ...

INFO:autoortho:------------------------------------

INFO:autoortho:Detected system: uname_result(system='Darwin', node='192-168-1-100.tpgi.com.au', release='23.5.0', version='Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020', machine='arm64')

INFO:autoortho:Detected location Melbourne, Victoria, AU

INFO:autoortho:Detected installed scenery:

INFO:autoortho:    /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_Alps_HD_XP12

INFO:autoortho:        Mounted? True

INFO:autoortho:    /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_afr

INFO:autoortho:        Mounted? True

INFO:autoortho:    /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/.DS_Store

INFO:autoortho:        Mounted? False

INFO:autoortho:    /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_aus_pac

INFO:autoortho:        Mounted? True

INFO:autoortho:    /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_asi

INFO:autoortho:        Mounted? True

INFO:autoortho:    /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_sa

INFO:autoortho:        Mounted? True

INFO:autoortho:    /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_afr copy 2

INFO:autoortho:        Mounted? True

INFO:autoortho:    /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_eur

INFO:autoortho:        Mounted? True

INFO:autoortho:    /Users/ryanxu/Desktop/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_na

INFO:autoortho:        Mounted? True

INFO:autoortho:Checking maptypes:

WARNING:getortho:Failed with status 403 to get chunk Chunk(2176,3232,EOX,13,13) on server a.

WARNING:autoortho:    Maptype: Null FAILED!

INFO:autoortho:    Maptype: BI OK!

INFO:autoortho:    Maptype: NAIP OK!

WARNING:getortho:Failed with status 403 to get chunk Chunk(2176,3232,EOX,13,13) on server a.

WARNING:autoortho:    Maptype: EOX FAILED!

INFO:autoortho:    Maptype: USGS OK!

INFO:autoortho:    Maptype: Firefly OK!

INFO:autoortho:Checking DDS file compression:

INFO:autoortho:    ISPC OK!

INFO:autoortho:------------------------------------

WARNING:autoortho:***************

WARNING:autoortho:***************

WARNING:autoortho:FAILURES DETECTED!!

WARNING:autoortho:Please review logs and setup.

WARNING:autoortho:***************

WARNING:autoortho:***************

INFO:aostats:STATS: ID: {'cur_mem_mb': 67, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 67, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 72, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 72, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 72, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 54, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 54, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 54, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 54, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 54, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 54, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 54, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 54, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 54, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 54, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 54, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 54, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 54, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 54, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 54, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 54, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 54, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 52, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 52, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 52, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 46, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 46, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 46, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 46, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 46, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 46, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 46, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 46, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 46, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 32, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 32, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 32, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 25, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 25, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 25, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 25, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 25, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

INFO:aostats:STATS: ID: {'cur_mem_mb': 25, 'chunk_miss': 6, 'http_403': 2, 'req_err': 2, 'req_ok': 4, 'bytes_dl': 70615}

**Comment by keisisqrl** [comment]
I'm having _possibly_ the same issue. Same errors in the log, I put the MacOS crash report for python in a gist:

https://gist.github.com/keisisqrl/7ac09dbf223f03bbcc0de3ddf0915487

**Comment by keisisqrl** [comment]
Found a solution - this is a Tk bug of all things, and something missing in the instructions.

Make sure you follow _all of_ the instructions in this: https://github.com/zodiac1214/autoortho/blob/macos-0.7.2/docs/index.md

It sounds like you did - but before step 8, there should be a step to run:
`brew tap --force homebrew/core`

Otherwise the next command (which builds tcl-tk) will do it for you and overwrite your changes.

This is a fairly new change to homebrew, I suspect the authors (like me) have used it for a long time.
