### ISSUE TITLE
[Feature Request] Map Provider HERE

### ISSUE THREAD

**Issue by NNowakowski** [kubilus1/autoortho#60]
I see that there are various Map Providers we're able to pick from if we want something other than Bing.
Personally I'm using HERE in my manual Ortho4XP setup but I've noticed that this isn't an option for autoortho.
Can we have that one added here?

Ortho4XP creates the URL inside the O4_Custom_URL.py file; the referenced function get_Here_value() actually isn't needed necessarily but can be replaced by newest inside the URL.
That would leave the URL as something like this:
```python
url="https://"+random.choice(['1','2','3','4'])+".aerial.maps.api.here.com/maptile/2.1/maptile/newest/satellite.day/"+str(tilematrix)+"/"+str(til_x)+"/"+str(til_y)+"/256/jpg?app_id=VgTVFr1a0ft1qGcLCVJ6&app_code=LJXqQ8ErW71UsRUK3R33Ow"
```

I had to replace the appId and appCode with a newer one I received from the website requests; I'm not sure how long these are actually valid for so perhaps they should be configurable somehow? Ortho4XP still reads .py files even when running the binary version so changing these from time to time isn't really an issue there; I'm not sure if autoortho also supports that.

**Comment by kubilus1** [comment]
Having this more of a plugin style would definitely be nice to have.  I'll look into how supporting sources that require auth.
