### ISSUE TITLE
I am getting an issue when I install AutoOrtho.

### ISSUE THREAD

**Issue by FlightSimulator101** [kubilus1/autoortho#85]
So I downloaded autoortho and my Malwarebytes is saying that it has a spyware and also I tested it out with virus total and it says the same thing.

**Comment by FlightSimulator101** [comment]
![image](https://user-images.githubusercontent.com/11083046/227639623-3a3a98f4-b60d-4219-b797-1e7021bac99b.png)

**Comment by kubilus1** [comment]
Over aggressive virus scanning.  Try submitting as a false positive.
