### ISSUE TITLE
getting an issue after downloading a continent

### ISSUE THREAD

**Issue by vexx13** [kubilus1/autoortho#86]
Hi, I seem to be getting this error when I download a continent. This happens when I launch xp after installation.
![X-Plane Screenshot 2023 03 26 - 15 33 36 28](https://user-images.githubusercontent.com/128977338/227776164-c4e5c5ab-a1fe-4c40-bd93-fc5ee1a8f54f.png)

**Comment by mckleashey123** [comment]
Did you click run and get the Firewall Window that asked for allow?
