### ISSUE TITLE
Vigorf.A Trojan detected by MS Defender

### ISSUE THREAD

**Issue by JayPi01** [kubilus1/autoortho#91]
When I download 0.3.1-4/autoortho_win.zip Windows 11 Defender detects Trojan:Win32/Vigorf.A

**Comment by BlaineElMono** [comment]
me too

**Comment by kubilus1** [comment]
False positive.  You can either ignore it or run directly via source code instead.

**Comment by Troyer69** [comment]
Please could you explain me how to run directly via source code instead?

**Comment by hakanr339b** [comment]
Windows Defender be like that idk why, im a bit concerned too

**Comment by kubilus1** [comment]
Windows defender pretty much flags every python based program packaged as
an exe.  Lazy garbage malware algorithm.  I have some ideas for a
workaround but little time ATM to dig in.
