### ISSUE TITLE
Weird LOD issues (wrong tile showing up)

### ISSUE THREAD

**Issue by evilstiefel** [kubilus1/autoortho#98]
Not sure if this was introduced with 0.4.0+, but I now sometimes have tiles which are colored as if they come from a different zoomlevel. When zooming in, they get replaced buy another tile which is color-matched with the surrounding tiles, repeatably so (zooming out I get off-color textures again).

See attached example, looking at the region around the riverbed.

![image](https://user-images.githubusercontent.com/8029370/230677040-5532c334-c345-43e3-939b-1350741a06a9.png)
![image](https://user-images.githubusercontent.com/8029370/230677061-a2331c3a-631d-4647-ba51-760e63db4f7a.png)

**Comment by kubilus1** [comment]
As designed.  Those are tiles that timed out, so you have a lower res version.  You can adjust this in your config file, try increasing maxwait time.  That will trade lag for quality.

**Comment by evilstiefel** [comment]
Alright, just weird that the "higher" fidelity tiles are used for some surface areas even when zoomed out, and they are evidently preset (since they show up when zoomed in). So you're saying, zoomed out, the light-grey tiles should cover everything, but 95% of them timed out?

Incidently, what does the factor stand for? Minutes? Default value is 0.5 and mine was already set to 1.0 when taking these screens.
